// Code generated by tools/codegen - DO NOT EDIT
package vehicle

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI Vehicle_Create
func Create(modelid int32, x float32, y float32, z float32, rotation float32, color1 int32, color2 int32, respawnDelay int32, addSiren bool, id *int32) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_Create(modelid, x, y, z, rotation, color1, color2, respawnDelay, addSiren, id)
	return omp.NewVehicle(res)
}

// Destroy wraps CAPI Vehicle_Destroy
func Destroy(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_Destroy(vehicle.Handle())
}

// FromID wraps CAPI Vehicle_FromID
func FromID(vehicleid int32) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_FromID(vehicleid)
	return omp.NewVehicle(res)
}

// GetID wraps CAPI Vehicle_GetID
func GetID(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetID(vehicle.Handle())
}

// GetMaxPassengerSeats wraps CAPI Vehicle_GetMaxPassengerSeats
func GetMaxPassengerSeats(modelid int32) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetMaxPassengerSeats(modelid)
}

// IsStreamedIn wraps CAPI Vehicle_IsStreamedIn
func IsStreamedIn(vehicle *omp.Vehicle, player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_IsStreamedIn(vehicle.Handle(), player.Handle())
}

// GetPos wraps CAPI Vehicle_GetPos
func GetPos(vehicle *omp.Vehicle, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetPos(vehicle.Handle(), x, y, z)
}

// SetPos wraps CAPI Vehicle_SetPos
func SetPos(vehicle *omp.Vehicle, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetPos(vehicle.Handle(), x, y, z)
}

// GetZAngle wraps CAPI Vehicle_GetZAngle
func GetZAngle(vehicle *omp.Vehicle) float32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetZAngle(vehicle.Handle())
}

// GetRotationQuat wraps CAPI Vehicle_GetRotationQuat
func GetRotationQuat(vehicle *omp.Vehicle, w *float32, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetRotationQuat(vehicle.Handle(), w, x, y, z)
}

// GetDistanceFromPoint wraps CAPI Vehicle_GetDistanceFromPoint
func GetDistanceFromPoint(vehicle *omp.Vehicle, x float32, y float32, z float32) float32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetDistanceFromPoint(vehicle.Handle(), x, y, z)
}

// SetZAngle wraps CAPI Vehicle_SetZAngle
func SetZAngle(vehicle *omp.Vehicle, angle float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetZAngle(vehicle.Handle(), angle)
}

// SetParamsForPlayer wraps CAPI Vehicle_SetParamsForPlayer
func SetParamsForPlayer(vehicle *omp.Vehicle, player *omp.Player, objective int32, doors int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetParamsForPlayer(vehicle.Handle(), player.Handle(), objective, doors)
}

// UseManualEngineAndLights wraps CAPI Vehicle_UseManualEngineAndLights
func UseManualEngineAndLights() bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_UseManualEngineAndLights()
}

// SetParamsEx wraps CAPI Vehicle_SetParamsEx
func SetParamsEx(vehicle *omp.Vehicle, engine int32, lights int32, alarm int32, doors int32, bonnet int32, boot int32, objective int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetParamsEx(vehicle.Handle(), engine, lights, alarm, doors, bonnet, boot, objective)
}

// GetParamsEx wraps CAPI Vehicle_GetParamsEx
func GetParamsEx(vehicle *omp.Vehicle, engine *int32, lights *int32, alarm *int32, doors *int32, bonnet *int32, boot *int32, objective *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetParamsEx(vehicle.Handle(), engine, lights, alarm, doors, bonnet, boot, objective)
}

// GetParamsSirenState wraps CAPI Vehicle_GetParamsSirenState
func GetParamsSirenState(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetParamsSirenState(vehicle.Handle())
}

// SetParamsCarDoors wraps CAPI Vehicle_SetParamsCarDoors
func SetParamsCarDoors(vehicle *omp.Vehicle, frontLeft int32, frontRight int32, rearLeft int32, rearRight int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetParamsCarDoors(vehicle.Handle(), frontLeft, frontRight, rearLeft, rearRight)
}

// GetParamsCarDoors wraps CAPI Vehicle_GetParamsCarDoors
func GetParamsCarDoors(vehicle *omp.Vehicle, frontLeft *int32, frontRight *int32, rearLeft *int32, rearRight *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetParamsCarDoors(vehicle.Handle(), frontLeft, frontRight, rearLeft, rearRight)
}

// SetParamsCarWindows wraps CAPI Vehicle_SetParamsCarWindows
func SetParamsCarWindows(vehicle *omp.Vehicle, frontLeft int32, frontRight int32, rearLeft int32, rearRight int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetParamsCarWindows(vehicle.Handle(), frontLeft, frontRight, rearLeft, rearRight)
}

// GetParamsCarWindows wraps CAPI Vehicle_GetParamsCarWindows
func GetParamsCarWindows(vehicle *omp.Vehicle, frontLeft *int32, frontRight *int32, rearLeft *int32, rearRight *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetParamsCarWindows(vehicle.Handle(), frontLeft, frontRight, rearLeft, rearRight)
}

// SetToRespawn wraps CAPI Vehicle_SetToRespawn
func SetToRespawn(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetToRespawn(vehicle.Handle())
}

// LinkToInterior wraps CAPI Vehicle_LinkToInterior
func LinkToInterior(vehicle *omp.Vehicle, interiorid int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_LinkToInterior(vehicle.Handle(), interiorid)
}

// AddComponent wraps CAPI Vehicle_AddComponent
func AddComponent(vehicle *omp.Vehicle, componentid int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_AddComponent(vehicle.Handle(), componentid)
}

// RemoveComponent wraps CAPI Vehicle_RemoveComponent
func RemoveComponent(vehicle *omp.Vehicle, componentid int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_RemoveComponent(vehicle.Handle(), componentid)
}

// ChangeColor wraps CAPI Vehicle_ChangeColor
func ChangeColor(vehicle *omp.Vehicle, color1 int32, color2 int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_ChangeColor(vehicle.Handle(), color1, color2)
}

// ChangePaintjob wraps CAPI Vehicle_ChangePaintjob
func ChangePaintjob(vehicle *omp.Vehicle, paintjobid int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_ChangePaintjob(vehicle.Handle(), paintjobid)
}

// SetHealth wraps CAPI Vehicle_SetHealth
func SetHealth(vehicle *omp.Vehicle, health float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetHealth(vehicle.Handle(), health)
}

// GetHealth wraps CAPI Vehicle_GetHealth
func GetHealth(vehicle *omp.Vehicle) float32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetHealth(vehicle.Handle())
}

// AttachTrailer wraps CAPI Vehicle_AttachTrailer
func AttachTrailer(trailer *omp.Vehicle, vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_AttachTrailer(trailer.Handle(), vehicle.Handle())
}

// DetachTrailer wraps CAPI Vehicle_DetachTrailer
func DetachTrailer(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_DetachTrailer(vehicle.Handle())
}

// IsTrailerAttached wraps CAPI Vehicle_IsTrailerAttached
func IsTrailerAttached(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_IsTrailerAttached(vehicle.Handle())
}

// GetTrailer wraps CAPI Vehicle_GetTrailer
func GetTrailer(vehicle *omp.Vehicle) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_GetTrailer(vehicle.Handle())
	return omp.NewVehicle(res)
}

// SetNumberPlate wraps CAPI Vehicle_SetNumberPlate
func SetNumberPlate(vehicle *omp.Vehicle, numberPlate string) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetNumberPlate(vehicle.Handle(), numberPlate)
}

// GetModel wraps CAPI Vehicle_GetModel
func GetModel(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetModel(vehicle.Handle())
}

// GetComponentInSlot wraps CAPI Vehicle_GetComponentInSlot
func GetComponentInSlot(vehicle *omp.Vehicle, slot int32) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetComponentInSlot(vehicle.Handle(), slot)
}

// GetComponentType wraps CAPI Vehicle_GetComponentType
func GetComponentType(componentid int32) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetComponentType(componentid)
}

// CanHaveComponent wraps CAPI Vehicle_CanHaveComponent
func CanHaveComponent(modelid int32, componentid int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_CanHaveComponent(modelid, componentid)
}

// GetRandomColorPair wraps CAPI Vehicle_GetRandomColorPair
func GetRandomColorPair(modelid int32, color1 *int32, color2 *int32, color3 *int32, color4 *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetRandomColorPair(modelid, color1, color2, color3, color4)
}

// ColorIndexToColor wraps CAPI Vehicle_ColorIndexToColor
func ColorIndexToColor(colorIndex int32, alpha int32) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_ColorIndexToColor(colorIndex, alpha)
}

// Repair wraps CAPI Vehicle_Repair
func Repair(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_Repair(vehicle.Handle())
}

// GetVelocity wraps CAPI Vehicle_GetVelocity
func GetVelocity(vehicle *omp.Vehicle, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetVelocity(vehicle.Handle(), x, y, z)
}

// SetVelocity wraps CAPI Vehicle_SetVelocity
func SetVelocity(vehicle *omp.Vehicle, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetVelocity(vehicle.Handle(), x, y, z)
}

// SetAngularVelocity wraps CAPI Vehicle_SetAngularVelocity
func SetAngularVelocity(vehicle *omp.Vehicle, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetAngularVelocity(vehicle.Handle(), x, y, z)
}

// GetDamageStatus wraps CAPI Vehicle_GetDamageStatus
func GetDamageStatus(vehicle *omp.Vehicle, panels *int32, doors *int32, lights *int32, tires *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetDamageStatus(vehicle.Handle(), panels, doors, lights, tires)
}

// UpdateDamageStatus wraps CAPI Vehicle_UpdateDamageStatus
func UpdateDamageStatus(vehicle *omp.Vehicle, panels int32, doors int32, lights int32, tires int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_UpdateDamageStatus(vehicle.Handle(), panels, doors, lights, tires)
}

// GetModelInfo wraps CAPI Vehicle_GetModelInfo
func GetModelInfo(vehiclemodel int32, infotype int32, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetModelInfo(vehiclemodel, infotype, x, y, z)
}

// SetVirtualWorld wraps CAPI Vehicle_SetVirtualWorld
func SetVirtualWorld(vehicle *omp.Vehicle, virtualWorld int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetVirtualWorld(vehicle.Handle(), virtualWorld)
}

// GetVirtualWorld wraps CAPI Vehicle_GetVirtualWorld
func GetVirtualWorld(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetVirtualWorld(vehicle.Handle())
}

// GetLandingGearState wraps CAPI Vehicle_GetLandingGearState
func GetLandingGearState(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetLandingGearState(vehicle.Handle())
}

// IsValid wraps CAPI Vehicle_IsValid
func IsValid(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_IsValid(vehicle.Handle())
}

// AddStatic wraps CAPI Vehicle_AddStatic
func AddStatic(modelid int32, x float32, y float32, z float32, angle float32, color1 int32, color2 int32, id *int32) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_AddStatic(modelid, x, y, z, angle, color1, color2, id)
	return omp.NewVehicle(res)
}

// AddStaticEx wraps CAPI Vehicle_AddStaticEx
func AddStaticEx(modelid int32, x float32, y float32, z float32, angle float32, color1 int32, color2 int32, respawnDelay int32, addSiren bool, id *int32) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_AddStaticEx(modelid, x, y, z, angle, color1, color2, respawnDelay, addSiren, id)
	return omp.NewVehicle(res)
}

// EnableFriendlyFire wraps CAPI Vehicle_EnableFriendlyFire
func EnableFriendlyFire() bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_EnableFriendlyFire()
}

// GetSpawnInfo wraps CAPI Vehicle_GetSpawnInfo
func GetSpawnInfo(vehicle *omp.Vehicle, x *float32, y *float32, z *float32, rotation *float32, color1 *int32, color2 *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetSpawnInfo(vehicle.Handle(), x, y, z, rotation, color1, color2)
}

// SetSpawnInfo wraps CAPI Vehicle_SetSpawnInfo
func SetSpawnInfo(vehicle *omp.Vehicle, modelid int32, x float32, y float32, z float32, rotation float32, color1 int32, color2 int32, respawnTime int32, interior int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetSpawnInfo(vehicle.Handle(), modelid, x, y, z, rotation, color1, color2, respawnTime, interior)
}

// GetModelCount wraps CAPI Vehicle_GetModelCount
func GetModelCount(modelid int32) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetModelCount(modelid)
}

// GetModelsUsed wraps CAPI Vehicle_GetModelsUsed
func GetModelsUsed() int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetModelsUsed()
}

// GetPaintjob wraps CAPI Vehicle_GetPaintjob
func GetPaintjob(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetPaintjob(vehicle.Handle())
}

// GetColor wraps CAPI Vehicle_GetColor
func GetColor(vehicle *omp.Vehicle, color1 *int32, color2 *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetColor(vehicle.Handle(), color1, color2)
}

// GetInterior wraps CAPI Vehicle_GetInterior
func GetInterior(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetInterior(vehicle.Handle())
}

// GetNumberPlateString wraps CAPI Vehicle_GetNumberPlate and returns a string.
func GetNumberPlateString(vehicle *omp.Vehicle) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetNumberPlateString(vehicle.Handle())
}

// SetRespawnDelay wraps CAPI Vehicle_SetRespawnDelay
func SetRespawnDelay(vehicle *omp.Vehicle, respawnDelay int32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetRespawnDelay(vehicle.Handle(), respawnDelay)
}

// GetRespawnDelay wraps CAPI Vehicle_GetRespawnDelay
func GetRespawnDelay(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetRespawnDelay(vehicle.Handle())
}

// GetCab wraps CAPI Vehicle_GetCab
func GetCab(vehicle *omp.Vehicle) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_GetCab(vehicle.Handle())
	return omp.NewVehicle(res)
}

// GetTower wraps CAPI Vehicle_GetTower
func GetTower(vehicle *omp.Vehicle) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_GetTower(vehicle.Handle())
	return omp.NewVehicle(res)
}

// GetOccupiedTick wraps CAPI Vehicle_GetOccupiedTick
func GetOccupiedTick(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetOccupiedTick(vehicle.Handle())
}

// GetRespawnTick wraps CAPI Vehicle_GetRespawnTick
func GetRespawnTick(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetRespawnTick(vehicle.Handle())
}

// HasBeenOccupied wraps CAPI Vehicle_HasBeenOccupied
func HasBeenOccupied(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_HasBeenOccupied(vehicle.Handle())
}

// IsOccupied wraps CAPI Vehicle_IsOccupied
func IsOccupied(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_IsOccupied(vehicle.Handle())
}

// IsDead wraps CAPI Vehicle_IsDead
func IsDead(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_IsDead(vehicle.Handle())
}

// SetParamsSirenState wraps CAPI Vehicle_SetParamsSirenState
func SetParamsSirenState(vehicle *omp.Vehicle, sirenState bool) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_SetParamsSirenState(vehicle.Handle(), sirenState)
}

// ToggleSirenEnabled wraps CAPI Vehicle_ToggleSirenEnabled
func ToggleSirenEnabled(vehicle *omp.Vehicle, status bool) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_ToggleSirenEnabled(vehicle.Handle(), status)
}

// IsSirenEnabled wraps CAPI Vehicle_IsSirenEnabled
func IsSirenEnabled(vehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_IsSirenEnabled(vehicle.Handle())
}

// GetLastDriver wraps CAPI Vehicle_GetLastDriver
func GetLastDriver(vehicle *omp.Vehicle) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_GetLastDriver(vehicle.Handle())
	return omp.NewVehicle(res)
}

// GetDriver wraps CAPI Vehicle_GetDriver
func GetDriver(vehicle *omp.Vehicle) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_GetDriver(vehicle.Handle())
	return omp.NewVehicle(res)
}

// GetSirenState wraps CAPI Vehicle_GetSirenState
func GetSirenState(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetSirenState(vehicle.Handle())
}

// GetHydraReactorAngle wraps CAPI Vehicle_GetHydraReactorAngle
func GetHydraReactorAngle(vehicle *omp.Vehicle) uint32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetHydraReactorAngle(vehicle.Handle())
}

// GetTrainSpeed wraps CAPI Vehicle_GetTrainSpeed
func GetTrainSpeed(vehicle *omp.Vehicle) float32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetTrainSpeed(vehicle.Handle())
}

// GetMatrix wraps CAPI Vehicle_GetMatrix
func GetMatrix(vehicle *omp.Vehicle, rightX *float32, rightY *float32, rightZ *float32, upX *float32, upY *float32, upZ *float32, atX *float32, atY *float32, atZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Vehicle_GetMatrix(vehicle.Handle(), rightX, rightY, rightZ, upX, upY, upZ, atX, atY, atZ)
}

// GetOccupant wraps CAPI Vehicle_GetOccupant
func GetOccupant(vehicle *omp.Vehicle, seat int32) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Vehicle_GetOccupant(vehicle.Handle(), seat)
	return omp.NewVehicle(res)
}

// CountOccupants wraps CAPI Vehicle_CountOccupants
func CountOccupants(vehicle *omp.Vehicle) int32 {
	c := runtime.Instance().CAPI()
	return c.Vehicle_CountOccupants(vehicle.Handle())
}
