// Code generated by tools/codegen - DO NOT EDIT
package textlabel

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI TextLabel_Create
func Create(text string, color uint32, x float32, y float32, z float32, drawDistance float32, virtualWorld int32, los bool, id *int32) *omp.TextLabel {
	c := runtime.Instance().CAPI()
	res := c.TextLabel_Create(text, color, x, y, z, drawDistance, virtualWorld, los, id)
	return omp.NewTextLabel(res)
}

// Destroy wraps CAPI TextLabel_Destroy
func Destroy(textlabel *omp.TextLabel) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_Destroy(textlabel.Handle())
}

// FromID wraps CAPI TextLabel_FromID
func FromID(textlabelid int32) *omp.TextLabel {
	c := runtime.Instance().CAPI()
	res := c.TextLabel_FromID(textlabelid)
	return omp.NewTextLabel(res)
}

// GetID wraps CAPI TextLabel_GetID
func GetID(textlabel *omp.TextLabel) int32 {
	c := runtime.Instance().CAPI()
	return c.TextLabel_GetID(textlabel.Handle())
}

// AttachToPlayer wraps CAPI TextLabel_AttachToPlayer
func AttachToPlayer(textlabel *omp.TextLabel, player *omp.Player, offsetX float32, offsetY float32, offsetZ float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_AttachToPlayer(textlabel.Handle(), player.Handle(), offsetX, offsetY, offsetZ)
}

// AttachToVehicle wraps CAPI TextLabel_AttachToVehicle
func AttachToVehicle(textlabel *omp.TextLabel, vehicle *omp.Vehicle, offsetX float32, offsetY float32, offsetZ float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_AttachToVehicle(textlabel.Handle(), vehicle.Handle(), offsetX, offsetY, offsetZ)
}

// UpdateText wraps CAPI TextLabel_UpdateText
func UpdateText(textlabel *omp.TextLabel, color uint32, text string) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_UpdateText(textlabel.Handle(), color, text)
}

// IsValid wraps CAPI TextLabel_IsValid
func IsValid(textlabel *omp.TextLabel) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_IsValid(textlabel.Handle())
}

// IsStreamedIn wraps CAPI TextLabel_IsStreamedIn
func IsStreamedIn(player *omp.Player, textlabel *omp.TextLabel) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_IsStreamedIn(player.Handle(), textlabel.Handle())
}

// GetTextString wraps CAPI TextLabel_GetText and returns a string.
func GetTextString(textlabel *omp.TextLabel) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.TextLabel_GetTextString(textlabel.Handle())
}

// GetColor wraps CAPI TextLabel_GetColor
func GetColor(textlabel *omp.TextLabel) uint32 {
	c := runtime.Instance().CAPI()
	return c.TextLabel_GetColor(textlabel.Handle())
}

// GetPos wraps CAPI TextLabel_GetPos
func GetPos(textlabel *omp.TextLabel, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_GetPos(textlabel.Handle(), x, y, z)
}

// SetDrawDistance wraps CAPI TextLabel_SetDrawDistance
func SetDrawDistance(textlabel *omp.TextLabel, distance float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_SetDrawDistance(textlabel.Handle(), distance)
}

// GetDrawDistance wraps CAPI TextLabel_GetDrawDistance
func GetDrawDistance(textlabel *omp.TextLabel) float32 {
	c := runtime.Instance().CAPI()
	return c.TextLabel_GetDrawDistance(textlabel.Handle())
}

// GetLOS wraps CAPI TextLabel_GetLOS
func GetLOS(textlabel *omp.TextLabel) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_GetLOS(textlabel.Handle())
}

// SetLOS wraps CAPI TextLabel_SetLOS
func SetLOS(textlabel *omp.TextLabel, status bool) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_SetLOS(textlabel.Handle(), status)
}

// GetVirtualWorld wraps CAPI TextLabel_GetVirtualWorld
func GetVirtualWorld(textlabel *omp.TextLabel) int32 {
	c := runtime.Instance().CAPI()
	return c.TextLabel_GetVirtualWorld(textlabel.Handle())
}

// SetVirtualWorld wraps CAPI TextLabel_SetVirtualWorld
func SetVirtualWorld(textlabel *omp.TextLabel, world int32) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_SetVirtualWorld(textlabel.Handle(), world)
}

// GetAttachedData wraps CAPI TextLabel_GetAttachedData
func GetAttachedData(textlabel *omp.TextLabel, attachedPlayer *int32, attachedVehicle *int32) bool {
	c := runtime.Instance().CAPI()
	return c.TextLabel_GetAttachedData(textlabel.Handle(), attachedPlayer, attachedVehicle)
}
