// Code generated by tools/codegen - DO NOT EDIT
package playerobject

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI PlayerObject_Create
func Create(player *omp.Player, modelid int32, x float32, y float32, z float32, rotationX float32, rotationY float32, rotationZ float32, drawDistance float32, id *int32) *omp.PlayerObject {
	c := runtime.Instance().CAPI()
	res := c.PlayerObject_Create(player.Handle(), modelid, x, y, z, rotationX, rotationY, rotationZ, drawDistance, id)
	return omp.NewPlayerObject(res)
}

// Destroy wraps CAPI PlayerObject_Destroy
func Destroy(player *omp.Player, object *omp.PlayerObject) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_Destroy(player.Handle(), object.Handle())
}

// FromID wraps CAPI PlayerObject_FromID
func FromID(player *omp.Player, objectid int32) *omp.PlayerObject {
	c := runtime.Instance().CAPI()
	res := c.PlayerObject_FromID(player.Handle(), objectid)
	return omp.NewPlayerObject(res)
}

// GetID wraps CAPI PlayerObject_GetID
func GetID(player *omp.Player, object *omp.PlayerObject) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetID(player.Handle(), object.Handle())
}

// AttachToVehicle wraps CAPI PlayerObject_AttachToVehicle
func AttachToVehicle(player *omp.Player, object *omp.PlayerObject, vehicle *omp.Vehicle, offsetX float32, offsetY float32, offsetZ float32, rotationX float32, rotationY float32, rotationZ float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_AttachToVehicle(player.Handle(), object.Handle(), vehicle.Handle(), offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ)
}

// AttachToPlayer wraps CAPI PlayerObject_AttachToPlayer
func AttachToPlayer(player *omp.Player, object *omp.PlayerObject, playerAttachedTo *omp.Player, offsetX float32, offsetY float32, offsetZ float32, rotationX float32, rotationY float32, rotationZ float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_AttachToPlayer(player.Handle(), object.Handle(), playerAttachedTo.Handle(), offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ)
}

// AttachToObject wraps CAPI PlayerObject_AttachToObject
func AttachToObject(player *omp.Player, object *omp.PlayerObject, attachedTo *omp.PlayerObject, offsetX float32, offsetY float32, offsetZ float32, rotationX float32, rotationY float32, rotationZ float32, syncRotation bool) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_AttachToObject(player.Handle(), object.Handle(), attachedTo.Handle(), offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ, syncRotation)
}

// SetPos wraps CAPI PlayerObject_SetPos
func SetPos(player *omp.Player, object *omp.PlayerObject, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_SetPos(player.Handle(), object.Handle(), x, y, z)
}

// GetPos wraps CAPI PlayerObject_GetPos
func GetPos(player *omp.Player, object *omp.PlayerObject, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetPos(player.Handle(), object.Handle(), x, y, z)
}

// SetRot wraps CAPI PlayerObject_SetRot
func SetRot(player *omp.Player, object *omp.PlayerObject, rotationX float32, rotationY float32, rotationZ float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_SetRot(player.Handle(), object.Handle(), rotationX, rotationY, rotationZ)
}

// GetRot wraps CAPI PlayerObject_GetRot
func GetRot(player *omp.Player, object *omp.PlayerObject, rotationX *float32, rotationY *float32, rotationZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetRot(player.Handle(), object.Handle(), rotationX, rotationY, rotationZ)
}

// GetModel wraps CAPI PlayerObject_GetModel
func GetModel(player *omp.Player, object *omp.PlayerObject) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetModel(player.Handle(), object.Handle())
}

// SetNoCameraCollision wraps CAPI PlayerObject_SetNoCameraCollision
func SetNoCameraCollision(player *omp.Player, object *omp.PlayerObject) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_SetNoCameraCollision(player.Handle(), object.Handle())
}

// IsValid wraps CAPI PlayerObject_IsValid
func IsValid(player *omp.Player, object *omp.PlayerObject) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_IsValid(player.Handle(), object.Handle())
}

// Move wraps CAPI PlayerObject_Move
func Move(player *omp.Player, object *omp.PlayerObject, x float32, y float32, z float32, speed float32, rotationX float32, rotationY float32, rotationZ float32) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_Move(player.Handle(), object.Handle(), x, y, z, speed, rotationX, rotationY, rotationZ)
}

// Stop wraps CAPI PlayerObject_Stop
func Stop(player *omp.Player, object *omp.PlayerObject) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_Stop(player.Handle(), object.Handle())
}

// IsMoving wraps CAPI PlayerObject_IsMoving
func IsMoving(player *omp.Player, object *omp.PlayerObject) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_IsMoving(player.Handle(), object.Handle())
}

// BeginEditing wraps CAPI PlayerObject_BeginEditing
func BeginEditing(player *omp.Player, object *omp.PlayerObject) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_BeginEditing(player.Handle(), object.Handle())
}

// SetMaterial wraps CAPI PlayerObject_SetMaterial
func SetMaterial(player *omp.Player, object *omp.PlayerObject, materialIndex int32, modelID int32, textureLibrary string, textureName string, materialColor uint32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_SetMaterial(player.Handle(), object.Handle(), materialIndex, modelID, textureLibrary, textureName, materialColor)
}

// SetMaterialText wraps CAPI PlayerObject_SetMaterialText
func SetMaterialText(player *omp.Player, object *omp.PlayerObject, text string, materialIndex int32, materialSize int32, fontface string, fontsize int32, bold bool, fontColor uint32, backgroundColor uint32, textalignment int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_SetMaterialText(player.Handle(), object.Handle(), text, materialIndex, materialSize, fontface, fontsize, bold, fontColor, backgroundColor, textalignment)
}

// GetDrawDistance wraps CAPI PlayerObject_GetDrawDistance
func GetDrawDistance(player *omp.Player, object *omp.PlayerObject) float32 {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetDrawDistance(player.Handle(), object.Handle())
}

// GetMoveSpeed wraps CAPI PlayerObject_GetMoveSpeed
func GetMoveSpeed(player *omp.Player, object *omp.PlayerObject) float32 {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetMoveSpeed(player.Handle(), object.Handle())
}

// GetMovingTargetPos wraps CAPI PlayerObject_GetMovingTargetPos
func GetMovingTargetPos(player *omp.Player, object *omp.PlayerObject, targetX *float32, targetY *float32, targetZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetMovingTargetPos(player.Handle(), object.Handle(), targetX, targetY, targetZ)
}

// GetMovingTargetRot wraps CAPI PlayerObject_GetMovingTargetRot
func GetMovingTargetRot(player *omp.Player, object *omp.PlayerObject, rotationX *float32, rotationY *float32, rotationZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetMovingTargetRot(player.Handle(), object.Handle(), rotationX, rotationY, rotationZ)
}

// GetAttachedData wraps CAPI PlayerObject_GetAttachedData
func GetAttachedData(player *omp.Player, object *omp.PlayerObject, parentVehicle *int32, parentObject *int32, parentPlayer *int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetAttachedData(player.Handle(), object.Handle(), parentVehicle, parentObject, parentPlayer)
}

// GetAttachedOffset wraps CAPI PlayerObject_GetAttachedOffset
func GetAttachedOffset(player *omp.Player, object *omp.PlayerObject, offsetX *float32, offsetY *float32, offsetZ *float32, rotationX *float32, rotationY *float32, rotationZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetAttachedOffset(player.Handle(), object.Handle(), offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ)
}

// GetSyncRotation wraps CAPI PlayerObject_GetSyncRotation
func GetSyncRotation(player *omp.Player, object *omp.PlayerObject) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_GetSyncRotation(player.Handle(), object.Handle())
}

// IsMaterialSlotUsed wraps CAPI PlayerObject_IsMaterialSlotUsed
func IsMaterialSlotUsed(player *omp.Player, object *omp.PlayerObject, materialIndex int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_IsMaterialSlotUsed(player.Handle(), object.Handle(), materialIndex)
}

// GetMaterial wraps CAPI PlayerObject_GetMaterial
func GetMaterial(player *omp.Player, object *omp.PlayerObject, materialIndex int32, modelid *int32, textureLibrary *string, textureName *string, materialColor *int32) bool {
	c := runtime.Instance().CAPI()
	var textureLibraryView runtime.CAPIStringView
	var textureNameView runtime.CAPIStringView
	res := c.PlayerObject_GetMaterial(player.Handle(), object.Handle(), materialIndex, modelid, &textureLibraryView, &textureNameView, materialColor)
	if textureLibrary != nil {
		*textureLibrary = runtime.CAPIStringViewToString(&textureLibraryView)
	}
	if textureName != nil {
		*textureName = runtime.CAPIStringViewToString(&textureNameView)
	}
	return res
}

// GetMaterialText wraps CAPI PlayerObject_GetMaterialText
func GetMaterialText(player *omp.Player, object *omp.PlayerObject, materialIndex int32, text *string, materialSize *int32, fontFace *string, fontSize *int32, bold *bool, fontColor *int32, backgroundColor *int32, textAlignment *int32) bool {
	c := runtime.Instance().CAPI()
	var textView runtime.CAPIStringView
	var fontFaceView runtime.CAPIStringView
	res := c.PlayerObject_GetMaterialText(player.Handle(), object.Handle(), materialIndex, &textView, materialSize, &fontFaceView, fontSize, bold, fontColor, backgroundColor, textAlignment)
	if text != nil {
		*text = runtime.CAPIStringViewToString(&textView)
	}
	if fontFace != nil {
		*fontFace = runtime.CAPIStringViewToString(&fontFaceView)
	}
	return res
}

// IsNoCameraCollision wraps CAPI PlayerObject_IsNoCameraCollision
func IsNoCameraCollision(player *omp.Player, object *omp.PlayerObject) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerObject_IsNoCameraCollision(player.Handle(), object.Handle())
}
