// Code generated by tools/codegen - DO NOT EDIT
package omp

// maintenance: We will update this file when upstream constants change.
// source: Manually sourced from https://github.com/openmultiplayer/omp-stdlib.

// Reasons a player disconnected.
type DisconnectReason int

const (
	DisconnectReasonTimeout DisconnectReason = 0
	DisconnectReasonQuit    DisconnectReason = 1
	DisconnectReasonKicked  DisconnectReason = 2
)

// Weapon identifiers.
type WeaponID int

const (
	WeaponFist               WeaponID = 0
	WeaponBrassKnuckles      WeaponID = 1
	WeaponGolfClub           WeaponID = 2
	WeaponNitestick          WeaponID = 3
	WeaponKnife              WeaponID = 4
	WeaponBat                WeaponID = 5
	WeaponShovel             WeaponID = 6
	WeaponPoolStick          WeaponID = 7
	WeaponKatana             WeaponID = 8
	WeaponChainsaw           WeaponID = 9
	WeaponDildo              WeaponID = 10
	WeaponDildo2             WeaponID = 11
	WeaponVibrator           WeaponID = 12
	WeaponVibrator2          WeaponID = 13
	WeaponFlowers            WeaponID = 14
	WeaponCane               WeaponID = 15
	WeaponGrenade            WeaponID = 16
	WeaponTeargas            WeaponID = 17
	WeaponMolotov            WeaponID = 18
	WeaponColt45             WeaponID = 22
	WeaponSilenced           WeaponID = 23
	WeaponDeagle             WeaponID = 24
	WeaponShotgun            WeaponID = 25
	WeaponSawedoff           WeaponID = 26
	WeaponCombatShotgun      WeaponID = 27
	WeaponUzi                WeaponID = 28
	WeaponMP5                WeaponID = 29
	WeaponAK47               WeaponID = 30
	WeaponM4                 WeaponID = 31
	WeaponTec9               WeaponID = 32
	WeaponRifle              WeaponID = 33
	WeaponSniper             WeaponID = 34
	WeaponRPG                WeaponID = 35
	WeaponHeatseeker         WeaponID = 36
	WeaponFlamethrower       WeaponID = 37
	WeaponMinigun            WeaponID = 38
	WeaponSatchel            WeaponID = 39
	WeaponBomb               WeaponID = 40
	WeaponSpraycan           WeaponID = 41
	WeaponFireExtinguisher   WeaponID = 42
	WeaponCamera             WeaponID = 43
	WeaponNightVisionGoggles WeaponID = 44
	WeaponThermalGoggles     WeaponID = 45
	WeaponParachute          WeaponID = 46
	WeaponVehicle            WeaponID = 49
	WeaponDrown              WeaponID = 53
	WeaponCollision          WeaponID = 54
)

// Bitmask values for player key states.
const (
	KeyNone            = 0
	KeyAction          = 1
	KeyCrouch          = 2
	KeyFire            = 4
	KeySprint          = 8
	KeySecondaryAttack = 16
	KeyJump            = 32
	KeyLookRight       = 64
	KeyHandbrake       = 128
	KeyAim             = 128
	KeyLookLeft        = 256
	KeySubmission      = 512
	KeyLookBehind      = 512
	KeyWalk            = 1024
	KeyAnalogUp        = 2048
	KeyAnalogDown      = 4096
	KeyAnalogLeft      = 8192
	KeyAnalogRight     = 16384
	KeyYes             = 65536
	KeyNo              = 131072
	KeyCtrlBack        = 262144
)

// Weapon slot identifiers.
type WeaponSlot int

const (
	WeaponSlotUnknown      WeaponSlot = -1
	WeaponSlotUnarmed      WeaponSlot = 0
	WeaponSlotMelee        WeaponSlot = 1
	WeaponSlotPistol       WeaponSlot = 2
	WeaponSlotShotgun      WeaponSlot = 3
	WeaponSlotMachineGun   WeaponSlot = 4
	WeaponSlotAssaultRifle WeaponSlot = 5
	WeaponSlotLongRifle    WeaponSlot = 6
	WeaponSlotArtillery    WeaponSlot = 7
	WeaponSlotExplosives   WeaponSlot = 8
	WeaponSlotEquipment    WeaponSlot = 9
	WeaponSlotGift         WeaponSlot = 10
	WeaponSlotGadget       WeaponSlot = 11
	WeaponSlotDetonator    WeaponSlot = 12
)

// Player state identifiers.
type PlayerState int

const (
	PlayerStateUnknown    PlayerState = -1
	PlayerStateNone       PlayerState = 0
	PlayerStateOnFoot     PlayerState = 1
	PlayerStateDriver     PlayerState = 2
	PlayerStatePassenger  PlayerState = 3
	PlayerStateWasted     PlayerState = 7
	PlayerStateSpawned    PlayerState = 8
	PlayerStateSpectating PlayerState = 9
)

// Special action identifiers.
type SpecialAction int

const (
	SpecialActionUnknown          SpecialAction = -1
	SpecialActionNone             SpecialAction = 0
	SpecialActionDuck             SpecialAction = 1
	SpecialActionUseJetpack       SpecialAction = 2
	SpecialActionEnterVehicle     SpecialAction = 3
	SpecialActionExitVehicle      SpecialAction = 4
	SpecialActionDance1           SpecialAction = 5
	SpecialActionDance2           SpecialAction = 6
	SpecialActionDance3           SpecialAction = 7
	SpecialActionDance4           SpecialAction = 8
	SpecialActionHandsUp          SpecialAction = 10
	SpecialActionUseCellphone     SpecialAction = 11
	SpecialActionSitting          SpecialAction = 12
	SpecialActionStopUseCellphone SpecialAction = 13
	SpecialActionDrinkBeer        SpecialAction = 20
	SpecialActionSmokeCiggy       SpecialAction = 21
	SpecialActionDrinkWine        SpecialAction = 22
	SpecialActionDrinkSprunk      SpecialAction = 23
	SpecialActionCuffed           SpecialAction = 24
	SpecialActionCarry            SpecialAction = 25
	SpecialActionPissing          SpecialAction = 68
)

// Hand-to-hand fight styles.
type FightStyle int

const (
	FightStyleUnknown  FightStyle = -1
	FightStyleNormal   FightStyle = 4
	FightStyleBoxing   FightStyle = 5
	FightStyleKungFu   FightStyle = 6
	FightStyleKneehead FightStyle = 7
	FightStyleGrabkick FightStyle = 15
	FightStyleElbow    FightStyle = 16
)

// Weapon skill identifiers.
type WeaponSkill int

const (
	WeaponSkillUnknown        WeaponSkill = -1
	WeaponSkillPistol         WeaponSkill = 0
	WeaponSkillPistolSilenced WeaponSkill = 1
	WeaponSkillDesertEagle    WeaponSkill = 2
	WeaponSkillShotgun        WeaponSkill = 3
	WeaponSkillSawnoffShotgun WeaponSkill = 4
	WeaponSkillSpas12Shotgun  WeaponSkill = 5
	WeaponSkillMicroUzi       WeaponSkill = 6
	WeaponSkillMP5            WeaponSkill = 7
	WeaponSkillAK47           WeaponSkill = 8
	WeaponSkillM4             WeaponSkill = 9
	WeaponSkillSniperRifle    WeaponSkill = 10
)

// Weapon state identifiers.
type WeaponState int

const (
	WeaponStateUnknown     WeaponState = -1
	WeaponStateNoBullets   WeaponState = 0
	WeaponStateLastBullet  WeaponState = 1
	WeaponStateMoreBullets WeaponState = 2
	WeaponStateReloading   WeaponState = 3
)

// Camera move types.
type CameraMoveType int

const (
	CameraMoveUnknown CameraMoveType = -1
	CameraMove        CameraMoveType = 1
	CameraCut         CameraMoveType = 2
)

// Camera mode identifiers.
type CameraMode int

const (
	CameraModeDisconnected     CameraMode = -1
	CameraModeNone             CameraMode = 0
	CameraModeBehindCar        CameraMode = 3
	CameraModeFollowPed        CameraMode = 4
	CameraModeSniper           CameraMode = 7
	CameraModeRocketLauncher   CameraMode = 8
	CameraModeFixed            CameraMode = 15
	CameraModeFirstPerson      CameraMode = 16
	CameraModeCamOnAString     CameraMode = 18
	CameraModeBehindBoat       CameraMode = 22
	CameraModeCamera           CameraMode = 46
	CameraModeRocketLauncherHS CameraMode = 51
	CameraModeAimWeapon        CameraMode = 53
	CameraModeAimWeaponFromCar CameraMode = 55
	CameraModeDwHeliChase      CameraMode = 56
)

// Map icon display styles.
type MapIconStyle int

const (
	MapIconStyleUnknown     MapIconStyle = -1
	MapIconLocal            MapIconStyle = 0
	MapIconGlobal           MapIconStyle = 1
	MapIconLocalCheckpoint  MapIconStyle = 2
	MapIconGlobalCheckpoint MapIconStyle = 3
)

// Player marker display modes.
type PlayerMarkersMode int

const (
	PlayerMarkersModeUnknown  PlayerMarkersMode = -1
	PlayerMarkersModeOff      PlayerMarkersMode = 0
	PlayerMarkersModeGlobal   PlayerMarkersMode = 1
	PlayerMarkersModeStreamed PlayerMarkersMode = 2
)

// Spectate mode identifiers.
type SpectateMode int

const (
	SpectateModeUnknown SpectateMode = -1
	SpectateModeNormal  SpectateMode = 1
	SpectateModeFixed   SpectateMode = 2
	SpectateModeSide    SpectateMode = 3
)

// Player recording types for NPC playback.
type PlayerRecordingType int

const (
	PlayerRecordingTypeUnknown PlayerRecordingType = -1
	PlayerRecordingTypeNone    PlayerRecordingType = 0
	PlayerRecordingTypeDriver  PlayerRecordingType = 1
	PlayerRecordingTypeOnFoot  PlayerRecordingType = 2
)

// NPC movement types.
type NPCMoveType int

const (
	NPCMoveTypeUnknown NPCMoveType = -1
	NPCMoveTypeNone    NPCMoveType = 0
	NPCMoveTypeWalk    NPCMoveType = 1
	NPCMoveTypeJog     NPCMoveType = 2
	NPCMoveTypeSprint  NPCMoveType = 3
	NPCMoveTypeDrive   NPCMoveType = 4
	NPCMoveTypeAuto    NPCMoveType = 5
)

// NPC entity check flags.
const (
	NPCEntityCheckNone        = 0
	NPCEntityCheckPlayer      = 1
	NPCEntityCheckNPC         = 2
	NPCEntityCheckActor       = 4
	NPCEntityCheckVehicle     = 8
	NPCEntityCheckObject      = 16
	NPCEntityCheckPObjectOrig = 32
	NPCEntityCheckPObjectTarg = 64
	NPCEntityCheckMap         = 128
	NPCEntityCheckAll         = 255
)

// Forced sync targets for animations.
type ForceSync int

const (
	ForceSyncUnknown ForceSync = -1
	ForceSyncNone    ForceSync = 0
	ForceSyncAll     ForceSync = 1
	ForceSyncOther   ForceSync = 2
)

// Sources for click callbacks.
type ClickSource int

const (
	ClickSourceUnknown    ClickSource = -1
	ClickSourceScoreboard ClickSource = 0
)

// Bullet hit types for OnPlayerWeaponShot.
type BulletHitType int

const (
	BulletHitTypeUnknown      BulletHitType = -1
	BulletHitTypeNone         BulletHitType = 0
	BulletHitTypePlayer       BulletHitType = 1
	BulletHitTypeVehicle      BulletHitType = 2
	BulletHitTypeObject       BulletHitType = 3
	BulletHitTypePlayerObject BulletHitType = 4
)

// Checkpoint and race checkpoint marker types.
type CheckpointType int

const (
	CheckpointTypeUnknown      CheckpointType = -1
	CheckpointTypeGroundNormal CheckpointType = 0
	CheckpointTypeGroundFinish CheckpointType = 1
	CheckpointTypeGroundEmpty  CheckpointType = 2
	CheckpointTypeAirNormal    CheckpointType = 3
	CheckpointTypeAirFinish    CheckpointType = 4
	CheckpointTypeAirRotating  CheckpointType = 5
	CheckpointTypeAirStrobing  CheckpointType = 6
	CheckpointTypeAirSwinging  CheckpointType = 7
	CheckpointTypeAirBobbing   CheckpointType = 8
)

// Dialog style identifiers.
type DialogStyle int

const (
	DialogStyleUnknown        DialogStyle = -1
	DialogStyleMsgBox         DialogStyle = 0
	DialogStyleInput          DialogStyle = 1
	DialogStyleList           DialogStyle = 2
	DialogStylePassword       DialogStyle = 3
	DialogStyleTablist        DialogStyle = 4
	DialogStyleTablistHeaders DialogStyle = 5
)

// Text draw font identifiers.
type TextDrawFont int

const (
	TextDrawFontUnknown        TextDrawFont = -1
	TextDrawFont0              TextDrawFont = 0
	TextDrawFont1              TextDrawFont = 1
	TextDrawFont2              TextDrawFont = 2
	TextDrawFont3              TextDrawFont = 3
	TextDrawFontSpriteDraw     TextDrawFont = 4
	TextDrawFontModelPreview   TextDrawFont = 5
	TextDrawFontBank           TextDrawFont = 0
	TextDrawFontStandard       TextDrawFont = 1
	TextDrawFontSpaceage       TextDrawFont = 2
	TextDrawFontHeading        TextDrawFont = 3
	TextDrawFontBeckettRegular TextDrawFont = 0
	TextDrawFontAharoniBold    TextDrawFont = 1
	TextDrawFontBankGothic     TextDrawFont = 2
	TextDrawFontPricedown      TextDrawFont = 3
	TextDrawFontSprite         TextDrawFont = 4
	TextDrawFontPreview        TextDrawFont = 5
)

// Text draw alignment identifiers.
type TextDrawAlign int

const (
	TextDrawAlignUnknown TextDrawAlign = -1
	TextDrawAlignLeft    TextDrawAlign = 1
	TextDrawAlignCentre  TextDrawAlign = 2
	TextDrawAlignCenter  TextDrawAlign = 2
	TextDrawAlignRight   TextDrawAlign = 3
)

// Object selection types.
type SelectObjectType int

const (
	SelectObjectUnknown      SelectObjectType = -1
	SelectObjectGlobalObject SelectObjectType = 1
	SelectObjectPlayerObject SelectObjectType = 2
)

// Object material texture sizes.
type ObjectMaterialSize int

const (
	ObjectMaterialSizeUnknown ObjectMaterialSize = -1
	ObjectMaterialSize32x32   ObjectMaterialSize = 10
	ObjectMaterialSize64x32   ObjectMaterialSize = 20
	ObjectMaterialSize64x64   ObjectMaterialSize = 30
	ObjectMaterialSize128x32  ObjectMaterialSize = 40
	ObjectMaterialSize128x64  ObjectMaterialSize = 50
	ObjectMaterialSize128x128 ObjectMaterialSize = 60
	ObjectMaterialSize256x32  ObjectMaterialSize = 70
	ObjectMaterialSize256x64  ObjectMaterialSize = 80
	ObjectMaterialSize256x128 ObjectMaterialSize = 90
	ObjectMaterialSize256x256 ObjectMaterialSize = 100
	ObjectMaterialSize512x64  ObjectMaterialSize = 110
	ObjectMaterialSize512x128 ObjectMaterialSize = 120
	ObjectMaterialSize512x256 ObjectMaterialSize = 130
	ObjectMaterialSize512x512 ObjectMaterialSize = 140
)

// Object material text alignment identifiers.
type ObjectMaterialTextAlign int

const (
	ObjectMaterialTextAlignUnknown ObjectMaterialTextAlign = -1
	ObjectMaterialTextAlignLeft    ObjectMaterialTextAlign = 0
	ObjectMaterialTextAlignCentre  ObjectMaterialTextAlign = 1
	ObjectMaterialTextAlignCenter  ObjectMaterialTextAlign = 1
	ObjectMaterialTextAlignRight   ObjectMaterialTextAlign = 2
)

// Object edit response identifiers.
type EditResponse int

const (
	EditResponseUnknown EditResponse = -1
	EditResponseCancel  EditResponse = 0
	EditResponseFinal   EditResponse = 1
	EditResponseUpdate  EditResponse = 2
)

// Vehicle mod slot identifiers.
type CarModType int

const (
	CarModTypeNone         CarModType = -1
	CarModTypeSpoiler      CarModType = 0
	CarModTypeHood         CarModType = 1
	CarModTypeRoof         CarModType = 2
	CarModTypeSideskirt    CarModType = 3
	CarModTypeLamps        CarModType = 4
	CarModTypeNitro        CarModType = 5
	CarModTypeExhaust      CarModType = 6
	CarModTypeWheels       CarModType = 7
	CarModTypeStereo       CarModType = 8
	CarModTypeHydraulics   CarModType = 9
	CarModTypeFrontBumper  CarModType = 10
	CarModTypeRearBumper   CarModType = 11
	CarModTypeVentRight    CarModType = 12
	CarModTypeVentLeft     CarModType = 13
	CarModTypeFrontBullbar CarModType = 14
	CarModTypeRearBullbar  CarModType = 15
)

// Vehicle model info identifiers.
type VehicleModelInfo int

const (
	VehicleModelInfoUnknown     VehicleModelInfo = -1
	VehicleModelInfoSize        VehicleModelInfo = 1
	VehicleModelInfoFrontSeat   VehicleModelInfo = 2
	VehicleModelInfoRearSeat    VehicleModelInfo = 3
	VehicleModelInfoPetrolCap   VehicleModelInfo = 4
	VehicleModelInfoWheelsFront VehicleModelInfo = 5
	VehicleModelInfoWheelsRear  VehicleModelInfo = 6
	VehicleModelInfoWheelsMid   VehicleModelInfo = 7
	VehicleModelInfoFrontBumper VehicleModelInfo = 8
	VehicleModelInfoRearBumper  VehicleModelInfo = 9
)

// Vehicle panel damage status values.
type VehiclePanelStatus int

const (
	VehiclePanelStatusUnknown VehiclePanelStatus = -1
	VehiclePanelStatusNone    VehiclePanelStatus = 0
)

// Vehicle door damage status flags.
const (
	VehicleDoorStatusNone              = 0
	VehicleDoorStatusBonnetOpen        = 1
	VehicleDoorStatusBonnetDamaged     = 2
	VehicleDoorStatusBonnetMissing     = 4
	VehicleDoorStatusBootOpen          = 256
	VehicleDoorStatusBootDamaged       = 512
	VehicleDoorStatusBootMissing       = 1024
	VehicleDoorStatusFrontLeftOpen     = 65536
	VehicleDoorStatusFrontLeftDamaged  = 131072
	VehicleDoorStatusFrontLeftMissing  = 262144
	VehicleDoorStatusFrontRightOpen    = 16777216
	VehicleDoorStatusFrontRightDamaged = 33554432
	VehicleDoorStatusFrontRightMissing = 67108864
)

// Vehicle light damage status flags.
const (
	VehicleLightStatusNone             = 0
	VehicleLightStatusFrontLeftBroken  = 1
	VehicleLightStatusFrontRightBroken = 4
	VehicleLightStatusRearBroken       = 64
)

// Vehicle tyre damage status flags.
const (
	VehicleTyreStatusNone             = 0
	VehicleTyreStatusFrontLeftPopped  = 8
	VehicleTyreStatusFrontRightPopped = 2
	VehicleTyreStatusRearLeftPopped   = 4
	VehicleTyreStatusRearRightPopped  = 1
)

// Aircraft landing gear states.
type LandingGearState int

const (
	LandingGearStateDown LandingGearState = 0
	LandingGearStateUp   LandingGearState = 1
)

// Vehicle parameter state values.
type VehicleParam int

const (
	VehicleParamUnset VehicleParam = -1
	VehicleParamOff   VehicleParam = 0
	VehicleParamOn    VehicleParam = 1
)

// Network connection status values.
type ConnectionStatus int

const (
	ConnectionStatusUnknown                             ConnectionStatus = -1
	ConnectionStatusNoAction                            ConnectionStatus = 0
	ConnectionStatusDisconnectASAP                      ConnectionStatus = 1
	ConnectionStatusDisconnectASAPSilently              ConnectionStatus = 2
	ConnectionStatusDisconnectOnNoAck                   ConnectionStatus = 3
	ConnectionStatusRequestedConnection                 ConnectionStatus = 4
	ConnectionStatusHandlingConnectionRequest           ConnectionStatus = 5
	ConnectionStatusUnverifiedSender                    ConnectionStatus = 6
	ConnectionStatusSetEncryptionOnMultiple16BytePacket ConnectionStatus = 7
	ConnectionStatusConnected                           ConnectionStatus = 8
)

// Download request types.
type DownloadRequest int

const (
	DownloadRequestUnknown     DownloadRequest = -1
	DownloadRequestEmpty       DownloadRequest = 0
	DownloadRequestModelFile   DownloadRequest = 1
	DownloadRequestTextureFile DownloadRequest = 2
)

// HTTP request methods.
type HttpMethod int

const (
	HttpMethodUnknown HttpMethod = -1
	HttpGet           HttpMethod = 1
	HttpPost          HttpMethod = 2
	HttpHead          HttpMethod = 3
)

// HTTP error response codes.
type HttpError int

const (
	HttpErrorUnknown           HttpError = -1
	HttpErrorBadHost           HttpError = 1
	HttpErrorNoSocket          HttpError = 2
	HttpErrorCantConnect       HttpError = 3
	HttpErrorCantWrite         HttpError = 4
	HttpErrorContentTooBig     HttpError = 5
	HttpErrorMalformedResponse HttpError = 6
)

// Server/player variable types.
type VarType int

const (
	VarTypeUnknown VarType = -1
	VarTypeNone    VarType = 0
	VarTypeInt     VarType = 1
	VarTypeString  VarType = 2
	VarTypeFloat   VarType = 3
)
