// Code generated by tools/codegen - DO NOT EDIT
package omp

// PlayerGiveDamageActorEvent is emitted when onPlayerGiveDamageActor
type PlayerGiveDamageActorEvent struct {
	Player *Player `json:"player"`
	Actor  *Actor  `json:"actor"`
	Amount float32 `json:"amount"`
	Weapon int32   `json:"weapon"`
	Part   int32   `json:"part"`
}

// ActorStreamInEvent is emitted when onActorStreamIn
type ActorStreamInEvent struct {
	Actor     *Actor  `json:"actor"`
	ForPlayer *Player `json:"forplayer"`
}

// ActorStreamOutEvent is emitted when onActorStreamOut
type ActorStreamOutEvent struct {
	Actor     *Actor  `json:"actor"`
	ForPlayer *Player `json:"forplayer"`
}

// PlayerEnterCheckpointEvent is emitted when onPlayerEnterCheckpoint
type PlayerEnterCheckpointEvent struct {
	Player *Player `json:"player"`
}

// PlayerLeaveCheckpointEvent is emitted when onPlayerLeaveCheckpoint
type PlayerLeaveCheckpointEvent struct {
	Player *Player `json:"player"`
}

// PlayerEnterRaceCheckpointEvent is emitted when onPlayerEnterRaceCheckpoint
type PlayerEnterRaceCheckpointEvent struct {
	Player *Player `json:"player"`
}

// PlayerLeaveRaceCheckpointEvent is emitted when onPlayerLeaveRaceCheckpoint
type PlayerLeaveRaceCheckpointEvent struct {
	Player *Player `json:"player"`
}

// PlayerRequestClassEvent is emitted when onPlayerRequestClass
type PlayerRequestClassEvent struct {
	Player  *Player `json:"player"`
	ClassID int32   `json:"classid"`
}

// ConsoleTextEvent is emitted when onConsoleText
type ConsoleTextEvent struct {
	Command    BorrowedStringView `json:"command"`
	Parameters BorrowedStringView `json:"parameters"`
}

// RconLoginAttemptEvent is emitted when onRconLoginAttempt
type RconLoginAttemptEvent struct {
	Address  BorrowedStringView `json:"address"`
	Password BorrowedStringView `json:"password"`
	Success  bool               `json:"success"`
}

// TickEvent is emitted when onTick
type TickEvent struct {
	Elapsed int32 `json:"elapsed"`
}

// PlayerFinishedDownloadingEvent is emitted when onPlayerFinishedDownloading
type PlayerFinishedDownloadingEvent struct {
	Player *Player `json:"player"`
	VW     int32   `json:"vw"`
}

// PlayerRequestDownloadEvent is emitted when onPlayerRequestDownload
type PlayerRequestDownloadEvent struct {
	Player   *Player `json:"player"`
	Typ      int32   `json:"type"`
	Checksum int32   `json:"checksum"`
}

// DialogResponseEvent is emitted when onDialogResponse
type DialogResponseEvent struct {
	Player    *Player            `json:"player"`
	DialogID  int32              `json:"dialogid"`
	Response  int32              `json:"response"`
	ListItem  int32              `json:"listitem"`
	InputText BorrowedStringView `json:"inputtext"`
}

// PlayerEnterGangZoneEvent is emitted when onPlayerEnterGangZone
type PlayerEnterGangZoneEvent struct {
	Player *Player   `json:"player"`
	Zone   *GangZone `json:"zone"`
}

// PlayerLeaveGangZoneEvent is emitted when onPlayerLeaveGangZone
type PlayerLeaveGangZoneEvent struct {
	Player *Player   `json:"player"`
	Zone   *GangZone `json:"zone"`
}

// PlayerClickGangZoneEvent is emitted when onPlayerClickGangZone
type PlayerClickGangZoneEvent struct {
	Player *Player   `json:"player"`
	Zone   *GangZone `json:"zone"`
}

// PlayerSelectedMenuRowEvent is emitted when onPlayerSelectedMenuRow
type PlayerSelectedMenuRowEvent struct {
	Player *Player `json:"player"`
	Row    int32   `json:"row"`
}

// PlayerExitedMenuEvent is emitted when onPlayerExitedMenu
type PlayerExitedMenuEvent struct {
	Player *Player `json:"player"`
}

// NPCFinishMoveEvent is emitted when onNPCFinishMove
type NPCFinishMoveEvent struct {
	NPC *NPC `json:"npc"`
}

// NPCCreateEvent is emitted when onNPCCreate
type NPCCreateEvent struct {
	NPC *NPC `json:"npc"`
}

// NPCDestroyEvent is emitted when onNPCDestroy
type NPCDestroyEvent struct {
	NPC *NPC `json:"npc"`
}

// NPCWeaponStateChangeEvent is emitted when onNPCWeaponStateChange
type NPCWeaponStateChangeEvent struct {
	NPC      *NPC  `json:"npc"`
	NewState int32 `json:"newstate"`
	OldState int32 `json:"oldstate"`
}

// NPCTakeDamageEvent is emitted when onNPCTakeDamage
type NPCTakeDamageEvent struct {
	NPC      *NPC    `json:"npc"`
	Damager  *Player `json:"damager"`
	Damage   float32 `json:"damage"`
	Weapon   int32   `json:"weapon"`
	BodyPart int32   `json:"bodypart"`
}

// NPCGiveDamageEvent is emitted when onNPCGiveDamage
type NPCGiveDamageEvent struct {
	NPC      *NPC    `json:"npc"`
	Damaged  *Player `json:"damaged"`
	Damage   float32 `json:"damage"`
	Weapon   int32   `json:"weapon"`
	BodyPart int32   `json:"bodypart"`
}

// NPCDeathEvent is emitted when onNPCDeath
type NPCDeathEvent struct {
	NPC    *NPC    `json:"npc"`
	Killer *Player `json:"killer"`
	Reason int32   `json:"reason"`
}

// NPCSpawnEvent is emitted when onNPCSpawn
type NPCSpawnEvent struct {
	NPC *NPC `json:"npc"`
}

// NPCRespawnEvent is emitted when onNPCRespawn
type NPCRespawnEvent struct {
	NPC *NPC `json:"npc"`
}

// NPCPlaybackStartEvent is emitted when onNPCPlaybackStart
type NPCPlaybackStartEvent struct {
	NPC      *NPC  `json:"npc"`
	RecordID int32 `json:"recordid"`
}

// NPCPlaybackEndEvent is emitted when onNPCPlaybackEnd
type NPCPlaybackEndEvent struct {
	NPC      *NPC  `json:"npc"`
	RecordID int32 `json:"recordid"`
}

// NPCShotMissedEvent is emitted when onNPCShotMissed
type NPCShotMissedEvent struct {
	NPC     *NPC    `json:"npc"`
	Weapon  int32   `json:"weapon"`
	OffsetX float32 `json:"offsetx"`
	OffsetY float32 `json:"offsety"`
	OffsetZ float32 `json:"offsetz"`
}

// NPCShotPlayerEvent is emitted when onNPCShotPlayer
type NPCShotPlayerEvent struct {
	NPC     *NPC    `json:"npc"`
	Player  *Player `json:"player"`
	Weapon  int32   `json:"weapon"`
	OffsetX float32 `json:"offsetx"`
	OffsetY float32 `json:"offsety"`
	OffsetZ float32 `json:"offsetz"`
}

// NPCShotNPCEvent is emitted when onNPCShotNPC
type NPCShotNPCEvent struct {
	NPC       *NPC    `json:"npc"`
	NpcTarget *NPC    `json:"npctarget"`
	Weapon    int32   `json:"weapon"`
	OffsetX   float32 `json:"offsetx"`
	OffsetY   float32 `json:"offsety"`
	OffsetZ   float32 `json:"offsetz"`
}

// NPCShotVehicleEvent is emitted when onNPCShotVehicle
type NPCShotVehicleEvent struct {
	NPC     *NPC     `json:"npc"`
	Vehicle *Vehicle `json:"vehicle"`
	Weapon  int32    `json:"weapon"`
	OffsetX float32  `json:"offsetx"`
	OffsetY float32  `json:"offsety"`
	OffsetZ float32  `json:"offsetz"`
}

// NPCShotObjectEvent is emitted when onNPCShotObject
type NPCShotObjectEvent struct {
	NPC     *NPC    `json:"npc"`
	Object  *Object `json:"object"`
	Weapon  int32   `json:"weapon"`
	OffsetX float32 `json:"offsetx"`
	OffsetY float32 `json:"offsety"`
	OffsetZ float32 `json:"offsetz"`
}

// NPCShotPlayerObjectEvent is emitted when onNPCShotPlayerObject
type NPCShotPlayerObjectEvent struct {
	NPC          *NPC          `json:"npc"`
	PlayerObject *PlayerObject `json:"playerobject"`
	Weapon       int32         `json:"weapon"`
	OffsetX      float32       `json:"offsetx"`
	OffsetY      float32       `json:"offsety"`
	OffsetZ      float32       `json:"offsetz"`
}

// NPCFinishNodePointEvent is emitted when onNPCFinishNodePoint
type NPCFinishNodePointEvent struct {
	NPC     *NPC  `json:"npc"`
	NodeID  int32 `json:"nodeid"`
	PointID int32 `json:"pointid"`
}

// NPCFinishNodeEvent is emitted when onNPCFinishNode
type NPCFinishNodeEvent struct {
	NPC    *NPC  `json:"npc"`
	NodeID int32 `json:"nodeid"`
}

// NPCChangeNodeEvent is emitted when onNPCChangeNode
type NPCChangeNodeEvent struct {
	NPC       *NPC  `json:"npc"`
	NewNodeID int32 `json:"newnodeid"`
	OldNodeID int32 `json:"oldnodeid"`
}

// NPCFinishMovePathEvent is emitted when onNPCFinishMovePath
type NPCFinishMovePathEvent struct {
	NPC    *NPC  `json:"npc"`
	PathID int32 `json:"pathid"`
}

// NPCFinishMovePathPointEvent is emitted when onNPCFinishMovePathPoint
type NPCFinishMovePathPointEvent struct {
	NPC     *NPC  `json:"npc"`
	PathID  int32 `json:"pathid"`
	PointID int32 `json:"pointid"`
}

// ObjectMoveEvent is emitted when onObjectMove
type ObjectMoveEvent struct {
	Object *Object `json:"object"`
}

// PlayerObjectMoveEvent is emitted when onPlayerObjectMove
type PlayerObjectMoveEvent struct {
	Player *Player `json:"player"`
	Object *Object `json:"object"`
}

// PlayerEditObjectEvent is emitted when onPlayerEditObject
type PlayerEditObjectEvent struct {
	Player    *Player `json:"player"`
	Object    *Object `json:"object"`
	Response  int32   `json:"response"`
	OffsetX   float32 `json:"offsetx"`
	OffsetY   float32 `json:"offsety"`
	OffsetZ   float32 `json:"offsetz"`
	RotationX float32 `json:"rotationx"`
	RotationY float32 `json:"rotationy"`
	RotationZ float32 `json:"rotationz"`
}

// PlayerEditPlayerObjectEvent is emitted when onPlayerEditPlayerObject
type PlayerEditPlayerObjectEvent struct {
	Player    *Player `json:"player"`
	Object    *Object `json:"object"`
	Response  int32   `json:"response"`
	OffsetX   float32 `json:"offsetx"`
	OffsetY   float32 `json:"offsety"`
	OffsetZ   float32 `json:"offsetz"`
	RotationX float32 `json:"rotationx"`
	RotationY float32 `json:"rotationy"`
	RotationZ float32 `json:"rotationz"`
}

// PlayerEditAttachedObjectEvent is emitted when onPlayerEditAttachedObject
type PlayerEditAttachedObjectEvent struct {
	Player    *Player `json:"player"`
	Saved     bool    `json:"saved"`
	Index     int32   `json:"index"`
	Model     int32   `json:"model"`
	Bone      int32   `json:"bone"`
	OffsetX   float32 `json:"offsetx"`
	OffsetY   float32 `json:"offsety"`
	OffsetZ   float32 `json:"offsetz"`
	RotationX float32 `json:"rotationx"`
	RotationY float32 `json:"rotationy"`
	RotationZ float32 `json:"rotationz"`
	ScaleX    float32 `json:"scalex"`
	ScaleY    float32 `json:"scaley"`
	ScaleZ    float32 `json:"scalez"`
}

// PlayerSelectObjectEvent is emitted when onPlayerSelectObject
type PlayerSelectObjectEvent struct {
	Player *Player `json:"player"`
	Object *Object `json:"object"`
	Model  int32   `json:"model"`
	X      float32 `json:"x"`
	Y      float32 `json:"y"`
	Z      float32 `json:"z"`
}

// PlayerSelectPlayerObjectEvent is emitted when onPlayerSelectPlayerObject
type PlayerSelectPlayerObjectEvent struct {
	Player *Player `json:"player"`
	Object *Object `json:"object"`
	Model  int32   `json:"model"`
	X      float32 `json:"x"`
	Y      float32 `json:"y"`
	Z      float32 `json:"z"`
}

// PlayerPickUpPickupEvent is emitted when onPlayerPickUpPickup
type PlayerPickUpPickupEvent struct {
	Player *Player `json:"player"`
	Pickup *Pickup `json:"pickup"`
}

// PlayerConnectEvent is emitted when onPlayerConnect
type PlayerConnectEvent struct {
	Player *Player `json:"player"`
}

// PlayerSpawnEvent is emitted when onPlayerSpawn
type PlayerSpawnEvent struct {
	Player *Player `json:"player"`
}

// PlayerCommandTextEvent is emitted when onPlayerCommandText
type PlayerCommandTextEvent struct {
	Player  *Player            `json:"player"`
	Command BorrowedStringView `json:"command"`
}

// PlayerKeyStateChangeEvent is emitted when onPlayerKeyStateChange
type PlayerKeyStateChangeEvent struct {
	Player  *Player `json:"player"`
	NewKeys int32   `json:"newkeys"`
	OldKeys int32   `json:"oldkeys"`
}

// IncomingConnectionEvent is emitted when onIncomingConnection
type IncomingConnectionEvent struct {
	Player    *Player            `json:"player"`
	IpAddress BorrowedStringView `json:"ipaddress"`
	Port      int32              `json:"port"`
}

// PlayerDisconnectEvent is emitted when onPlayerDisconnect
type PlayerDisconnectEvent struct {
	Player *Player `json:"player"`
	Reason int32   `json:"reason"`
}

// PlayerRequestSpawnEvent is emitted when onPlayerRequestSpawn
type PlayerRequestSpawnEvent struct {
	Player *Player `json:"player"`
}

// PlayerStreamInEvent is emitted when onPlayerStreamIn
type PlayerStreamInEvent struct {
	Player    *Player `json:"player"`
	ForPlayer *Player `json:"forplayer"`
}

// PlayerStreamOutEvent is emitted when onPlayerStreamOut
type PlayerStreamOutEvent struct {
	Player    *Player `json:"player"`
	ForPlayer *Player `json:"forplayer"`
}

// PlayerTextEvent is emitted when onPlayerText
type PlayerTextEvent struct {
	Player *Player            `json:"player"`
	Text   BorrowedStringView `json:"text"`
}

// PlayerShotMissedEvent is emitted when onPlayerShotMissed
type PlayerShotMissedEvent struct {
	Player *Player `json:"player"`
	Weapon int32   `json:"weapon"`
	X      float32 `json:"x"`
	Y      float32 `json:"y"`
	Z      float32 `json:"z"`
}

// PlayerShotPlayerEvent is emitted when onPlayerShotPlayer
type PlayerShotPlayerEvent struct {
	Player *Player `json:"player"`
	Target *Player `json:"target"`
	Weapon int32   `json:"weapon"`
	X      float32 `json:"x"`
	Y      float32 `json:"y"`
	Z      float32 `json:"z"`
}

// PlayerShotVehicleEvent is emitted when onPlayerShotVehicle
type PlayerShotVehicleEvent struct {
	Player *Player  `json:"player"`
	Target *Vehicle `json:"target"`
	Weapon int32    `json:"weapon"`
	X      float32  `json:"x"`
	Y      float32  `json:"y"`
	Z      float32  `json:"z"`
}

// PlayerShotObjectEvent is emitted when onPlayerShotObject
type PlayerShotObjectEvent struct {
	Player *Player `json:"player"`
	Target *Object `json:"target"`
	Weapon int32   `json:"weapon"`
	X      float32 `json:"x"`
	Y      float32 `json:"y"`
	Z      float32 `json:"z"`
}

// PlayerShotPlayerObjectEvent is emitted when onPlayerShotPlayerObject
type PlayerShotPlayerObjectEvent struct {
	Player *Player `json:"player"`
	Target *Object `json:"target"`
	Weapon int32   `json:"weapon"`
	X      float32 `json:"x"`
	Y      float32 `json:"y"`
	Z      float32 `json:"z"`
}

// PlayerDeathEvent is emitted when onPlayerDeath
type PlayerDeathEvent struct {
	Player *Player `json:"player"`
	Killer *Player `json:"killer"`
	Reason int32   `json:"reason"`
}

// PlayerTakeDamageEvent is emitted when onPlayerTakeDamage
type PlayerTakeDamageEvent struct {
	Player   *Player `json:"player"`
	From     *Player `json:"from"`
	Amount   float32 `json:"amount"`
	Weapon   int32   `json:"weapon"`
	Bodypart int32   `json:"bodypart"`
}

// PlayerGiveDamageEvent is emitted when onPlayerGiveDamage
type PlayerGiveDamageEvent struct {
	Player   *Player `json:"player"`
	To       *Player `json:"to"`
	Amount   float32 `json:"amount"`
	Weapon   int32   `json:"weapon"`
	Bodypart int32   `json:"bodypart"`
}

// PlayerInteriorChangeEvent is emitted when onPlayerInteriorChange
type PlayerInteriorChangeEvent struct {
	Player      *Player `json:"player"`
	NewInterior int32   `json:"newinterior"`
	OldInterior int32   `json:"oldinterior"`
}

// PlayerStateChangeEvent is emitted when onPlayerStateChange
type PlayerStateChangeEvent struct {
	Player   *Player `json:"player"`
	NewState int32   `json:"newstate"`
	OldState int32   `json:"oldstate"`
}

// PlayerClickMapEvent is emitted when onPlayerClickMap
type PlayerClickMapEvent struct {
	Player *Player `json:"player"`
	X      float32 `json:"x"`
	Y      float32 `json:"y"`
	Z      float32 `json:"z"`
}

// PlayerClickPlayerEvent is emitted when onPlayerClickPlayer
type PlayerClickPlayerEvent struct {
	Player  *Player `json:"player"`
	Clicked *Player `json:"clicked"`
	Source  int32   `json:"source"`
}

// ClientCheckResponseEvent is emitted when onClientCheckResponse
type ClientCheckResponseEvent struct {
	Player     *Player `json:"player"`
	ActionType int32   `json:"actiontype"`
	Address    int32   `json:"address"`
	Result     int32   `json:"result"`
}

// PlayerUpdateEvent is emitted when onPlayerUpdate
type PlayerUpdateEvent struct {
	Player *Player `json:"player"`
}

// PlayerCancelTextDrawSelectionEvent is emitted when onPlayerCancelTextDrawSelection
type PlayerCancelTextDrawSelectionEvent struct {
	Player *Player `json:"player"`
}

// PlayerCancelPlayerTextDrawSelectionEvent is emitted when onPlayerCancelPlayerTextDrawSelection
type PlayerCancelPlayerTextDrawSelectionEvent struct {
	Player *Player `json:"player"`
}

// PlayerClickTextDrawEvent is emitted when onPlayerClickTextDraw
type PlayerClickTextDrawEvent struct {
	Player   *Player   `json:"player"`
	Textdraw *TextDraw `json:"textdraw"`
}

// PlayerClickPlayerTextDrawEvent is emitted when onPlayerClickPlayerTextDraw
type PlayerClickPlayerTextDrawEvent struct {
	Player   *Player   `json:"player"`
	Textdraw *TextDraw `json:"textdraw"`
}

// VehicleStreamInEvent is emitted when onVehicleStreamIn
type VehicleStreamInEvent struct {
	Vehicle *Vehicle `json:"vehicle"`
	Player  *Player  `json:"player"`
}

// VehicleStreamOutEvent is emitted when onVehicleStreamOut
type VehicleStreamOutEvent struct {
	Vehicle *Vehicle `json:"vehicle"`
	Player  *Player  `json:"player"`
}

// VehicleDeathEvent is emitted when onVehicleDeath
type VehicleDeathEvent struct {
	Vehicle *Vehicle `json:"vehicle"`
	Player  *Player  `json:"player"`
}

// PlayerEnterVehicleEvent is emitted when onPlayerEnterVehicle
type PlayerEnterVehicleEvent struct {
	Player    *Player  `json:"player"`
	Vehicle   *Vehicle `json:"vehicle"`
	Passenger bool     `json:"passenger"`
}

// PlayerExitVehicleEvent is emitted when onPlayerExitVehicle
type PlayerExitVehicleEvent struct {
	Player  *Player  `json:"player"`
	Vehicle *Vehicle `json:"vehicle"`
}

// VehicleDamageStatusUpdateEvent is emitted when onVehicleDamageStatusUpdate
type VehicleDamageStatusUpdateEvent struct {
	Vehicle *Vehicle `json:"vehicle"`
	Player  *Player  `json:"player"`
}

// VehiclePaintJobEvent is emitted when onVehiclePaintJob
type VehiclePaintJobEvent struct {
	Player   *Player  `json:"player"`
	Vehicle  *Vehicle `json:"vehicle"`
	PaintJob int32    `json:"paintjob"`
}

// VehicleModEvent is emitted when onVehicleMod
type VehicleModEvent struct {
	Player    *Player  `json:"player"`
	Vehicle   *Vehicle `json:"vehicle"`
	Component int32    `json:"component"`
}

// VehicleResprayEvent is emitted when onVehicleRespray
type VehicleResprayEvent struct {
	Player  *Player  `json:"player"`
	Vehicle *Vehicle `json:"vehicle"`
	Color1  int32    `json:"color1"`
	Color2  int32    `json:"color2"`
}

// EnterExitModShopEvent is emitted when onEnterExitModShop
type EnterExitModShopEvent struct {
	Player     *Player `json:"player"`
	Enterexit  int32   `json:"enterexit"`
	InteriorID int32   `json:"interiorid"`
}

// VehicleSpawnEvent is emitted when onVehicleSpawn
type VehicleSpawnEvent struct {
	Vehicle *Vehicle `json:"vehicle"`
}

// UnoccupiedVehicleUpdateEvent is emitted when onUnoccupiedVehicleUpdate
type UnoccupiedVehicleUpdateEvent struct {
	Vehicle   *Vehicle `json:"vehicle"`
	Player    *Player  `json:"player"`
	Seat      int32    `json:"seat"`
	PosX      float32  `json:"posx"`
	PosY      float32  `json:"posy"`
	PosZ      float32  `json:"posz"`
	VelocityX float32  `json:"velocityx"`
	VelocityY float32  `json:"velocityy"`
	VelocityZ float32  `json:"velocityz"`
}

// TrailerUpdateEvent is emitted when onTrailerUpdate
type TrailerUpdateEvent struct {
	Player  *Player  `json:"player"`
	Trailer *Vehicle `json:"trailer"`
}

// VehicleSirenStateChangeEvent is emitted when onVehicleSirenStateChange
type VehicleSirenStateChangeEvent struct {
	Player     *Player  `json:"player"`
	Vehicle    *Vehicle `json:"vehicle"`
	SirenState int32    `json:"sirenstate"`
}
