// Code generated by tools/codegen - DO NOT EDIT
package omp

import "context"

// EventHandler is the interface for handling all game events
// Implement only the events you want to handle
type EventHandler interface {
	OnPlayerGiveDamageActor(ctx context.Context, event *PlayerGiveDamageActorEvent) error
	OnActorStreamIn(ctx context.Context, event *ActorStreamInEvent) error
	OnActorStreamOut(ctx context.Context, event *ActorStreamOutEvent) error
	OnPlayerEnterCheckpoint(ctx context.Context, event *PlayerEnterCheckpointEvent) error
	OnPlayerLeaveCheckpoint(ctx context.Context, event *PlayerLeaveCheckpointEvent) error
	OnPlayerEnterRaceCheckpoint(ctx context.Context, event *PlayerEnterRaceCheckpointEvent) error
	OnPlayerLeaveRaceCheckpoint(ctx context.Context, event *PlayerLeaveRaceCheckpointEvent) error
	OnPlayerRequestClass(ctx context.Context, event *PlayerRequestClassEvent) (bool, error)
	OnConsoleText(ctx context.Context, event *ConsoleTextEvent) (bool, error)
	OnRconLoginAttempt(ctx context.Context, event *RconLoginAttemptEvent) (bool, error)
	OnTick(ctx context.Context, event *TickEvent) error
	OnPlayerFinishedDownloading(ctx context.Context, event *PlayerFinishedDownloadingEvent) error
	OnPlayerRequestDownload(ctx context.Context, event *PlayerRequestDownloadEvent) error
	OnDialogResponse(ctx context.Context, event *DialogResponseEvent) error
	OnPlayerEnterGangZone(ctx context.Context, event *PlayerEnterGangZoneEvent) error
	OnPlayerLeaveGangZone(ctx context.Context, event *PlayerLeaveGangZoneEvent) error
	OnPlayerClickGangZone(ctx context.Context, event *PlayerClickGangZoneEvent) error
	OnPlayerSelectedMenuRow(ctx context.Context, event *PlayerSelectedMenuRowEvent) error
	OnPlayerExitedMenu(ctx context.Context, event *PlayerExitedMenuEvent) error
	OnNPCFinishMove(ctx context.Context, event *NPCFinishMoveEvent) error
	OnNPCCreate(ctx context.Context, event *NPCCreateEvent) error
	OnNPCDestroy(ctx context.Context, event *NPCDestroyEvent) error
	OnNPCWeaponStateChange(ctx context.Context, event *NPCWeaponStateChangeEvent) error
	OnNPCTakeDamage(ctx context.Context, event *NPCTakeDamageEvent) (bool, error)
	OnNPCGiveDamage(ctx context.Context, event *NPCGiveDamageEvent) (bool, error)
	OnNPCDeath(ctx context.Context, event *NPCDeathEvent) error
	OnNPCSpawn(ctx context.Context, event *NPCSpawnEvent) error
	OnNPCRespawn(ctx context.Context, event *NPCRespawnEvent) error
	OnNPCPlaybackStart(ctx context.Context, event *NPCPlaybackStartEvent) error
	OnNPCPlaybackEnd(ctx context.Context, event *NPCPlaybackEndEvent) error
	OnNPCShotMissed(ctx context.Context, event *NPCShotMissedEvent) (bool, error)
	OnNPCShotPlayer(ctx context.Context, event *NPCShotPlayerEvent) (bool, error)
	OnNPCShotNPC(ctx context.Context, event *NPCShotNPCEvent) (bool, error)
	OnNPCShotVehicle(ctx context.Context, event *NPCShotVehicleEvent) (bool, error)
	OnNPCShotObject(ctx context.Context, event *NPCShotObjectEvent) (bool, error)
	OnNPCShotPlayerObject(ctx context.Context, event *NPCShotPlayerObjectEvent) (bool, error)
	OnNPCFinishNodePoint(ctx context.Context, event *NPCFinishNodePointEvent) error
	OnNPCFinishNode(ctx context.Context, event *NPCFinishNodeEvent) error
	OnNPCChangeNode(ctx context.Context, event *NPCChangeNodeEvent) (bool, error)
	OnNPCFinishMovePath(ctx context.Context, event *NPCFinishMovePathEvent) error
	OnNPCFinishMovePathPoint(ctx context.Context, event *NPCFinishMovePathPointEvent) error
	OnObjectMove(ctx context.Context, event *ObjectMoveEvent) error
	OnPlayerObjectMove(ctx context.Context, event *PlayerObjectMoveEvent) error
	OnPlayerEditObject(ctx context.Context, event *PlayerEditObjectEvent) error
	OnPlayerEditPlayerObject(ctx context.Context, event *PlayerEditPlayerObjectEvent) error
	OnPlayerEditAttachedObject(ctx context.Context, event *PlayerEditAttachedObjectEvent) error
	OnPlayerSelectObject(ctx context.Context, event *PlayerSelectObjectEvent) error
	OnPlayerSelectPlayerObject(ctx context.Context, event *PlayerSelectPlayerObjectEvent) error
	OnPlayerPickUpPickup(ctx context.Context, event *PlayerPickUpPickupEvent) error
	OnPlayerConnect(ctx context.Context, event *PlayerConnectEvent) error
	OnPlayerSpawn(ctx context.Context, event *PlayerSpawnEvent) error
	OnPlayerCommandText(ctx context.Context, event *PlayerCommandTextEvent) (bool, error)
	OnPlayerKeyStateChange(ctx context.Context, event *PlayerKeyStateChangeEvent) error
	OnIncomingConnection(ctx context.Context, event *IncomingConnectionEvent) error
	OnPlayerDisconnect(ctx context.Context, event *PlayerDisconnectEvent) error
	OnPlayerRequestSpawn(ctx context.Context, event *PlayerRequestSpawnEvent) (bool, error)
	OnPlayerStreamIn(ctx context.Context, event *PlayerStreamInEvent) error
	OnPlayerStreamOut(ctx context.Context, event *PlayerStreamOutEvent) error
	OnPlayerText(ctx context.Context, event *PlayerTextEvent) (bool, error)
	OnPlayerShotMissed(ctx context.Context, event *PlayerShotMissedEvent) (bool, error)
	OnPlayerShotPlayer(ctx context.Context, event *PlayerShotPlayerEvent) (bool, error)
	OnPlayerShotVehicle(ctx context.Context, event *PlayerShotVehicleEvent) (bool, error)
	OnPlayerShotObject(ctx context.Context, event *PlayerShotObjectEvent) (bool, error)
	OnPlayerShotPlayerObject(ctx context.Context, event *PlayerShotPlayerObjectEvent) (bool, error)
	OnPlayerDeath(ctx context.Context, event *PlayerDeathEvent) error
	OnPlayerTakeDamage(ctx context.Context, event *PlayerTakeDamageEvent) error
	OnPlayerGiveDamage(ctx context.Context, event *PlayerGiveDamageEvent) error
	OnPlayerInteriorChange(ctx context.Context, event *PlayerInteriorChangeEvent) error
	OnPlayerStateChange(ctx context.Context, event *PlayerStateChangeEvent) error
	OnPlayerClickMap(ctx context.Context, event *PlayerClickMapEvent) error
	OnPlayerClickPlayer(ctx context.Context, event *PlayerClickPlayerEvent) error
	OnClientCheckResponse(ctx context.Context, event *ClientCheckResponseEvent) error
	OnPlayerUpdate(ctx context.Context, event *PlayerUpdateEvent) (bool, error)
	OnPlayerCancelTextDrawSelection(ctx context.Context, event *PlayerCancelTextDrawSelectionEvent) error
	OnPlayerCancelPlayerTextDrawSelection(ctx context.Context, event *PlayerCancelPlayerTextDrawSelectionEvent) error
	OnPlayerClickTextDraw(ctx context.Context, event *PlayerClickTextDrawEvent) error
	OnPlayerClickPlayerTextDraw(ctx context.Context, event *PlayerClickPlayerTextDrawEvent) error
	OnVehicleStreamIn(ctx context.Context, event *VehicleStreamInEvent) error
	OnVehicleStreamOut(ctx context.Context, event *VehicleStreamOutEvent) error
	OnVehicleDeath(ctx context.Context, event *VehicleDeathEvent) error
	OnPlayerEnterVehicle(ctx context.Context, event *PlayerEnterVehicleEvent) error
	OnPlayerExitVehicle(ctx context.Context, event *PlayerExitVehicleEvent) error
	OnVehicleDamageStatusUpdate(ctx context.Context, event *VehicleDamageStatusUpdateEvent) error
	OnVehiclePaintJob(ctx context.Context, event *VehiclePaintJobEvent) (bool, error)
	OnVehicleMod(ctx context.Context, event *VehicleModEvent) (bool, error)
	OnVehicleRespray(ctx context.Context, event *VehicleResprayEvent) (bool, error)
	OnEnterExitModShop(ctx context.Context, event *EnterExitModShopEvent) error
	OnVehicleSpawn(ctx context.Context, event *VehicleSpawnEvent) error
	OnUnoccupiedVehicleUpdate(ctx context.Context, event *UnoccupiedVehicleUpdateEvent) (bool, error)
	OnTrailerUpdate(ctx context.Context, event *TrailerUpdateEvent) (bool, error)
	OnVehicleSirenStateChange(ctx context.Context, event *VehicleSirenStateChangeEvent) (bool, error)
}

// BaseEventHandler provides default no-op implementations for all events
// Embed this to only implement events you care about
type BaseEventHandler struct{}

func (b *BaseEventHandler) OnPlayerGiveDamageActor(ctx context.Context, event *PlayerGiveDamageActorEvent) error {
	return nil
}
func (b *BaseEventHandler) OnActorStreamIn(ctx context.Context, event *ActorStreamInEvent) error {
	return nil
}
func (b *BaseEventHandler) OnActorStreamOut(ctx context.Context, event *ActorStreamOutEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerEnterCheckpoint(ctx context.Context, event *PlayerEnterCheckpointEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerLeaveCheckpoint(ctx context.Context, event *PlayerLeaveCheckpointEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerEnterRaceCheckpoint(ctx context.Context, event *PlayerEnterRaceCheckpointEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerLeaveRaceCheckpoint(ctx context.Context, event *PlayerLeaveRaceCheckpointEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerRequestClass(ctx context.Context, event *PlayerRequestClassEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnConsoleText(ctx context.Context, event *ConsoleTextEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnRconLoginAttempt(ctx context.Context, event *RconLoginAttemptEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnTick(ctx context.Context, event *TickEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerFinishedDownloading(ctx context.Context, event *PlayerFinishedDownloadingEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerRequestDownload(ctx context.Context, event *PlayerRequestDownloadEvent) error {
	return nil
}
func (b *BaseEventHandler) OnDialogResponse(ctx context.Context, event *DialogResponseEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerEnterGangZone(ctx context.Context, event *PlayerEnterGangZoneEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerLeaveGangZone(ctx context.Context, event *PlayerLeaveGangZoneEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerClickGangZone(ctx context.Context, event *PlayerClickGangZoneEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerSelectedMenuRow(ctx context.Context, event *PlayerSelectedMenuRowEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerExitedMenu(ctx context.Context, event *PlayerExitedMenuEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCFinishMove(ctx context.Context, event *NPCFinishMoveEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCCreate(ctx context.Context, event *NPCCreateEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCDestroy(ctx context.Context, event *NPCDestroyEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCWeaponStateChange(ctx context.Context, event *NPCWeaponStateChangeEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCTakeDamage(ctx context.Context, event *NPCTakeDamageEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnNPCGiveDamage(ctx context.Context, event *NPCGiveDamageEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnNPCDeath(ctx context.Context, event *NPCDeathEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCSpawn(ctx context.Context, event *NPCSpawnEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCRespawn(ctx context.Context, event *NPCRespawnEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCPlaybackStart(ctx context.Context, event *NPCPlaybackStartEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCPlaybackEnd(ctx context.Context, event *NPCPlaybackEndEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCShotMissed(ctx context.Context, event *NPCShotMissedEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnNPCShotPlayer(ctx context.Context, event *NPCShotPlayerEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnNPCShotNPC(ctx context.Context, event *NPCShotNPCEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnNPCShotVehicle(ctx context.Context, event *NPCShotVehicleEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnNPCShotObject(ctx context.Context, event *NPCShotObjectEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnNPCShotPlayerObject(ctx context.Context, event *NPCShotPlayerObjectEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnNPCFinishNodePoint(ctx context.Context, event *NPCFinishNodePointEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCFinishNode(ctx context.Context, event *NPCFinishNodeEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCChangeNode(ctx context.Context, event *NPCChangeNodeEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnNPCFinishMovePath(ctx context.Context, event *NPCFinishMovePathEvent) error {
	return nil
}
func (b *BaseEventHandler) OnNPCFinishMovePathPoint(ctx context.Context, event *NPCFinishMovePathPointEvent) error {
	return nil
}
func (b *BaseEventHandler) OnObjectMove(ctx context.Context, event *ObjectMoveEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerObjectMove(ctx context.Context, event *PlayerObjectMoveEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerEditObject(ctx context.Context, event *PlayerEditObjectEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerEditPlayerObject(ctx context.Context, event *PlayerEditPlayerObjectEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerEditAttachedObject(ctx context.Context, event *PlayerEditAttachedObjectEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerSelectObject(ctx context.Context, event *PlayerSelectObjectEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerSelectPlayerObject(ctx context.Context, event *PlayerSelectPlayerObjectEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerPickUpPickup(ctx context.Context, event *PlayerPickUpPickupEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerConnect(ctx context.Context, event *PlayerConnectEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerSpawn(ctx context.Context, event *PlayerSpawnEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerCommandText(ctx context.Context, event *PlayerCommandTextEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnPlayerKeyStateChange(ctx context.Context, event *PlayerKeyStateChangeEvent) error {
	return nil
}
func (b *BaseEventHandler) OnIncomingConnection(ctx context.Context, event *IncomingConnectionEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerDisconnect(ctx context.Context, event *PlayerDisconnectEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerRequestSpawn(ctx context.Context, event *PlayerRequestSpawnEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnPlayerStreamIn(ctx context.Context, event *PlayerStreamInEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerStreamOut(ctx context.Context, event *PlayerStreamOutEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerText(ctx context.Context, event *PlayerTextEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnPlayerShotMissed(ctx context.Context, event *PlayerShotMissedEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnPlayerShotPlayer(ctx context.Context, event *PlayerShotPlayerEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnPlayerShotVehicle(ctx context.Context, event *PlayerShotVehicleEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnPlayerShotObject(ctx context.Context, event *PlayerShotObjectEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnPlayerShotPlayerObject(ctx context.Context, event *PlayerShotPlayerObjectEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnPlayerDeath(ctx context.Context, event *PlayerDeathEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerTakeDamage(ctx context.Context, event *PlayerTakeDamageEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerGiveDamage(ctx context.Context, event *PlayerGiveDamageEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerInteriorChange(ctx context.Context, event *PlayerInteriorChangeEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerStateChange(ctx context.Context, event *PlayerStateChangeEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerClickMap(ctx context.Context, event *PlayerClickMapEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerClickPlayer(ctx context.Context, event *PlayerClickPlayerEvent) error {
	return nil
}
func (b *BaseEventHandler) OnClientCheckResponse(ctx context.Context, event *ClientCheckResponseEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerUpdate(ctx context.Context, event *PlayerUpdateEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnPlayerCancelTextDrawSelection(ctx context.Context, event *PlayerCancelTextDrawSelectionEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerCancelPlayerTextDrawSelection(ctx context.Context, event *PlayerCancelPlayerTextDrawSelectionEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerClickTextDraw(ctx context.Context, event *PlayerClickTextDrawEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerClickPlayerTextDraw(ctx context.Context, event *PlayerClickPlayerTextDrawEvent) error {
	return nil
}
func (b *BaseEventHandler) OnVehicleStreamIn(ctx context.Context, event *VehicleStreamInEvent) error {
	return nil
}
func (b *BaseEventHandler) OnVehicleStreamOut(ctx context.Context, event *VehicleStreamOutEvent) error {
	return nil
}
func (b *BaseEventHandler) OnVehicleDeath(ctx context.Context, event *VehicleDeathEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerEnterVehicle(ctx context.Context, event *PlayerEnterVehicleEvent) error {
	return nil
}
func (b *BaseEventHandler) OnPlayerExitVehicle(ctx context.Context, event *PlayerExitVehicleEvent) error {
	return nil
}
func (b *BaseEventHandler) OnVehicleDamageStatusUpdate(ctx context.Context, event *VehicleDamageStatusUpdateEvent) error {
	return nil
}
func (b *BaseEventHandler) OnVehiclePaintJob(ctx context.Context, event *VehiclePaintJobEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnVehicleMod(ctx context.Context, event *VehicleModEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnVehicleRespray(ctx context.Context, event *VehicleResprayEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnEnterExitModShop(ctx context.Context, event *EnterExitModShopEvent) error {
	return nil
}
func (b *BaseEventHandler) OnVehicleSpawn(ctx context.Context, event *VehicleSpawnEvent) error {
	return nil
}
func (b *BaseEventHandler) OnUnoccupiedVehicleUpdate(ctx context.Context, event *UnoccupiedVehicleUpdateEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnTrailerUpdate(ctx context.Context, event *TrailerUpdateEvent) (bool, error) {
	return true, nil
}
func (b *BaseEventHandler) OnVehicleSirenStateChange(ctx context.Context, event *VehicleSirenStateChangeEvent) (bool, error) {
	return true, nil
}
