// Code generated by tools/codegen - DO NOT EDIT
package omp

import "github.com/ompgo-dev/ompgo/pkg/handle"

// Player is a safe wrapper around an open.mp player handle
type Player struct {
	handle handle.Handle
}

// NewPlayer creates a Player from an opaque handle
func NewPlayer(handle handle.Handle) *Player {
	if handle == 0 {
		return nil
	}
	return &Player{handle: handle}
}

// Handle returns the underlying handle
func (e *Player) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *Player) Valid() bool {
	return e != nil && e.handle != 0
}

// Vehicle is a safe wrapper around an open.mp vehicle handle
type Vehicle struct {
	handle handle.Handle
}

// NewVehicle creates a Vehicle from an opaque handle
func NewVehicle(handle handle.Handle) *Vehicle {
	if handle == 0 {
		return nil
	}
	return &Vehicle{handle: handle}
}

// Handle returns the underlying handle
func (e *Vehicle) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *Vehicle) Valid() bool {
	return e != nil && e.handle != 0
}

// Actor is a safe wrapper around an open.mp actor handle
type Actor struct {
	handle handle.Handle
}

// NewActor creates a Actor from an opaque handle
func NewActor(handle handle.Handle) *Actor {
	if handle == 0 {
		return nil
	}
	return &Actor{handle: handle}
}

// Handle returns the underlying handle
func (e *Actor) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *Actor) Valid() bool {
	return e != nil && e.handle != 0
}

// Object is a safe wrapper around an open.mp object handle
type Object struct {
	handle handle.Handle
}

// NewObject creates a Object from an opaque handle
func NewObject(handle handle.Handle) *Object {
	if handle == 0 {
		return nil
	}
	return &Object{handle: handle}
}

// Handle returns the underlying handle
func (e *Object) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *Object) Valid() bool {
	return e != nil && e.handle != 0
}

// PlayerObject is a safe wrapper around an open.mp playerobject handle
type PlayerObject struct {
	handle handle.Handle
}

// NewPlayerObject creates a PlayerObject from an opaque handle
func NewPlayerObject(handle handle.Handle) *PlayerObject {
	if handle == 0 {
		return nil
	}
	return &PlayerObject{handle: handle}
}

// Handle returns the underlying handle
func (e *PlayerObject) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *PlayerObject) Valid() bool {
	return e != nil && e.handle != 0
}

// Pickup is a safe wrapper around an open.mp pickup handle
type Pickup struct {
	handle handle.Handle
}

// NewPickup creates a Pickup from an opaque handle
func NewPickup(handle handle.Handle) *Pickup {
	if handle == 0 {
		return nil
	}
	return &Pickup{handle: handle}
}

// Handle returns the underlying handle
func (e *Pickup) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *Pickup) Valid() bool {
	return e != nil && e.handle != 0
}

// TextDraw is a safe wrapper around an open.mp textdraw handle
type TextDraw struct {
	handle handle.Handle
}

// NewTextDraw creates a TextDraw from an opaque handle
func NewTextDraw(handle handle.Handle) *TextDraw {
	if handle == 0 {
		return nil
	}
	return &TextDraw{handle: handle}
}

// Handle returns the underlying handle
func (e *TextDraw) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *TextDraw) Valid() bool {
	return e != nil && e.handle != 0
}

// PlayerTextDraw is a safe wrapper around an open.mp playertextdraw handle
type PlayerTextDraw struct {
	handle handle.Handle
}

// NewPlayerTextDraw creates a PlayerTextDraw from an opaque handle
func NewPlayerTextDraw(handle handle.Handle) *PlayerTextDraw {
	if handle == 0 {
		return nil
	}
	return &PlayerTextDraw{handle: handle}
}

// Handle returns the underlying handle
func (e *PlayerTextDraw) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *PlayerTextDraw) Valid() bool {
	return e != nil && e.handle != 0
}

// TextLabel is a safe wrapper around an open.mp textlabel handle
type TextLabel struct {
	handle handle.Handle
}

// NewTextLabel creates a TextLabel from an opaque handle
func NewTextLabel(handle handle.Handle) *TextLabel {
	if handle == 0 {
		return nil
	}
	return &TextLabel{handle: handle}
}

// Handle returns the underlying handle
func (e *TextLabel) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *TextLabel) Valid() bool {
	return e != nil && e.handle != 0
}

// PlayerTextLabel is a safe wrapper around an open.mp playertextlabel handle
type PlayerTextLabel struct {
	handle handle.Handle
}

// NewPlayerTextLabel creates a PlayerTextLabel from an opaque handle
func NewPlayerTextLabel(handle handle.Handle) *PlayerTextLabel {
	if handle == 0 {
		return nil
	}
	return &PlayerTextLabel{handle: handle}
}

// Handle returns the underlying handle
func (e *PlayerTextLabel) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *PlayerTextLabel) Valid() bool {
	return e != nil && e.handle != 0
}

// GangZone is a safe wrapper around an open.mp gangzone handle
type GangZone struct {
	handle handle.Handle
}

// NewGangZone creates a GangZone from an opaque handle
func NewGangZone(handle handle.Handle) *GangZone {
	if handle == 0 {
		return nil
	}
	return &GangZone{handle: handle}
}

// Handle returns the underlying handle
func (e *GangZone) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *GangZone) Valid() bool {
	return e != nil && e.handle != 0
}

// Menu is a safe wrapper around an open.mp menu handle
type Menu struct {
	handle handle.Handle
}

// NewMenu creates a Menu from an opaque handle
func NewMenu(handle handle.Handle) *Menu {
	if handle == 0 {
		return nil
	}
	return &Menu{handle: handle}
}

// Handle returns the underlying handle
func (e *Menu) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *Menu) Valid() bool {
	return e != nil && e.handle != 0
}

// Checkpoint is a safe wrapper around an open.mp checkpoint handle
type Checkpoint struct {
	handle handle.Handle
}

// NewCheckpoint creates a Checkpoint from an opaque handle
func NewCheckpoint(handle handle.Handle) *Checkpoint {
	if handle == 0 {
		return nil
	}
	return &Checkpoint{handle: handle}
}

// Handle returns the underlying handle
func (e *Checkpoint) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *Checkpoint) Valid() bool {
	return e != nil && e.handle != 0
}

// NPC is a safe wrapper around an open.mp npc handle
type NPC struct {
	handle handle.Handle
}

// NewNPC creates a NPC from an opaque handle
func NewNPC(handle handle.Handle) *NPC {
	if handle == 0 {
		return nil
	}
	return &NPC{handle: handle}
}

// Handle returns the underlying handle
func (e *NPC) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *NPC) Valid() bool {
	return e != nil && e.handle != 0
}

// Class is a safe wrapper around an open.mp class handle
type Class struct {
	handle handle.Handle
}

// NewClass creates a Class from an opaque handle
func NewClass(handle handle.Handle) *Class {
	if handle == 0 {
		return nil
	}
	return &Class{handle: handle}
}

// Handle returns the underlying handle
func (e *Class) Handle() handle.Handle {
	if e == nil {
		return 0
	}
	return e.handle
}

// Valid returns true if the handle is not nil
func (e *Class) Valid() bool {
	return e != nil && e.handle != 0
}

// Vector3 represents a 3D position
type Vector3 struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
	Z float32 `json:"z"`
}

// Vector4 represents a 4D vector (often rotation)
type Vector4 struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
	Z float32 `json:"z"`
	W float32 `json:"w"`
}

// Color represents an RGBA color
type Color uint32

// RGBA creates a Color from RGBA components
func RGBA(r uint8, g uint8, b uint8, a uint8) Color {
	return Color(uint32(r)<<24 | uint32(g)<<16 | uint32(b)<<8 | uint32(a))
}

// RGB creates a Color from RGB components with full alpha
func RGB(r uint8, g uint8, b uint8) Color {
	return RGBA(r, g, b, 255)
}

// Common color constants
const (
	ColorWhite  = Color(uint32(0xffffffff))
	ColorBlack  = Color(uint32(0xff))
	ColorRed    = Color(uint32(0xff0000ff))
	ColorGreen  = Color(uint32(0xff00ff))
	ColorBlue   = Color(uint32(0xffff))
	ColorYellow = Color(uint32(0xffff00ff))
	ColorOrange = Color(uint32(0xff8000ff))
	ColorPurple = Color(uint32(0x8000ffff))
	ColorGrey   = Color(uint32(0xaaaaafff))
)
