// Code generated by tools/codegen - DO NOT EDIT
package dialog

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Show wraps CAPI Dialog_Show
func Show(player *omp.Player, dialog int32, style int32, title string, body string, button1 string, button2 string) bool {
	c := runtime.Instance().CAPI()
	return c.Dialog_Show(player.Handle(), dialog, style, title, body, button1, button2)
}

// Hide wraps CAPI Dialog_Hide
func Hide(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Dialog_Hide(player.Handle())
}
