// Code generated by tools/codegen - DO NOT EDIT
package pickup

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI Pickup_Create
func Create(model int32, typ int32, x float32, y float32, z float32, virtualWorld int32, id *int32) *omp.Pickup {
	c := runtime.Instance().CAPI()
	res := c.Pickup_Create(model, typ, x, y, z, virtualWorld, id)
	return omp.NewPickup(res)
}

// AddStatic wraps CAPI Pickup_AddStatic
func AddStatic(model int32, typ int32, x float32, y float32, z float32, virtualWorld int32) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_AddStatic(model, typ, x, y, z, virtualWorld)
}

// Destroy wraps CAPI Pickup_Destroy
func Destroy(pickup *omp.Pickup) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_Destroy(pickup.Handle())
}

// FromID wraps CAPI Pickup_FromID
func FromID(pickupid int32) *omp.Pickup {
	c := runtime.Instance().CAPI()
	res := c.Pickup_FromID(pickupid)
	return omp.NewPickup(res)
}

// GetID wraps CAPI Pickup_GetID
func GetID(pickup *omp.Pickup) int32 {
	c := runtime.Instance().CAPI()
	return c.Pickup_GetID(pickup.Handle())
}

// IsValid wraps CAPI Pickup_IsValid
func IsValid(pickup *omp.Pickup) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_IsValid(pickup.Handle())
}

// IsStreamedIn wraps CAPI Pickup_IsStreamedIn
func IsStreamedIn(player *omp.Player, pickup *omp.Pickup) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_IsStreamedIn(player.Handle(), pickup.Handle())
}

// GetPos wraps CAPI Pickup_GetPos
func GetPos(pickup *omp.Pickup, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_GetPos(pickup.Handle(), x, y, z)
}

// GetModel wraps CAPI Pickup_GetModel
func GetModel(pickup *omp.Pickup) int32 {
	c := runtime.Instance().CAPI()
	return c.Pickup_GetModel(pickup.Handle())
}

// GetType wraps CAPI Pickup_GetType
func GetType(pickup *omp.Pickup) int32 {
	c := runtime.Instance().CAPI()
	return c.Pickup_GetType(pickup.Handle())
}

// GetVirtualWorld wraps CAPI Pickup_GetVirtualWorld
func GetVirtualWorld(pickup *omp.Pickup) int32 {
	c := runtime.Instance().CAPI()
	return c.Pickup_GetVirtualWorld(pickup.Handle())
}

// SetPos wraps CAPI Pickup_SetPos
func SetPos(pickup *omp.Pickup, x float32, y float32, z float32, update bool) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_SetPos(pickup.Handle(), x, y, z, update)
}

// SetModel wraps CAPI Pickup_SetModel
func SetModel(pickup *omp.Pickup, model int32, update bool) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_SetModel(pickup.Handle(), model, update)
}

// SetType wraps CAPI Pickup_SetType
func SetType(pickup *omp.Pickup, typ int32, update bool) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_SetType(pickup.Handle(), typ, update)
}

// SetVirtualWorld wraps CAPI Pickup_SetVirtualWorld
func SetVirtualWorld(pickup *omp.Pickup, virtualworld int32) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_SetVirtualWorld(pickup.Handle(), virtualworld)
}

// ShowForPlayer wraps CAPI Pickup_ShowForPlayer
func ShowForPlayer(player *omp.Player, pickup *omp.Pickup) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_ShowForPlayer(player.Handle(), pickup.Handle())
}

// HideForPlayer wraps CAPI Pickup_HideForPlayer
func HideForPlayer(player *omp.Player, pickup *omp.Pickup) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_HideForPlayer(player.Handle(), pickup.Handle())
}

// IsHiddenForPlayer wraps CAPI Pickup_IsHiddenForPlayer
func IsHiddenForPlayer(player *omp.Player, pickup *omp.Pickup) bool {
	c := runtime.Instance().CAPI()
	return c.Pickup_IsHiddenForPlayer(player.Handle(), pickup.Handle())
}
