// Code generated by tools/codegen - DO NOT EDIT
package class

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Add wraps CAPI Class_Add
func Add(team uint8, skin int32, x float32, y float32, z float32, angle float32, weapon1 uint8, ammo1 uint32, weapon2 uint8, ammo2 uint32, weapon3 uint8, ammo3 uint32, id *int32) *omp.Class {
	c := runtime.Instance().CAPI()
	res := c.Class_Add(team, skin, x, y, z, angle, weapon1, ammo1, weapon2, ammo2, weapon3, ammo3, id)
	return omp.NewClass(res)
}

// FromID wraps CAPI Class_FromID
func FromID(classid int32) *omp.Class {
	c := runtime.Instance().CAPI()
	res := c.Class_FromID(classid)
	return omp.NewClass(res)
}

// GetID wraps CAPI Class_GetID
func GetID(cls *omp.Class) int32 {
	c := runtime.Instance().CAPI()
	return c.Class_GetID(cls.Handle())
}

// Count wraps CAPI Class_Count
func Count() int32 {
	c := runtime.Instance().CAPI()
	return c.Class_Count()
}

// GetData wraps CAPI Class_GetData
func GetData(classptr *omp.Class, teamid *uint8, skin *int32, x *float32, y *float32, z *float32, angle *float32, weapon1 *uint8, weapon1Ammo *uint32, weapon2 *uint8, weapon2Ammo *uint32, weapon3 *uint8, weapon3Ammo *uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Class_GetData(classptr.Handle(), teamid, skin, x, y, z, angle, weapon1, weapon1Ammo, weapon2, weapon2Ammo, weapon3, weapon3Ammo)
}

// Edit wraps CAPI Class_Edit
func Edit(classptr *omp.Class, teamid uint8, skin int32, x float32, y float32, z float32, angle float32, weapon1 uint8, ammo1 uint32, weapon2 uint8, ammo2 uint32, weapon3 uint8, ammo3 uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Class_Edit(classptr.Handle(), teamid, skin, x, y, z, angle, weapon1, ammo1, weapon2, ammo2, weapon3, ammo3)
}
