// Code generated by tools/codegen - DO NOT EDIT
package players

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// SetSpawnInfo wraps CAPI Player_SetSpawnInfo
func SetSpawnInfo(player *omp.Player, team uint8, skin int32, x float32, y float32, z float32, angle float32, weapon1 uint8, ammo1 uint32, weapon2 uint8, ammo2 uint32, weapon3 uint8, ammo3 uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetSpawnInfo(player.Handle(), team, skin, x, y, z, angle, weapon1, ammo1, weapon2, ammo2, weapon3, ammo3)
}

// GetSpawnInfo wraps CAPI Player_GetSpawnInfo
func GetSpawnInfo(player *omp.Player, team *uint8, skin *int32, x *float32, y *float32, z *float32, angle *float32, weapon1 *uint8, ammo1 *uint32, weapon2 *uint8, ammo2 *uint32, weapon3 *uint8, ammo3 *uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetSpawnInfo(player.Handle(), team, skin, x, y, z, angle, weapon1, ammo1, weapon2, ammo2, weapon3, ammo3)
}

// GetNetworkStatsString wraps CAPI Player_GetNetworkStats and returns a string.
func GetNetworkStatsString(player *omp.Player) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Player_GetNetworkStatsString(player.Handle())
}

// NetStatsBytesReceived wraps CAPI Player_NetStatsBytesReceived
func NetStatsBytesReceived(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_NetStatsBytesReceived(player.Handle())
}

// NetStatsBytesSent wraps CAPI Player_NetStatsBytesSent
func NetStatsBytesSent(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_NetStatsBytesSent(player.Handle())
}

// NetStatsConnectionStatus wraps CAPI Player_NetStatsConnectionStatus
func NetStatsConnectionStatus(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_NetStatsConnectionStatus(player.Handle())
}

// NetStatsGetConnectedTime wraps CAPI Player_NetStatsGetConnectedTime
func NetStatsGetConnectedTime(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_NetStatsGetConnectedTime(player.Handle())
}

// NetStatsGetIPPortString wraps CAPI Player_NetStatsGetIpPort and returns a string.
func NetStatsGetIPPortString(player *omp.Player) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Player_NetStatsGetIpPortString(player.Handle())
}

// NetStatsMessagesReceived wraps CAPI Player_NetStatsMessagesReceived
func NetStatsMessagesReceived(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_NetStatsMessagesReceived(player.Handle())
}

// NetStatsMessagesRecvPerSecond wraps CAPI Player_NetStatsMessagesRecvPerSecond
func NetStatsMessagesRecvPerSecond(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_NetStatsMessagesRecvPerSecond(player.Handle())
}

// NetStatsMessagesSent wraps CAPI Player_NetStatsMessagesSent
func NetStatsMessagesSent(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_NetStatsMessagesSent(player.Handle())
}

// NetStatsPacketLossPercent wraps CAPI Player_NetStatsPacketLossPercent
func NetStatsPacketLossPercent(player *omp.Player) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_NetStatsPacketLossPercent(player.Handle())
}

// GetCustomSkin wraps CAPI Player_GetCustomSkin
func GetCustomSkin(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetCustomSkin(player.Handle())
}

// GetDialog wraps CAPI Player_GetDialog
func GetDialog(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetDialog(player.Handle())
}

// GetDialogData wraps CAPI Player_GetDialogData
func GetDialogData(player *omp.Player, dialogid *int32, style *int32, title *string, body *string, button1 *string, button2 *string) bool {
	c := runtime.Instance().CAPI()
	var titleView runtime.CAPIStringView
	var bodyView runtime.CAPIStringView
	var button1View runtime.CAPIStringView
	var button2View runtime.CAPIStringView
	res := c.Player_GetDialogData(player.Handle(), dialogid, style, &titleView, &bodyView, &button1View, &button2View)
	if title != nil {
		*title = runtime.CAPIStringViewToString(&titleView)
	}
	if body != nil {
		*body = runtime.CAPIStringViewToString(&bodyView)
	}
	if button1 != nil {
		*button1 = runtime.CAPIStringViewToString(&button1View)
	}
	if button2 != nil {
		*button2 = runtime.CAPIStringViewToString(&button2View)
	}
	return res
}

// GetMenu wraps CAPI Player_GetMenu
func GetMenu(player *omp.Player) *omp.Menu {
	c := runtime.Instance().CAPI()
	res := c.Player_GetMenu(player.Handle())
	return omp.NewMenu(res)
}

// GetSurfingPlayerObject wraps CAPI Player_GetSurfingPlayerObject
func GetSurfingPlayerObject(player *omp.Player) *omp.PlayerObject {
	c := runtime.Instance().CAPI()
	res := c.Player_GetSurfingPlayerObject(player.Handle())
	return omp.NewPlayerObject(res)
}

// GetCameraTargetPlayerObject wraps CAPI Player_GetCameraTargetPlayerObject
func GetCameraTargetPlayerObject(player *omp.Player) *omp.PlayerObject {
	c := runtime.Instance().CAPI()
	res := c.Player_GetCameraTargetPlayerObject(player.Handle())
	return omp.NewPlayerObject(res)
}

// FromID wraps CAPI Player_FromID
func FromID(playerid int32) *omp.Player {
	c := runtime.Instance().CAPI()
	res := c.Player_FromID(playerid)
	return omp.NewPlayer(res)
}

// GetID wraps CAPI Player_GetID
func GetID(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetID(player.Handle())
}

// SendClientMessage wraps CAPI Player_SendClientMessage
func SendClientMessage(player *omp.Player, color uint32, text string) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SendClientMessage(player.Handle(), color, text)
}

// SetCameraPos wraps CAPI Player_SetCameraPos
func SetCameraPos(player *omp.Player, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetCameraPos(player.Handle(), x, y, z)
}

// SetDrunkLevel wraps CAPI Player_SetDrunkLevel
func SetDrunkLevel(player *omp.Player, level int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetDrunkLevel(player.Handle(), level)
}

// SetInterior wraps CAPI Player_SetInterior
func SetInterior(player *omp.Player, interior int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetInterior(player.Handle(), interior)
}

// SetWantedLevel wraps CAPI Player_SetWantedLevel
func SetWantedLevel(player *omp.Player, level int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetWantedLevel(player.Handle(), level)
}

// SetWeather wraps CAPI Player_SetWeather
func SetWeather(player *omp.Player, weather int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetWeather(player.Handle(), weather)
}

// GetWeather wraps CAPI Player_GetWeather
func GetWeather(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetWeather(player.Handle())
}

// SetSkin wraps CAPI Player_SetSkin
func SetSkin(player *omp.Player, skin int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetSkin(player.Handle(), skin)
}

// SetShopName wraps CAPI Player_SetShopName
func SetShopName(player *omp.Player, name string) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetShopName(player.Handle(), name)
}

// GiveMoney wraps CAPI Player_GiveMoney
func GiveMoney(player *omp.Player, amount int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GiveMoney(player.Handle(), amount)
}

// SetCameraLookAt wraps CAPI Player_SetCameraLookAt
func SetCameraLookAt(player *omp.Player, x float32, y float32, z float32, cutType int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetCameraLookAt(player.Handle(), x, y, z, cutType)
}

// SetCameraBehind wraps CAPI Player_SetCameraBehind
func SetCameraBehind(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetCameraBehind(player.Handle())
}

// CreateExplosion wraps CAPI Player_CreateExplosion
func CreateExplosion(player *omp.Player, x float32, y float32, z float32, typ int32, radius float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_CreateExplosion(player.Handle(), x, y, z, typ, radius)
}

// PlayAudioStream wraps CAPI Player_PlayAudioStream
func PlayAudioStream(player *omp.Player, url string, x float32, y float32, z float32, distance float32, usePos bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_PlayAudioStream(player.Handle(), url, x, y, z, distance, usePos)
}

// StopAudioStream wraps CAPI Player_StopAudioStream
func StopAudioStream(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_StopAudioStream(player.Handle())
}

// ToggleWidescreen wraps CAPI Player_ToggleWidescreen
func ToggleWidescreen(player *omp.Player, enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ToggleWidescreen(player.Handle(), enable)
}

// IsWidescreenToggled wraps CAPI Player_IsWidescreenToggled
func IsWidescreenToggled(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsWidescreenToggled(player.Handle())
}

// SetHealth wraps CAPI Player_SetHealth
func SetHealth(player *omp.Player, health float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetHealth(player.Handle(), health)
}

// GetHealth wraps CAPI Player_GetHealth
func GetHealth(player *omp.Player) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetHealth(player.Handle())
}

// SetArmor wraps CAPI Player_SetArmor
func SetArmor(player *omp.Player, armor float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetArmor(player.Handle(), armor)
}

// GetArmor wraps CAPI Player_GetArmor
func GetArmor(player *omp.Player) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetArmor(player.Handle())
}

// SetTeam wraps CAPI Player_SetTeam
func SetTeam(player *omp.Player, team int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetTeam(player.Handle(), team)
}

// GetTeam wraps CAPI Player_GetTeam
func GetTeam(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetTeam(player.Handle())
}

// SetScore wraps CAPI Player_SetScore
func SetScore(player *omp.Player, score int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetScore(player.Handle(), score)
}

// GetScore wraps CAPI Player_GetScore
func GetScore(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetScore(player.Handle())
}

// GetSkin wraps CAPI Player_GetSkin
func GetSkin(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetSkin(player.Handle())
}

// SetColor wraps CAPI Player_SetColor
func SetColor(player *omp.Player, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetColor(player.Handle(), color)
}

// GetColor wraps CAPI Player_GetColor
func GetColor(player *omp.Player) uint32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetColor(player.Handle())
}

// GetDefaultColor wraps CAPI Player_GetDefaultColor
func GetDefaultColor(player *omp.Player) uint32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetDefaultColor(player.Handle())
}

// GetDrunkLevel wraps CAPI Player_GetDrunkLevel
func GetDrunkLevel(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetDrunkLevel(player.Handle())
}

// GiveWeapon wraps CAPI Player_GiveWeapon
func GiveWeapon(player *omp.Player, weapon int32, ammo int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GiveWeapon(player.Handle(), weapon, ammo)
}

// RemoveWeapon wraps CAPI Player_RemoveWeapon
func RemoveWeapon(player *omp.Player, weapon int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_RemoveWeapon(player.Handle(), weapon)
}

// GetMoney wraps CAPI Player_GetMoney
func GetMoney(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetMoney(player.Handle())
}

// ResetMoney wraps CAPI Player_ResetMoney
func ResetMoney(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ResetMoney(player.Handle())
}

// SetName wraps CAPI Player_SetName
func SetName(player *omp.Player, name string) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_SetName(player.Handle(), name)
}

// GetName wraps CAPI Player_GetName and returns a string.
func GetName(player *omp.Player) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Player_GetNameString(player.Handle())
}

// GetState wraps CAPI Player_GetState
func GetState(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetState(player.Handle())
}

// GetPing wraps CAPI Player_GetPing
func GetPing(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetPing(player.Handle())
}

// GetWeapon wraps CAPI Player_GetWeapon
func GetWeapon(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetWeapon(player.Handle())
}

// SetTime wraps CAPI Player_SetTime
func SetTime(player *omp.Player, hour int32, minute int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetTime(player.Handle(), hour, minute)
}

// GetTime wraps CAPI Player_GetTime
func GetTime(player *omp.Player, hour *int32, minute *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetTime(player.Handle(), hour, minute)
}

// ToggleClock wraps CAPI Player_ToggleClock
func ToggleClock(player *omp.Player, enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ToggleClock(player.Handle(), enable)
}

// HasClock wraps CAPI Player_HasClock
func HasClock(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_HasClock(player.Handle())
}

// ForceClassSelection wraps CAPI Player_ForceClassSelection
func ForceClassSelection(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ForceClassSelection(player.Handle())
}

// GetWantedLevel wraps CAPI Player_GetWantedLevel
func GetWantedLevel(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetWantedLevel(player.Handle())
}

// SetFightingStyle wraps CAPI Player_SetFightingStyle
func SetFightingStyle(player *omp.Player, style int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetFightingStyle(player.Handle(), style)
}

// GetFightingStyle wraps CAPI Player_GetFightingStyle
func GetFightingStyle(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetFightingStyle(player.Handle())
}

// SetVelocity wraps CAPI Player_SetVelocity
func SetVelocity(player *omp.Player, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetVelocity(player.Handle(), x, y, z)
}

// GetVelocity wraps CAPI Player_GetVelocity
func GetVelocity(player *omp.Player, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetVelocity(player.Handle(), x, y, z)
}

// GetCameraPos wraps CAPI Player_GetCameraPos
func GetCameraPos(player *omp.Player, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetCameraPos(player.Handle(), x, y, z)
}

// GetDistanceFromPoint wraps CAPI Player_GetDistanceFromPoint
func GetDistanceFromPoint(player *omp.Player, x float32, y float32, z float32) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetDistanceFromPoint(player.Handle(), x, y, z)
}

// GetInterior wraps CAPI Player_GetInterior
func GetInterior(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetInterior(player.Handle())
}

// SetPos wraps CAPI Player_SetPos
func SetPos(player *omp.Player, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetPos(player.Handle(), x, y, z)
}

// GetPos wraps CAPI Player_GetPos
func GetPos(player *omp.Player, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetPos(player.Handle(), x, y, z)
}

// GetVirtualWorld wraps CAPI Player_GetVirtualWorld
func GetVirtualWorld(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetVirtualWorld(player.Handle())
}

// IsNPC wraps CAPI Player_IsNPC
func IsNPC(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsNPC(player.Handle())
}

// IsStreamedIn wraps CAPI Player_IsStreamedIn
func IsStreamedIn(player *omp.Player, other *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsStreamedIn(player.Handle(), other.Handle())
}

// PlayGameSound wraps CAPI Player_PlayGameSound
func PlayGameSound(player *omp.Player, sound int32, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_PlayGameSound(player.Handle(), sound, x, y, z)
}

// SpectatePlayer wraps CAPI Player_SpectatePlayer
func SpectatePlayer(player *omp.Player, target *omp.Player, mode int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SpectatePlayer(player.Handle(), target.Handle(), mode)
}

// SpectateVehicle wraps CAPI Player_SpectateVehicle
func SpectateVehicle(player *omp.Player, target *omp.Vehicle, mode int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SpectateVehicle(player.Handle(), target.Handle(), mode)
}

// SetVirtualWorld wraps CAPI Player_SetVirtualWorld
func SetVirtualWorld(player *omp.Player, vw int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetVirtualWorld(player.Handle(), vw)
}

// SetWorldBounds wraps CAPI Player_SetWorldBounds
func SetWorldBounds(player *omp.Player, xMax float32, xMin float32, yMax float32, yMin float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetWorldBounds(player.Handle(), xMax, xMin, yMax, yMin)
}

// ClearWorldBounds wraps CAPI Player_ClearWorldBounds
func ClearWorldBounds(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ClearWorldBounds(player.Handle())
}

// GetWorldBounds wraps CAPI Player_GetWorldBounds
func GetWorldBounds(player *omp.Player, xmax *float32, xmin *float32, ymax *float32, ymin *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetWorldBounds(player.Handle(), xmax, xmin, ymax, ymin)
}

// ClearAnimations wraps CAPI Player_ClearAnimations
func ClearAnimations(player *omp.Player, syncType int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ClearAnimations(player.Handle(), syncType)
}

// GetLastShotVectors wraps CAPI Player_GetLastShotVectors
func GetLastShotVectors(player *omp.Player, originX *float32, originY *float32, originZ *float32, hitX *float32, hitY *float32, hitZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetLastShotVectors(player.Handle(), originX, originY, originZ, hitX, hitY, hitZ)
}

// GetCameraTargetPlayer wraps CAPI Player_GetCameraTargetPlayer
func GetCameraTargetPlayer(player *omp.Player) *omp.Player {
	c := runtime.Instance().CAPI()
	res := c.Player_GetCameraTargetPlayer(player.Handle())
	return omp.NewPlayer(res)
}

// GetCameraTargetActor wraps CAPI Player_GetCameraTargetActor
func GetCameraTargetActor(player *omp.Player) *omp.Actor {
	c := runtime.Instance().CAPI()
	res := c.Player_GetCameraTargetActor(player.Handle())
	return omp.NewActor(res)
}

// GetCameraTargetObject wraps CAPI Player_GetCameraTargetObject
func GetCameraTargetObject(player *omp.Player) *omp.Object {
	c := runtime.Instance().CAPI()
	res := c.Player_GetCameraTargetObject(player.Handle())
	return omp.NewObject(res)
}

// GetCameraTargetVehicle wraps CAPI Player_GetCameraTargetVehicle
func GetCameraTargetVehicle(player *omp.Player) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Player_GetCameraTargetVehicle(player.Handle())
	return omp.NewVehicle(res)
}

// PutInVehicle wraps CAPI Player_PutInVehicle
func PutInVehicle(player *omp.Player, vehicle *omp.Vehicle, seat int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_PutInVehicle(player.Handle(), vehicle.Handle(), seat)
}

// RemoveBuilding wraps CAPI Player_RemoveBuilding
func RemoveBuilding(player *omp.Player, model int32, x float32, y float32, z float32, radius float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_RemoveBuilding(player.Handle(), model, x, y, z, radius)
}

// GetBuildingsRemoved wraps CAPI Player_GetBuildingsRemoved
func GetBuildingsRemoved(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetBuildingsRemoved(player.Handle())
}

// RemoveFromVehicle wraps CAPI Player_RemoveFromVehicle
func RemoveFromVehicle(player *omp.Player, force bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_RemoveFromVehicle(player.Handle(), force)
}

// RemoveMapIcon wraps CAPI Player_RemoveMapIcon
func RemoveMapIcon(player *omp.Player, icon int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_RemoveMapIcon(player.Handle(), icon)
}

// SetMapIcon wraps CAPI Player_SetMapIcon
func SetMapIcon(player *omp.Player, iconID int32, x float32, y float32, z float32, typ int32, color uint32, style int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetMapIcon(player.Handle(), iconID, x, y, z, typ, color, style)
}

// ResetWeapons wraps CAPI Player_ResetWeapons
func ResetWeapons(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ResetWeapons(player.Handle())
}

// SetAmmo wraps CAPI Player_SetAmmo
func SetAmmo(player *omp.Player, id uint8, ammo uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetAmmo(player.Handle(), id, ammo)
}

// SetArmedWeapon wraps CAPI Player_SetArmedWeapon
func SetArmedWeapon(player *omp.Player, weapon uint8) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetArmedWeapon(player.Handle(), weapon)
}

// SetChatBubble wraps CAPI Player_SetChatBubble
func SetChatBubble(player *omp.Player, text string, color uint32, drawdistance float32, expiretime int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetChatBubble(player.Handle(), text, color, drawdistance, expiretime)
}

// SetPosFindZ wraps CAPI Player_SetPosFindZ
func SetPosFindZ(player *omp.Player, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetPosFindZ(player.Handle(), x, y, z)
}

// SetSkillLevel wraps CAPI Player_SetSkillLevel
func SetSkillLevel(player *omp.Player, weapon uint8, level int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetSkillLevel(player.Handle(), weapon, level)
}

// SetSpecialAction wraps CAPI Player_SetSpecialAction
func SetSpecialAction(player *omp.Player, action uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetSpecialAction(player.Handle(), action)
}

// ShowNameTagForPlayer wraps CAPI Player_ShowNameTagForPlayer
func ShowNameTagForPlayer(player *omp.Player, other *omp.Player, enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ShowNameTagForPlayer(player.Handle(), other.Handle(), enable)
}

// ToggleControllable wraps CAPI Player_ToggleControllable
func ToggleControllable(player *omp.Player, enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ToggleControllable(player.Handle(), enable)
}

// ToggleSpectating wraps CAPI Player_ToggleSpectating
func ToggleSpectating(player *omp.Player, enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ToggleSpectating(player.Handle(), enable)
}

// ApplyAnimation wraps CAPI Player_ApplyAnimation
func ApplyAnimation(player *omp.Player, animlib string, animname string, delta float32, loop bool, lockX bool, lockY bool, freeze bool, time uint32, sync int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ApplyAnimation(player.Handle(), animlib, animname, delta, loop, lockX, lockY, freeze, time, sync)
}

// GetAnimationName wraps CAPI Player_GetAnimationName
func GetAnimationName(index int32, lib *string, name *string) bool {
	c := runtime.Instance().CAPI()
	var libView runtime.CAPIStringView
	var nameView runtime.CAPIStringView
	res := c.Player_GetAnimationName(index, &libView, &nameView)
	if lib != nil {
		*lib = runtime.CAPIStringViewToString(&libView)
	}
	if name != nil {
		*name = runtime.CAPIStringViewToString(&nameView)
	}
	return res
}

// EditAttachedObject wraps CAPI Player_EditAttachedObject
func EditAttachedObject(player *omp.Player, index int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_EditAttachedObject(player.Handle(), index)
}

// EnableCameraTarget wraps CAPI Player_EnableCameraTarget
func EnableCameraTarget(player *omp.Player, enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_EnableCameraTarget(player.Handle(), enable)
}

// EnableStuntBonus wraps CAPI Player_EnableStuntBonus
func EnableStuntBonus(player *omp.Player, enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_EnableStuntBonus(player.Handle(), enable)
}

// GetPlayerAmmo wraps CAPI Player_GetPlayerAmmo
func GetPlayerAmmo(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetPlayerAmmo(player.Handle())
}

// GetAnimationIndex wraps CAPI Player_GetAnimationIndex
func GetAnimationIndex(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetAnimationIndex(player.Handle())
}

// GetFacingAngle wraps CAPI Player_GetFacingAngle
func GetFacingAngle(player *omp.Player) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetFacingAngle(player.Handle())
}

// GetIPString wraps CAPI Player_GetIp and returns a string.
func GetIPString(player *omp.Player) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Player_GetIpString(player.Handle())
}

// GetSpecialAction wraps CAPI Player_GetSpecialAction
func GetSpecialAction(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetSpecialAction(player.Handle())
}

// GetVehicleID wraps CAPI Player_GetVehicleID
func GetVehicleID(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetVehicleID(player.Handle())
}

// GetVehicleSeat wraps CAPI Player_GetVehicleSeat
func GetVehicleSeat(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetVehicleSeat(player.Handle())
}

// GetWeaponData wraps CAPI Player_GetWeaponData
func GetWeaponData(player *omp.Player, slot int32, weaponid *int32, ammo *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetWeaponData(player.Handle(), slot, weaponid, ammo)
}

// GetWeaponState wraps CAPI Player_GetWeaponState
func GetWeaponState(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetWeaponState(player.Handle())
}

// InterpolateCameraPos wraps CAPI Player_InterpolateCameraPos
func InterpolateCameraPos(player *omp.Player, fromX float32, fromY float32, fromZ float32, toX float32, toY float32, toZ float32, time int32, cut int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_InterpolateCameraPos(player.Handle(), fromX, fromY, fromZ, toX, toY, toZ, time, cut)
}

// InterpolateCameraLookAt wraps CAPI Player_InterpolateCameraLookAt
func InterpolateCameraLookAt(player *omp.Player, fromX float32, fromY float32, fromZ float32, toX float32, toY float32, toZ float32, time int32, cut int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_InterpolateCameraLookAt(player.Handle(), fromX, fromY, fromZ, toX, toY, toZ, time, cut)
}

// IsPlayerAttachedObjectSlotUsed wraps CAPI Player_IsPlayerAttachedObjectSlotUsed
func IsPlayerAttachedObjectSlotUsed(player *omp.Player, index int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsPlayerAttachedObjectSlotUsed(player.Handle(), index)
}

// AttachCameraToObject wraps CAPI Player_AttachCameraToObject
func AttachCameraToObject(player *omp.Player, object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Player_AttachCameraToObject(player.Handle(), object.Handle())
}

// AttachCameraToPlayerObject wraps CAPI Player_AttachCameraToPlayerObject
func AttachCameraToPlayerObject(player *omp.Player, object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Player_AttachCameraToPlayerObject(player.Handle(), object.Handle())
}

// GetCameraAspectRatio wraps CAPI Player_GetCameraAspectRatio
func GetCameraAspectRatio(player *omp.Player) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetCameraAspectRatio(player.Handle())
}

// GetCameraFrontVector wraps CAPI Player_GetCameraFrontVector
func GetCameraFrontVector(player *omp.Player, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetCameraFrontVector(player.Handle(), x, y, z)
}

// GetCameraMode wraps CAPI Player_GetCameraMode
func GetCameraMode(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetCameraMode(player.Handle())
}

// GetKeys wraps CAPI Player_GetKeys
func GetKeys(player *omp.Player, keys *int32, updown *int32, leftright *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetKeys(player.Handle(), keys, updown, leftright)
}

// GetSurfingVehicle wraps CAPI Player_GetSurfingVehicle
func GetSurfingVehicle(player *omp.Player) *omp.Vehicle {
	c := runtime.Instance().CAPI()
	res := c.Player_GetSurfingVehicle(player.Handle())
	return omp.NewVehicle(res)
}

// GetSurfingObject wraps CAPI Player_GetSurfingObject
func GetSurfingObject(player *omp.Player) *omp.Object {
	c := runtime.Instance().CAPI()
	res := c.Player_GetSurfingObject(player.Handle())
	return omp.NewObject(res)
}

// GetTargetPlayer wraps CAPI Player_GetTargetPlayer
func GetTargetPlayer(player *omp.Player) *omp.Player {
	c := runtime.Instance().CAPI()
	res := c.Player_GetTargetPlayer(player.Handle())
	return omp.NewPlayer(res)
}

// GetTargetActor wraps CAPI Player_GetTargetActor
func GetTargetActor(player *omp.Player) *omp.Actor {
	c := runtime.Instance().CAPI()
	res := c.Player_GetTargetActor(player.Handle())
	return omp.NewActor(res)
}

// IsInVehicle wraps CAPI Player_IsInVehicle
func IsInVehicle(player *omp.Player, targetVehicle *omp.Vehicle) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsInVehicle(player.Handle(), targetVehicle.Handle())
}

// IsInAnyVehicle wraps CAPI Player_IsInAnyVehicle
func IsInAnyVehicle(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsInAnyVehicle(player.Handle())
}

// IsInRangeOfPoint wraps CAPI Player_IsInRangeOfPoint
func IsInRangeOfPoint(player *omp.Player, rng float32, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsInRangeOfPoint(player.Handle(), rng, x, y, z)
}

// PlayCrimeReport wraps CAPI Player_PlayCrimeReport
func PlayCrimeReport(player *omp.Player, suspect *omp.Player, crime int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_PlayCrimeReport(player.Handle(), suspect.Handle(), crime)
}

// RemoveAttachedObject wraps CAPI Player_RemoveAttachedObject
func RemoveAttachedObject(player *omp.Player, index int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_RemoveAttachedObject(player.Handle(), index)
}

// SetAttachedObject wraps CAPI Player_SetAttachedObject
func SetAttachedObject(player *omp.Player, index int32, modelid int32, bone int32, offsetX float32, offsetY float32, offsetZ float32, rotationX float32, rotationY float32, rotationZ float32, scaleX float32, scaleY float32, scaleZ float32, materialcolor1 uint32, materialcolor2 uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetAttachedObject(player.Handle(), index, modelid, bone, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ, scaleX, scaleY, scaleZ, materialcolor1, materialcolor2)
}

// GetAttachedObject wraps CAPI Player_GetAttachedObject
func GetAttachedObject(player *omp.Player, index int32, modelid *int32, bone *int32, offsetX *float32, offsetY *float32, offsetZ *float32, rotationX *float32, rotationY *float32, rotationZ *float32, scaleX *float32, scaleY *float32, scaleZ *float32, materialcolor1 *int32, materialcolor2 *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetAttachedObject(player.Handle(), index, modelid, bone, offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ, scaleX, scaleY, scaleZ, materialcolor1, materialcolor2)
}

// SetFacingAngle wraps CAPI Player_SetFacingAngle
func SetFacingAngle(player *omp.Player, angle float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetFacingAngle(player.Handle(), angle)
}

// SetMarkerForPlayer wraps CAPI Player_SetMarkerForPlayer
func SetMarkerForPlayer(player *omp.Player, other *omp.Player, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetMarkerForPlayer(player.Handle(), other.Handle(), color)
}

// GetMarkerForPlayer wraps CAPI Player_GetMarkerForPlayer
func GetMarkerForPlayer(player *omp.Player, other *omp.Player) uint32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetMarkerForPlayer(player.Handle(), other.Handle())
}

// AllowTeleport wraps CAPI Player_AllowTeleport
func AllowTeleport(player *omp.Player, allow bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_AllowTeleport(player.Handle(), allow)
}

// IsTeleportAllowed wraps CAPI Player_IsTeleportAllowed
func IsTeleportAllowed(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsTeleportAllowed(player.Handle())
}

// DisableRemoteVehicleCollisions wraps CAPI Player_DisableRemoteVehicleCollisions
func DisableRemoteVehicleCollisions(player *omp.Player, disable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_DisableRemoteVehicleCollisions(player.Handle(), disable)
}

// GetCameraZoom wraps CAPI Player_GetCameraZoom
func GetCameraZoom(player *omp.Player) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetCameraZoom(player.Handle())
}

// SelectTextDraw wraps CAPI Player_SelectTextDraw
func SelectTextDraw(player *omp.Player, hoverColour uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SelectTextDraw(player.Handle(), hoverColour)
}

// CancelSelectTextDraw wraps CAPI Player_CancelSelectTextDraw
func CancelSelectTextDraw(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_CancelSelectTextDraw(player.Handle())
}

// SendClientCheck wraps CAPI Player_SendClientCheck
func SendClientCheck(player *omp.Player, actionType int32, address int32, offset int32, count int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SendClientCheck(player.Handle(), actionType, address, offset, count)
}

// Spawn wraps CAPI Player_Spawn
func Spawn(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_Spawn(player.Handle())
}

// GPCIString wraps CAPI Player_GPCI and returns a string.
func GPCIString(player *omp.Player) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Player_GPCIString(player.Handle())
}

// IsAdmin wraps CAPI Player_IsAdmin
func IsAdmin(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsAdmin(player.Handle())
}

// Kick wraps CAPI Player_Kick
func Kick(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_Kick(player.Handle())
}

// ShowGameText wraps CAPI Player_ShowGameText
func ShowGameText(player *omp.Player, text string, time int32, style int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ShowGameText(player.Handle(), text, time, style)
}

// HideGameText wraps CAPI Player_HideGameText
func HideGameText(player *omp.Player, style int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_HideGameText(player.Handle(), style)
}

// HasGameText wraps CAPI Player_HasGameText
func HasGameText(player *omp.Player, style int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_HasGameText(player.Handle(), style)
}

// GetGameText wraps CAPI Player_GetGameText
func GetGameText(player *omp.Player, style int32, message *string, time *int32, remaining *int32) bool {
	c := runtime.Instance().CAPI()
	var messageView runtime.CAPIStringView
	res := c.Player_GetGameText(player.Handle(), style, &messageView, time, remaining)
	if message != nil {
		*message = runtime.CAPIStringViewToString(&messageView)
	}
	return res
}

// Ban wraps CAPI Player_Ban
func Ban(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_Ban(player.Handle())
}

// BanEx wraps CAPI Player_BanEx
func BanEx(player *omp.Player, reason string) bool {
	c := runtime.Instance().CAPI()
	return c.Player_BanEx(player.Handle(), reason)
}

// SendDeathMessage wraps CAPI Player_SendDeathMessage
func SendDeathMessage(player *omp.Player, killer *omp.Player, killee *omp.Player, weapon int32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SendDeathMessage(player.Handle(), killer.Handle(), killee.Handle(), weapon)
}

// SendMessageToPlayer wraps CAPI Player_SendMessageToPlayer
func SendMessageToPlayer(player *omp.Player, sender *omp.Player, message string) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SendMessageToPlayer(player.Handle(), sender.Handle(), message)
}

// GetVersionString wraps CAPI Player_GetVersion and returns a string.
func GetVersionString(player *omp.Player) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Player_GetVersionString(player.Handle())
}

// GetSkillLevel wraps CAPI Player_GetSkillLevel
func GetSkillLevel(player *omp.Player, skill int32) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetSkillLevel(player.Handle(), skill)
}

// GetZAim wraps CAPI Player_GetZAim
func GetZAim(player *omp.Player) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetZAim(player.Handle())
}

// GetSurfingOffsets wraps CAPI Player_GetSurfingOffsets
func GetSurfingOffsets(player *omp.Player, offsetX *float32, offsetY *float32, offsetZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetSurfingOffsets(player.Handle(), offsetX, offsetY, offsetZ)
}

// GetRotationQuat wraps CAPI Player_GetRotationQuat
func GetRotationQuat(player *omp.Player, x *float32, y *float32, z *float32, w *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetRotationQuat(player.Handle(), x, y, z, w)
}

// GetPlayerSpectateID wraps CAPI Player_GetPlayerSpectateID
func GetPlayerSpectateID(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetPlayerSpectateID(player.Handle())
}

// GetSpectateType wraps CAPI Player_GetSpectateType
func GetSpectateType(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetSpectateType(player.Handle())
}

// GetRawIP wraps CAPI Player_GetRawIp
func GetRawIP(player *omp.Player) uint32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetRawIp(player.Handle())
}

// SetGravity wraps CAPI Player_SetGravity
func SetGravity(player *omp.Player, gravity float32) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetGravity(player.Handle(), gravity)
}

// GetGravity wraps CAPI Player_GetGravity
func GetGravity(player *omp.Player) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetGravity(player.Handle())
}

// SetAdmin wraps CAPI Player_SetAdmin
func SetAdmin(player *omp.Player, set bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_SetAdmin(player.Handle(), set)
}

// IsSpawned wraps CAPI Player_IsSpawned
func IsSpawned(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsSpawned(player.Handle())
}

// IsControllable wraps CAPI Player_IsControllable
func IsControllable(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsControllable(player.Handle())
}

// IsCameraTargetEnabled wraps CAPI Player_IsCameraTargetEnabled
func IsCameraTargetEnabled(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsCameraTargetEnabled(player.Handle())
}

// ToggleGhostMode wraps CAPI Player_ToggleGhostMode
func ToggleGhostMode(player *omp.Player, toggle bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_ToggleGhostMode(player.Handle(), toggle)
}

// GetGhostMode wraps CAPI Player_GetGhostMode
func GetGhostMode(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_GetGhostMode(player.Handle())
}

// AllowWeapons wraps CAPI Player_AllowWeapons
func AllowWeapons(player *omp.Player, allow bool) bool {
	c := runtime.Instance().CAPI()
	return c.Player_AllowWeapons(player.Handle(), allow)
}

// AreWeaponsAllowed wraps CAPI Player_AreWeaponsAllowed
func AreWeaponsAllowed(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_AreWeaponsAllowed(player.Handle())
}

// IsPlayerUsingOfficialClient wraps CAPI Player_IsPlayerUsingOfficialClient
func IsPlayerUsingOfficialClient(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsPlayerUsingOfficialClient(player.Handle())
}

// GetAnimationFlags wraps CAPI Player_GetAnimationFlags
func GetAnimationFlags(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetAnimationFlags(player.Handle())
}

// IsInDriveByMode wraps CAPI Player_IsInDriveByMode
func IsInDriveByMode(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsInDriveByMode(player.Handle())
}

// IsCuffed wraps CAPI Player_IsCuffed
func IsCuffed(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsCuffed(player.Handle())
}

// IsUsingOmp wraps CAPI Player_IsUsingOmp
func IsUsingOmp(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsUsingOmp(player.Handle())
}

// IsInModShop wraps CAPI Player_IsInModShop
func IsInModShop(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Player_IsInModShop(player.Handle())
}

// GetSirenState wraps CAPI Player_GetSirenState
func GetSirenState(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetSirenState(player.Handle())
}

// GetLandingGearState wraps CAPI Player_GetLandingGearState
func GetLandingGearState(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetLandingGearState(player.Handle())
}

// GetHydraReactorAngle wraps CAPI Player_GetHydraReactorAngle
func GetHydraReactorAngle(player *omp.Player) uint32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetHydraReactorAngle(player.Handle())
}

// GetTrainSpeed wraps CAPI Player_GetTrainSpeed
func GetTrainSpeed(player *omp.Player) float32 {
	c := runtime.Instance().CAPI()
	return c.Player_GetTrainSpeed(player.Handle())
}
