// Code generated by tools/codegen - DO NOT EDIT
package gangzone

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI GangZone_Create
func Create(minx float32, miny float32, maxx float32, maxy float32, id *int32) *omp.GangZone {
	c := runtime.Instance().CAPI()
	res := c.GangZone_Create(minx, miny, maxx, maxy, id)
	return omp.NewGangZone(res)
}

// Destroy wraps CAPI GangZone_Destroy
func Destroy(gangzone *omp.GangZone) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_Destroy(gangzone.Handle())
}

// FromID wraps CAPI GangZone_FromID
func FromID(gangzoneid int32) *omp.GangZone {
	c := runtime.Instance().CAPI()
	res := c.GangZone_FromID(gangzoneid)
	return omp.NewGangZone(res)
}

// GetID wraps CAPI GangZone_GetID
func GetID(gangzone *omp.GangZone) int32 {
	c := runtime.Instance().CAPI()
	return c.GangZone_GetID(gangzone.Handle())
}

// ShowForPlayer wraps CAPI GangZone_ShowForPlayer
func ShowForPlayer(player *omp.Player, gangzone *omp.GangZone, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_ShowForPlayer(player.Handle(), gangzone.Handle(), color)
}

// ShowForAll wraps CAPI GangZone_ShowForAll
func ShowForAll(gangzone *omp.GangZone, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_ShowForAll(gangzone.Handle(), color)
}

// HideForPlayer wraps CAPI GangZone_HideForPlayer
func HideForPlayer(player *omp.Player, gangzone *omp.GangZone) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_HideForPlayer(player.Handle(), gangzone.Handle())
}

// HideForAll wraps CAPI GangZone_HideForAll
func HideForAll(gangzone *omp.GangZone) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_HideForAll(gangzone.Handle())
}

// FlashForPlayer wraps CAPI GangZone_FlashForPlayer
func FlashForPlayer(player *omp.Player, gangzone *omp.GangZone, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_FlashForPlayer(player.Handle(), gangzone.Handle(), color)
}

// FlashForAll wraps CAPI GangZone_FlashForAll
func FlashForAll(gangzone *omp.GangZone, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_FlashForAll(gangzone.Handle(), color)
}

// StopFlashForPlayer wraps CAPI GangZone_StopFlashForPlayer
func StopFlashForPlayer(player *omp.Player, gangzone *omp.GangZone) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_StopFlashForPlayer(player.Handle(), gangzone.Handle())
}

// StopFlashForAll wraps CAPI GangZone_StopFlashForAll
func StopFlashForAll(gangzone *omp.GangZone) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_StopFlashForAll(gangzone.Handle())
}

// IsValid wraps CAPI GangZone_IsValid
func IsValid(gangzone *omp.GangZone) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_IsValid(gangzone.Handle())
}

// IsPlayerIn wraps CAPI GangZone_IsPlayerIn
func IsPlayerIn(player *omp.Player, gangzone *omp.GangZone) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_IsPlayerIn(player.Handle(), gangzone.Handle())
}

// IsVisibleForPlayer wraps CAPI GangZone_IsVisibleForPlayer
func IsVisibleForPlayer(player *omp.Player, gangzone *omp.GangZone) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_IsVisibleForPlayer(player.Handle(), gangzone.Handle())
}

// GetColorForPlayer wraps CAPI GangZone_GetColorForPlayer
func GetColorForPlayer(player *omp.Player, gangzone *omp.GangZone) int32 {
	c := runtime.Instance().CAPI()
	return c.GangZone_GetColorForPlayer(player.Handle(), gangzone.Handle())
}

// GetFlashColorForPlayer wraps CAPI GangZone_GetFlashColorForPlayer
func GetFlashColorForPlayer(player *omp.Player, gangzone *omp.GangZone) int32 {
	c := runtime.Instance().CAPI()
	return c.GangZone_GetFlashColorForPlayer(player.Handle(), gangzone.Handle())
}

// IsFlashingForPlayer wraps CAPI GangZone_IsFlashingForPlayer
func IsFlashingForPlayer(player *omp.Player, gangzone *omp.GangZone) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_IsFlashingForPlayer(player.Handle(), gangzone.Handle())
}

// GetPos wraps CAPI GangZone_GetPos
func GetPos(gangzone *omp.GangZone, minx *float32, miny *float32, maxx *float32, maxy *float32) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_GetPos(gangzone.Handle(), minx, miny, maxx, maxy)
}

// UseCheck wraps CAPI GangZone_UseCheck
func UseCheck(gangzone *omp.GangZone, enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.GangZone_UseCheck(gangzone.Handle(), enable)
}
