// Code generated by tools/codegen - DO NOT EDIT
package checkpoint

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Set wraps CAPI Checkpoint_Set
func Set(player *omp.Player, x float32, y float32, z float32, radius float32) bool {
	c := runtime.Instance().CAPI()
	return c.Checkpoint_Set(player.Handle(), x, y, z, radius)
}

// Disable wraps CAPI Checkpoint_Disable
func Disable(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Checkpoint_Disable(player.Handle())
}

// IsPlayerIn wraps CAPI Checkpoint_IsPlayerIn
func IsPlayerIn(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Checkpoint_IsPlayerIn(player.Handle())
}

// IsActive wraps CAPI Checkpoint_IsActive
func IsActive(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Checkpoint_IsActive(player.Handle())
}

// Get wraps CAPI Checkpoint_Get
func Get(player *omp.Player, x *float32, y *float32, z *float32, radius *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Checkpoint_Get(player.Handle(), x, y, z, radius)
}
