// Code generated by tools/codegen - DO NOT EDIT
package runtime

/*
#cgo CFLAGS: -I${SRCDIR}/include

#include <stdbool.h>
#include "ompcapi.h"

extern struct OMPAPI_t g_ompapi;
extern bool g_capi_initialised;

extern void OMPGO_OnPlayerGiveDamageActor(void* player, void* actor, float amount, int weapon, int part);
extern void OMPGO_OnActorStreamIn(void* actor, void* forPlayer);
extern void OMPGO_OnActorStreamOut(void* actor, void* forPlayer);
extern void OMPGO_OnPlayerEnterCheckpoint(void* player);
extern void OMPGO_OnPlayerLeaveCheckpoint(void* player);
extern void OMPGO_OnPlayerEnterRaceCheckpoint(void* player);
extern void OMPGO_OnPlayerLeaveRaceCheckpoint(void* player);
extern bool OMPGO_OnPlayerRequestClass(void* player, int classId);
extern bool OMPGO_OnConsoleText(struct CAPIStringView command, struct CAPIStringView parameters);
extern bool OMPGO_OnRconLoginAttempt(struct CAPIStringView address, struct CAPIStringView password, bool success);
extern void OMPGO_OnTick(int elapsed);
extern void OMPGO_OnPlayerFinishedDownloading(void* player, int vw);
extern void OMPGO_OnPlayerRequestDownload(void* player, int type, int checksum);
extern void OMPGO_OnDialogResponse(void* player, int dialogId, int response, int listItem, struct CAPIStringView inputText);
extern void OMPGO_OnPlayerEnterGangZone(void* player, void* zone);
extern void OMPGO_OnPlayerLeaveGangZone(void* player, void* zone);
extern void OMPGO_OnPlayerClickGangZone(void* player, void* zone);
extern void OMPGO_OnPlayerSelectedMenuRow(void* player, int row);
extern void OMPGO_OnPlayerExitedMenu(void* player);
extern void OMPGO_OnNPCFinishMove(void* npc);
extern void OMPGO_OnNPCCreate(void* npc);
extern void OMPGO_OnNPCDestroy(void* npc);
extern void OMPGO_OnNPCWeaponStateChange(void* npc, int newState, int oldState);
extern bool OMPGO_OnNPCTakeDamage(void* npc, void* damager, float damage, int weapon, int bodyPart);
extern bool OMPGO_OnNPCGiveDamage(void* npc, void* damaged, float damage, int weapon, int bodyPart);
extern void OMPGO_OnNPCDeath(void* npc, void* killer, int reason);
extern void OMPGO_OnNPCSpawn(void* npc);
extern void OMPGO_OnNPCRespawn(void* npc);
extern void OMPGO_OnNPCPlaybackStart(void* npc, int recordId);
extern void OMPGO_OnNPCPlaybackEnd(void* npc, int recordId);
extern bool OMPGO_OnNPCShotMissed(void* npc, int weapon, float offsetX, float offsetY, float offsetZ);
extern bool OMPGO_OnNPCShotPlayer(void* npc, void* player, int weapon, float offsetX, float offsetY, float offsetZ);
extern bool OMPGO_OnNPCShotNPC(void* npc, void* npcTarget, int weapon, float offsetX, float offsetY, float offsetZ);
extern bool OMPGO_OnNPCShotVehicle(void* npc, void* vehicle, int weapon, float offsetX, float offsetY, float offsetZ);
extern bool OMPGO_OnNPCShotObject(void* npc, void* object, int weapon, float offsetX, float offsetY, float offsetZ);
extern bool OMPGO_OnNPCShotPlayerObject(void* npc, void* playerObject, int weapon, float offsetX, float offsetY, float offsetZ);
extern void OMPGO_OnNPCFinishNodePoint(void* npc, int nodeId, int pointId);
extern void OMPGO_OnNPCFinishNode(void* npc, int nodeId);
extern bool OMPGO_OnNPCChangeNode(void* npc, int newNodeId, int oldNodeId);
extern void OMPGO_OnNPCFinishMovePath(void* npc, int pathId);
extern void OMPGO_OnNPCFinishMovePathPoint(void* npc, int pathId, int pointId);
extern void OMPGO_OnObjectMove(void* object);
extern void OMPGO_OnPlayerObjectMove(void* player, void* object);
extern void OMPGO_OnPlayerEditObject(void* player, void* object, int response, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ);
extern void OMPGO_OnPlayerEditPlayerObject(void* player, void* object, int response, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ);
extern void OMPGO_OnPlayerEditAttachedObject(void* player, bool saved, int index, int model, int bone, float offsetX, float offsetY, float offsetZ, float rotationX, float rotationY, float rotationZ, float scaleX, float scaleY, float scaleZ);
extern void OMPGO_OnPlayerSelectObject(void* player, void* object, int model, float x, float y, float z);
extern void OMPGO_OnPlayerSelectPlayerObject(void* player, void* object, int model, float x, float y, float z);
extern void OMPGO_OnPlayerPickUpPickup(void* player, void* pickup);
extern void OMPGO_OnPlayerConnect(void* player);
extern void OMPGO_OnPlayerSpawn(void* player);
extern bool OMPGO_OnPlayerCommandText(void* player, struct CAPIStringView command);
extern void OMPGO_OnPlayerKeyStateChange(void* player, int newKeys, int oldKeys);
extern void OMPGO_OnIncomingConnection(void* player, struct CAPIStringView ipAddress, int port);
extern void OMPGO_OnPlayerDisconnect(void* player, int reason);
extern bool OMPGO_OnPlayerRequestSpawn(void* player);
extern void OMPGO_OnPlayerStreamIn(void* player, void* forPlayer);
extern void OMPGO_OnPlayerStreamOut(void* player, void* forPlayer);
extern bool OMPGO_OnPlayerText(void* player, struct CAPIStringView text);
extern bool OMPGO_OnPlayerShotMissed(void* player, int weapon, float x, float y, float z);
extern bool OMPGO_OnPlayerShotPlayer(void* player, void* target, int weapon, float x, float y, float z);
extern bool OMPGO_OnPlayerShotVehicle(void* player, void* target, int weapon, float x, float y, float z);
extern bool OMPGO_OnPlayerShotObject(void* player, void* target, int weapon, float x, float y, float z);
extern bool OMPGO_OnPlayerShotPlayerObject(void* player, void* target, int weapon, float x, float y, float z);
extern void OMPGO_OnPlayerDeath(void* player, void* killer, int reason);
extern void OMPGO_OnPlayerTakeDamage(void* player, void* from, float amount, int weapon, int bodypart);
extern void OMPGO_OnPlayerGiveDamage(void* player, void* to, float amount, int weapon, int bodypart);
extern void OMPGO_OnPlayerInteriorChange(void* player, int newInterior, int oldInterior);
extern void OMPGO_OnPlayerStateChange(void* player, int newState, int oldState);
extern void OMPGO_OnPlayerClickMap(void* player, float x, float y, float z);
extern void OMPGO_OnPlayerClickPlayer(void* player, void* clicked, int source);
extern void OMPGO_OnClientCheckResponse(void* player, int actionType, int address, int result);
extern bool OMPGO_OnPlayerUpdate(void* player);
extern void OMPGO_OnPlayerCancelTextDrawSelection(void* player);
extern void OMPGO_OnPlayerCancelPlayerTextDrawSelection(void* player);
extern void OMPGO_OnPlayerClickTextDraw(void* player, void* textdraw);
extern void OMPGO_OnPlayerClickPlayerTextDraw(void* player, void* textdraw);
extern void OMPGO_OnVehicleStreamIn(void* vehicle, void* player);
extern void OMPGO_OnVehicleStreamOut(void* vehicle, void* player);
extern void OMPGO_OnVehicleDeath(void* vehicle, void* player);
extern void OMPGO_OnPlayerEnterVehicle(void* player, void* vehicle, bool passenger);
extern void OMPGO_OnPlayerExitVehicle(void* player, void* vehicle);
extern void OMPGO_OnVehicleDamageStatusUpdate(void* vehicle, void* player);
extern bool OMPGO_OnVehiclePaintJob(void* player, void* vehicle, int paintJob);
extern bool OMPGO_OnVehicleMod(void* player, void* vehicle, int component);
extern bool OMPGO_OnVehicleRespray(void* player, void* vehicle, int color1, int color2);
extern void OMPGO_OnEnterExitModShop(void* player, int enterexit, int interiorId);
extern void OMPGO_OnVehicleSpawn(void* vehicle);
extern bool OMPGO_OnUnoccupiedVehicleUpdate(void* vehicle, void* player, int seat, float posX, float posY, float posZ, float velocityX, float velocityY, float velocityZ);
extern bool OMPGO_OnTrailerUpdate(void* player, void* trailer);
extern bool OMPGO_OnVehicleSirenStateChange(void* player, void* vehicle, int sirenState);



static bool OnPlayerGiveDamageActor_handler(struct EventArgs_onPlayerGiveDamageActor* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerGiveDamageActor((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].actor ? *args->list[0].actor : NULL), (args->list[0].amount ? *args->list[0].amount : 0.0f), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].part ? *args->list[0].part : 0)); return true;
}


static bool OnActorStreamIn_handler(struct EventArgs_onActorStreamIn* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnActorStreamIn((args->list[0].actor ? *args->list[0].actor : NULL), (args->list[0].forPlayer ? *args->list[0].forPlayer : NULL)); return true;
}


static bool OnActorStreamOut_handler(struct EventArgs_onActorStreamOut* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnActorStreamOut((args->list[0].actor ? *args->list[0].actor : NULL), (args->list[0].forPlayer ? *args->list[0].forPlayer : NULL)); return true;
}


static bool OnPlayerEnterCheckpoint_handler(struct EventArgs_onPlayerEnterCheckpoint* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerEnterCheckpoint((args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnPlayerLeaveCheckpoint_handler(struct EventArgs_onPlayerLeaveCheckpoint* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerLeaveCheckpoint((args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnPlayerEnterRaceCheckpoint_handler(struct EventArgs_onPlayerEnterRaceCheckpoint* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerEnterRaceCheckpoint((args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnPlayerLeaveRaceCheckpoint_handler(struct EventArgs_onPlayerLeaveRaceCheckpoint* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerLeaveRaceCheckpoint((args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnPlayerRequestClass_handler(struct EventArgs_onPlayerRequestClass* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerRequestClass((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].classId ? *args->list[0].classId : 0));
}


static bool OnConsoleText_handler(struct EventArgs_onConsoleText* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnConsoleText((args->list[0].command ? *args->list[0].command : (struct CAPIStringView){0, NULL}), (args->list[0].parameters ? *args->list[0].parameters : (struct CAPIStringView){0, NULL}));
}


static bool OnRconLoginAttempt_handler(struct EventArgs_onRconLoginAttempt* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnRconLoginAttempt((args->list[0].address ? *args->list[0].address : (struct CAPIStringView){0, NULL}), (args->list[0].password ? *args->list[0].password : (struct CAPIStringView){0, NULL}), (args->list[0].success ? *args->list[0].success : false));
}


static bool OnTick_handler(struct EventArgs_onTick* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnTick((args->list[0].elapsed ? *args->list[0].elapsed : 0)); return true;
}


static bool OnPlayerFinishedDownloading_handler(struct EventArgs_onPlayerFinishedDownloading* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerFinishedDownloading((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].vw ? *args->list[0].vw : 0)); return true;
}


static bool OnPlayerRequestDownload_handler(struct EventArgs_onPlayerRequestDownload* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerRequestDownload((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].type ? *args->list[0].type : 0), (args->list[0].checksum ? *args->list[0].checksum : 0)); return true;
}


static bool OnDialogResponse_handler(struct EventArgs_onDialogResponse* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnDialogResponse((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].dialogId ? *args->list[0].dialogId : 0), (args->list[0].response ? *args->list[0].response : 0), (args->list[0].listItem ? *args->list[0].listItem : 0), (args->list[0].inputText ? *args->list[0].inputText : (struct CAPIStringView){0, NULL})); return true;
}


static bool OnPlayerEnterGangZone_handler(struct EventArgs_onPlayerEnterGangZone* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerEnterGangZone((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].zone ? *args->list[0].zone : NULL)); return true;
}


static bool OnPlayerLeaveGangZone_handler(struct EventArgs_onPlayerLeaveGangZone* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerLeaveGangZone((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].zone ? *args->list[0].zone : NULL)); return true;
}


static bool OnPlayerClickGangZone_handler(struct EventArgs_onPlayerClickGangZone* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerClickGangZone((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].zone ? *args->list[0].zone : NULL)); return true;
}


static bool OnPlayerSelectedMenuRow_handler(struct EventArgs_onPlayerSelectedMenuRow* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerSelectedMenuRow((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].row ? *args->list[0].row : 0)); return true;
}


static bool OnPlayerExitedMenu_handler(struct EventArgs_onPlayerExitedMenu* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerExitedMenu((args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnNPCFinishMove_handler(struct EventArgs_onNPCFinishMove* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCFinishMove((args->list[0].npc ? *args->list[0].npc : NULL)); return true;
}


static bool OnNPCCreate_handler(struct EventArgs_onNPCCreate* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCCreate((args->list[0].npc ? *args->list[0].npc : NULL)); return true;
}


static bool OnNPCDestroy_handler(struct EventArgs_onNPCDestroy* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCDestroy((args->list[0].npc ? *args->list[0].npc : NULL)); return true;
}


static bool OnNPCWeaponStateChange_handler(struct EventArgs_onNPCWeaponStateChange* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCWeaponStateChange((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].newState ? *args->list[0].newState : 0), (args->list[0].oldState ? *args->list[0].oldState : 0)); return true;
}


static bool OnNPCTakeDamage_handler(struct EventArgs_onNPCTakeDamage* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnNPCTakeDamage((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].damager ? *args->list[0].damager : NULL), (args->list[0].damage ? *args->list[0].damage : 0.0f), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].bodyPart ? *args->list[0].bodyPart : 0));
}


static bool OnNPCGiveDamage_handler(struct EventArgs_onNPCGiveDamage* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnNPCGiveDamage((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].damaged ? *args->list[0].damaged : NULL), (args->list[0].damage ? *args->list[0].damage : 0.0f), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].bodyPart ? *args->list[0].bodyPart : 0));
}


static bool OnNPCDeath_handler(struct EventArgs_onNPCDeath* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCDeath((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].killer ? *args->list[0].killer : NULL), (args->list[0].reason ? *args->list[0].reason : 0)); return true;
}


static bool OnNPCSpawn_handler(struct EventArgs_onNPCSpawn* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCSpawn((args->list[0].npc ? *args->list[0].npc : NULL)); return true;
}


static bool OnNPCRespawn_handler(struct EventArgs_onNPCRespawn* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCRespawn((args->list[0].npc ? *args->list[0].npc : NULL)); return true;
}


static bool OnNPCPlaybackStart_handler(struct EventArgs_onNPCPlaybackStart* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCPlaybackStart((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].recordId ? *args->list[0].recordId : 0)); return true;
}


static bool OnNPCPlaybackEnd_handler(struct EventArgs_onNPCPlaybackEnd* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCPlaybackEnd((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].recordId ? *args->list[0].recordId : 0)); return true;
}


static bool OnNPCShotMissed_handler(struct EventArgs_onNPCShotMissed* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnNPCShotMissed((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].offsetX ? *args->list[0].offsetX : 0.0f), (args->list[0].offsetY ? *args->list[0].offsetY : 0.0f), (args->list[0].offsetZ ? *args->list[0].offsetZ : 0.0f));
}


static bool OnNPCShotPlayer_handler(struct EventArgs_onNPCShotPlayer* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnNPCShotPlayer((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].player ? *args->list[0].player : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].offsetX ? *args->list[0].offsetX : 0.0f), (args->list[0].offsetY ? *args->list[0].offsetY : 0.0f), (args->list[0].offsetZ ? *args->list[0].offsetZ : 0.0f));
}


static bool OnNPCShotNPC_handler(struct EventArgs_onNPCShotNPC* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnNPCShotNPC((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].npcTarget ? *args->list[0].npcTarget : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].offsetX ? *args->list[0].offsetX : 0.0f), (args->list[0].offsetY ? *args->list[0].offsetY : 0.0f), (args->list[0].offsetZ ? *args->list[0].offsetZ : 0.0f));
}


static bool OnNPCShotVehicle_handler(struct EventArgs_onNPCShotVehicle* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnNPCShotVehicle((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].offsetX ? *args->list[0].offsetX : 0.0f), (args->list[0].offsetY ? *args->list[0].offsetY : 0.0f), (args->list[0].offsetZ ? *args->list[0].offsetZ : 0.0f));
}


static bool OnNPCShotObject_handler(struct EventArgs_onNPCShotObject* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnNPCShotObject((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].object ? *args->list[0].object : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].offsetX ? *args->list[0].offsetX : 0.0f), (args->list[0].offsetY ? *args->list[0].offsetY : 0.0f), (args->list[0].offsetZ ? *args->list[0].offsetZ : 0.0f));
}


static bool OnNPCShotPlayerObject_handler(struct EventArgs_onNPCShotPlayerObject* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnNPCShotPlayerObject((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].playerObject ? *args->list[0].playerObject : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].offsetX ? *args->list[0].offsetX : 0.0f), (args->list[0].offsetY ? *args->list[0].offsetY : 0.0f), (args->list[0].offsetZ ? *args->list[0].offsetZ : 0.0f));
}


static bool OnNPCFinishNodePoint_handler(struct EventArgs_onNPCFinishNodePoint* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCFinishNodePoint((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].nodeId ? *args->list[0].nodeId : 0), (args->list[0].pointId ? *args->list[0].pointId : 0)); return true;
}


static bool OnNPCFinishNode_handler(struct EventArgs_onNPCFinishNode* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCFinishNode((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].nodeId ? *args->list[0].nodeId : 0)); return true;
}


static bool OnNPCChangeNode_handler(struct EventArgs_onNPCChangeNode* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnNPCChangeNode((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].newNodeId ? *args->list[0].newNodeId : 0), (args->list[0].oldNodeId ? *args->list[0].oldNodeId : 0));
}


static bool OnNPCFinishMovePath_handler(struct EventArgs_onNPCFinishMovePath* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCFinishMovePath((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].pathId ? *args->list[0].pathId : 0)); return true;
}


static bool OnNPCFinishMovePathPoint_handler(struct EventArgs_onNPCFinishMovePathPoint* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnNPCFinishMovePathPoint((args->list[0].npc ? *args->list[0].npc : NULL), (args->list[0].pathId ? *args->list[0].pathId : 0), (args->list[0].pointId ? *args->list[0].pointId : 0)); return true;
}


static bool OnObjectMove_handler(struct EventArgs_onObjectMove* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnObjectMove((args->list[0].object ? *args->list[0].object : NULL)); return true;
}


static bool OnPlayerObjectMove_handler(struct EventArgs_onPlayerObjectMove* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerObjectMove((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].object ? *args->list[0].object : NULL)); return true;
}


static bool OnPlayerEditObject_handler(struct EventArgs_onPlayerEditObject* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerEditObject((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].object ? *args->list[0].object : NULL), (args->list[0].response ? *args->list[0].response : 0), (args->list[0].offsetX ? *args->list[0].offsetX : 0.0f), (args->list[0].offsetY ? *args->list[0].offsetY : 0.0f), (args->list[0].offsetZ ? *args->list[0].offsetZ : 0.0f), (args->list[0].rotationX ? *args->list[0].rotationX : 0.0f), (args->list[0].rotationY ? *args->list[0].rotationY : 0.0f), (args->list[0].rotationZ ? *args->list[0].rotationZ : 0.0f)); return true;
}


static bool OnPlayerEditPlayerObject_handler(struct EventArgs_onPlayerEditPlayerObject* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerEditPlayerObject((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].object ? *args->list[0].object : NULL), (args->list[0].response ? *args->list[0].response : 0), (args->list[0].offsetX ? *args->list[0].offsetX : 0.0f), (args->list[0].offsetY ? *args->list[0].offsetY : 0.0f), (args->list[0].offsetZ ? *args->list[0].offsetZ : 0.0f), (args->list[0].rotationX ? *args->list[0].rotationX : 0.0f), (args->list[0].rotationY ? *args->list[0].rotationY : 0.0f), (args->list[0].rotationZ ? *args->list[0].rotationZ : 0.0f)); return true;
}


static bool OnPlayerEditAttachedObject_handler(struct EventArgs_onPlayerEditAttachedObject* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerEditAttachedObject((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].saved ? *args->list[0].saved : false), (args->list[0].index ? *args->list[0].index : 0), (args->list[0].model ? *args->list[0].model : 0), (args->list[0].bone ? *args->list[0].bone : 0), (args->list[0].offsetX ? *args->list[0].offsetX : 0.0f), (args->list[0].offsetY ? *args->list[0].offsetY : 0.0f), (args->list[0].offsetZ ? *args->list[0].offsetZ : 0.0f), (args->list[0].rotationX ? *args->list[0].rotationX : 0.0f), (args->list[0].rotationY ? *args->list[0].rotationY : 0.0f), (args->list[0].rotationZ ? *args->list[0].rotationZ : 0.0f), (args->list[0].scaleX ? *args->list[0].scaleX : 0.0f), (args->list[0].scaleY ? *args->list[0].scaleY : 0.0f), (args->list[0].scaleZ ? *args->list[0].scaleZ : 0.0f)); return true;
}


static bool OnPlayerSelectObject_handler(struct EventArgs_onPlayerSelectObject* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerSelectObject((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].object ? *args->list[0].object : NULL), (args->list[0].model ? *args->list[0].model : 0), (args->list[0].x ? *args->list[0].x : 0.0f), (args->list[0].y ? *args->list[0].y : 0.0f), (args->list[0].z ? *args->list[0].z : 0.0f)); return true;
}


static bool OnPlayerSelectPlayerObject_handler(struct EventArgs_onPlayerSelectPlayerObject* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerSelectPlayerObject((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].object ? *args->list[0].object : NULL), (args->list[0].model ? *args->list[0].model : 0), (args->list[0].x ? *args->list[0].x : 0.0f), (args->list[0].y ? *args->list[0].y : 0.0f), (args->list[0].z ? *args->list[0].z : 0.0f)); return true;
}


static bool OnPlayerPickUpPickup_handler(struct EventArgs_onPlayerPickUpPickup* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerPickUpPickup((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].pickup ? *args->list[0].pickup : NULL)); return true;
}


static bool OnPlayerConnect_handler(struct EventArgs_onPlayerConnect* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerConnect((args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnPlayerSpawn_handler(struct EventArgs_onPlayerSpawn* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerSpawn((args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnPlayerCommandText_handler(struct EventArgs_onPlayerCommandText* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerCommandText((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].command ? *args->list[0].command : (struct CAPIStringView){0, NULL}));
}


static bool OnPlayerKeyStateChange_handler(struct EventArgs_onPlayerKeyStateChange* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerKeyStateChange((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].newKeys ? *args->list[0].newKeys : 0), (args->list[0].oldKeys ? *args->list[0].oldKeys : 0)); return true;
}


static bool OnIncomingConnection_handler(struct EventArgs_onIncomingConnection* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnIncomingConnection((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].ipAddress ? *args->list[0].ipAddress : (struct CAPIStringView){0, NULL}), (args->list[0].port ? *args->list[0].port : 0)); return true;
}


static bool OnPlayerDisconnect_handler(struct EventArgs_onPlayerDisconnect* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerDisconnect((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].reason ? *args->list[0].reason : 0)); return true;
}


static bool OnPlayerRequestSpawn_handler(struct EventArgs_onPlayerRequestSpawn* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerRequestSpawn((args->list[0].player ? *args->list[0].player : NULL));
}


static bool OnPlayerStreamIn_handler(struct EventArgs_onPlayerStreamIn* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerStreamIn((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].forPlayer ? *args->list[0].forPlayer : NULL)); return true;
}


static bool OnPlayerStreamOut_handler(struct EventArgs_onPlayerStreamOut* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerStreamOut((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].forPlayer ? *args->list[0].forPlayer : NULL)); return true;
}


static bool OnPlayerText_handler(struct EventArgs_onPlayerText* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerText((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].text ? *args->list[0].text : (struct CAPIStringView){0, NULL}));
}


static bool OnPlayerShotMissed_handler(struct EventArgs_onPlayerShotMissed* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerShotMissed((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].x ? *args->list[0].x : 0.0f), (args->list[0].y ? *args->list[0].y : 0.0f), (args->list[0].z ? *args->list[0].z : 0.0f));
}


static bool OnPlayerShotPlayer_handler(struct EventArgs_onPlayerShotPlayer* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerShotPlayer((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].target ? *args->list[0].target : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].x ? *args->list[0].x : 0.0f), (args->list[0].y ? *args->list[0].y : 0.0f), (args->list[0].z ? *args->list[0].z : 0.0f));
}


static bool OnPlayerShotVehicle_handler(struct EventArgs_onPlayerShotVehicle* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerShotVehicle((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].target ? *args->list[0].target : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].x ? *args->list[0].x : 0.0f), (args->list[0].y ? *args->list[0].y : 0.0f), (args->list[0].z ? *args->list[0].z : 0.0f));
}


static bool OnPlayerShotObject_handler(struct EventArgs_onPlayerShotObject* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerShotObject((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].target ? *args->list[0].target : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].x ? *args->list[0].x : 0.0f), (args->list[0].y ? *args->list[0].y : 0.0f), (args->list[0].z ? *args->list[0].z : 0.0f));
}


static bool OnPlayerShotPlayerObject_handler(struct EventArgs_onPlayerShotPlayerObject* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerShotPlayerObject((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].target ? *args->list[0].target : NULL), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].x ? *args->list[0].x : 0.0f), (args->list[0].y ? *args->list[0].y : 0.0f), (args->list[0].z ? *args->list[0].z : 0.0f));
}


static bool OnPlayerDeath_handler(struct EventArgs_onPlayerDeath* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerDeath((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].killer ? *args->list[0].killer : NULL), (args->list[0].reason ? *args->list[0].reason : 0)); return true;
}


static bool OnPlayerTakeDamage_handler(struct EventArgs_onPlayerTakeDamage* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerTakeDamage((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].from ? *args->list[0].from : NULL), (args->list[0].amount ? *args->list[0].amount : 0.0f), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].bodypart ? *args->list[0].bodypart : 0)); return true;
}


static bool OnPlayerGiveDamage_handler(struct EventArgs_onPlayerGiveDamage* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerGiveDamage((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].to ? *args->list[0].to : NULL), (args->list[0].amount ? *args->list[0].amount : 0.0f), (args->list[0].weapon ? *args->list[0].weapon : 0), (args->list[0].bodypart ? *args->list[0].bodypart : 0)); return true;
}


static bool OnPlayerInteriorChange_handler(struct EventArgs_onPlayerInteriorChange* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerInteriorChange((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].newInterior ? *args->list[0].newInterior : 0), (args->list[0].oldInterior ? *args->list[0].oldInterior : 0)); return true;
}


static bool OnPlayerStateChange_handler(struct EventArgs_onPlayerStateChange* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerStateChange((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].newState ? *args->list[0].newState : 0), (args->list[0].oldState ? *args->list[0].oldState : 0)); return true;
}


static bool OnPlayerClickMap_handler(struct EventArgs_onPlayerClickMap* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerClickMap((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].x ? *args->list[0].x : 0.0f), (args->list[0].y ? *args->list[0].y : 0.0f), (args->list[0].z ? *args->list[0].z : 0.0f)); return true;
}


static bool OnPlayerClickPlayer_handler(struct EventArgs_onPlayerClickPlayer* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerClickPlayer((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].clicked ? *args->list[0].clicked : NULL), (args->list[0].source ? *args->list[0].source : 0)); return true;
}


static bool OnClientCheckResponse_handler(struct EventArgs_onClientCheckResponse* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnClientCheckResponse((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].actionType ? *args->list[0].actionType : 0), (args->list[0].address ? *args->list[0].address : 0), (args->list[0].result ? *args->list[0].result : 0)); return true;
}


static bool OnPlayerUpdate_handler(struct EventArgs_onPlayerUpdate* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnPlayerUpdate((args->list[0].player ? *args->list[0].player : NULL));
}


static bool OnPlayerCancelTextDrawSelection_handler(struct EventArgs_onPlayerCancelTextDrawSelection* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerCancelTextDrawSelection((args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnPlayerCancelPlayerTextDrawSelection_handler(struct EventArgs_onPlayerCancelPlayerTextDrawSelection* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerCancelPlayerTextDrawSelection((args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnPlayerClickTextDraw_handler(struct EventArgs_onPlayerClickTextDraw* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerClickTextDraw((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].textdraw ? *args->list[0].textdraw : NULL)); return true;
}


static bool OnPlayerClickPlayerTextDraw_handler(struct EventArgs_onPlayerClickPlayerTextDraw* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerClickPlayerTextDraw((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].textdraw ? *args->list[0].textdraw : NULL)); return true;
}


static bool OnVehicleStreamIn_handler(struct EventArgs_onVehicleStreamIn* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnVehicleStreamIn((args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnVehicleStreamOut_handler(struct EventArgs_onVehicleStreamOut* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnVehicleStreamOut((args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnVehicleDeath_handler(struct EventArgs_onVehicleDeath* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnVehicleDeath((args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnPlayerEnterVehicle_handler(struct EventArgs_onPlayerEnterVehicle* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerEnterVehicle((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].passenger ? *args->list[0].passenger : false)); return true;
}


static bool OnPlayerExitVehicle_handler(struct EventArgs_onPlayerExitVehicle* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnPlayerExitVehicle((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].vehicle ? *args->list[0].vehicle : NULL)); return true;
}


static bool OnVehicleDamageStatusUpdate_handler(struct EventArgs_onVehicleDamageStatusUpdate* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnVehicleDamageStatusUpdate((args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].player ? *args->list[0].player : NULL)); return true;
}


static bool OnVehiclePaintJob_handler(struct EventArgs_onVehiclePaintJob* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnVehiclePaintJob((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].paintJob ? *args->list[0].paintJob : 0));
}


static bool OnVehicleMod_handler(struct EventArgs_onVehicleMod* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnVehicleMod((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].component ? *args->list[0].component : 0));
}


static bool OnVehicleRespray_handler(struct EventArgs_onVehicleRespray* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnVehicleRespray((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].color1 ? *args->list[0].color1 : 0), (args->list[0].color2 ? *args->list[0].color2 : 0));
}


static bool OnEnterExitModShop_handler(struct EventArgs_onEnterExitModShop* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnEnterExitModShop((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].enterexit ? *args->list[0].enterexit : 0), (args->list[0].interiorId ? *args->list[0].interiorId : 0)); return true;
}


static bool OnVehicleSpawn_handler(struct EventArgs_onVehicleSpawn* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return true;
	}
	OMPGO_OnVehicleSpawn((args->list[0].vehicle ? *args->list[0].vehicle : NULL)); return true;
}


static bool OnUnoccupiedVehicleUpdate_handler(struct EventArgs_onUnoccupiedVehicleUpdate* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnUnoccupiedVehicleUpdate((args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].player ? *args->list[0].player : NULL), (args->list[0].seat ? *args->list[0].seat : 0), (args->list[0].posX ? *args->list[0].posX : 0.0f), (args->list[0].posY ? *args->list[0].posY : 0.0f), (args->list[0].posZ ? *args->list[0].posZ : 0.0f), (args->list[0].velocityX ? *args->list[0].velocityX : 0.0f), (args->list[0].velocityY ? *args->list[0].velocityY : 0.0f), (args->list[0].velocityZ ? *args->list[0].velocityZ : 0.0f));
}


static bool OnTrailerUpdate_handler(struct EventArgs_onTrailerUpdate* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnTrailerUpdate((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].trailer ? *args->list[0].trailer : NULL));
}


static bool OnVehicleSirenStateChange_handler(struct EventArgs_onVehicleSirenStateChange* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return false;
	}
	return OMPGO_OnVehicleSirenStateChange((args->list[0].player ? *args->list[0].player : NULL), (args->list[0].vehicle ? *args->list[0].vehicle : NULL), (args->list[0].sirenState ? *args->list[0].sirenState : 0));
}


bool capi_register_all_handlers() {
	if (!g_capi_initialised || !g_ompapi.Event.AddHandler) {
		return false;
	}
	bool ok = true;
	ok = g_ompapi.Event.AddHandler("onPlayerGiveDamageActor", EventPriorityType_Default, (void*)OnPlayerGiveDamageActor_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onActorStreamIn", EventPriorityType_Default, (void*)OnActorStreamIn_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onActorStreamOut", EventPriorityType_Default, (void*)OnActorStreamOut_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerEnterCheckpoint", EventPriorityType_Default, (void*)OnPlayerEnterCheckpoint_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerLeaveCheckpoint", EventPriorityType_Default, (void*)OnPlayerLeaveCheckpoint_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerEnterRaceCheckpoint", EventPriorityType_Default, (void*)OnPlayerEnterRaceCheckpoint_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerLeaveRaceCheckpoint", EventPriorityType_Default, (void*)OnPlayerLeaveRaceCheckpoint_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerRequestClass", EventPriorityType_Default, (void*)OnPlayerRequestClass_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onConsoleText", EventPriorityType_Default, (void*)OnConsoleText_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onRconLoginAttempt", EventPriorityType_Default, (void*)OnRconLoginAttempt_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onTick", EventPriorityType_Default, (void*)OnTick_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerFinishedDownloading", EventPriorityType_Default, (void*)OnPlayerFinishedDownloading_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerRequestDownload", EventPriorityType_Default, (void*)OnPlayerRequestDownload_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onDialogResponse", EventPriorityType_Default, (void*)OnDialogResponse_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerEnterGangZone", EventPriorityType_Default, (void*)OnPlayerEnterGangZone_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerLeaveGangZone", EventPriorityType_Default, (void*)OnPlayerLeaveGangZone_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerClickGangZone", EventPriorityType_Default, (void*)OnPlayerClickGangZone_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerSelectedMenuRow", EventPriorityType_Default, (void*)OnPlayerSelectedMenuRow_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerExitedMenu", EventPriorityType_Default, (void*)OnPlayerExitedMenu_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCFinishMove", EventPriorityType_Default, (void*)OnNPCFinishMove_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCCreate", EventPriorityType_Default, (void*)OnNPCCreate_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCDestroy", EventPriorityType_Default, (void*)OnNPCDestroy_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCWeaponStateChange", EventPriorityType_Default, (void*)OnNPCWeaponStateChange_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCTakeDamage", EventPriorityType_Default, (void*)OnNPCTakeDamage_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCGiveDamage", EventPriorityType_Default, (void*)OnNPCGiveDamage_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCDeath", EventPriorityType_Default, (void*)OnNPCDeath_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCSpawn", EventPriorityType_Default, (void*)OnNPCSpawn_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCRespawn", EventPriorityType_Default, (void*)OnNPCRespawn_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCPlaybackStart", EventPriorityType_Default, (void*)OnNPCPlaybackStart_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCPlaybackEnd", EventPriorityType_Default, (void*)OnNPCPlaybackEnd_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCShotMissed", EventPriorityType_Default, (void*)OnNPCShotMissed_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCShotPlayer", EventPriorityType_Default, (void*)OnNPCShotPlayer_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCShotNPC", EventPriorityType_Default, (void*)OnNPCShotNPC_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCShotVehicle", EventPriorityType_Default, (void*)OnNPCShotVehicle_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCShotObject", EventPriorityType_Default, (void*)OnNPCShotObject_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCShotPlayerObject", EventPriorityType_Default, (void*)OnNPCShotPlayerObject_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCFinishNodePoint", EventPriorityType_Default, (void*)OnNPCFinishNodePoint_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCFinishNode", EventPriorityType_Default, (void*)OnNPCFinishNode_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCChangeNode", EventPriorityType_Default, (void*)OnNPCChangeNode_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCFinishMovePath", EventPriorityType_Default, (void*)OnNPCFinishMovePath_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onNPCFinishMovePathPoint", EventPriorityType_Default, (void*)OnNPCFinishMovePathPoint_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onObjectMove", EventPriorityType_Default, (void*)OnObjectMove_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerObjectMove", EventPriorityType_Default, (void*)OnPlayerObjectMove_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerEditObject", EventPriorityType_Default, (void*)OnPlayerEditObject_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerEditPlayerObject", EventPriorityType_Default, (void*)OnPlayerEditPlayerObject_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerEditAttachedObject", EventPriorityType_Default, (void*)OnPlayerEditAttachedObject_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerSelectObject", EventPriorityType_Default, (void*)OnPlayerSelectObject_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerSelectPlayerObject", EventPriorityType_Default, (void*)OnPlayerSelectPlayerObject_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerPickUpPickup", EventPriorityType_Default, (void*)OnPlayerPickUpPickup_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerConnect", EventPriorityType_Default, (void*)OnPlayerConnect_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerSpawn", EventPriorityType_Default, (void*)OnPlayerSpawn_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerCommandText", EventPriorityType_Default, (void*)OnPlayerCommandText_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerKeyStateChange", EventPriorityType_Default, (void*)OnPlayerKeyStateChange_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onIncomingConnection", EventPriorityType_Default, (void*)OnIncomingConnection_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerDisconnect", EventPriorityType_Default, (void*)OnPlayerDisconnect_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerRequestSpawn", EventPriorityType_Default, (void*)OnPlayerRequestSpawn_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerStreamIn", EventPriorityType_Default, (void*)OnPlayerStreamIn_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerStreamOut", EventPriorityType_Default, (void*)OnPlayerStreamOut_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerText", EventPriorityType_Default, (void*)OnPlayerText_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerShotMissed", EventPriorityType_Default, (void*)OnPlayerShotMissed_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerShotPlayer", EventPriorityType_Default, (void*)OnPlayerShotPlayer_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerShotVehicle", EventPriorityType_Default, (void*)OnPlayerShotVehicle_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerShotObject", EventPriorityType_Default, (void*)OnPlayerShotObject_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerShotPlayerObject", EventPriorityType_Default, (void*)OnPlayerShotPlayerObject_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerDeath", EventPriorityType_Default, (void*)OnPlayerDeath_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerTakeDamage", EventPriorityType_Default, (void*)OnPlayerTakeDamage_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerGiveDamage", EventPriorityType_Default, (void*)OnPlayerGiveDamage_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerInteriorChange", EventPriorityType_Default, (void*)OnPlayerInteriorChange_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerStateChange", EventPriorityType_Default, (void*)OnPlayerStateChange_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerClickMap", EventPriorityType_Default, (void*)OnPlayerClickMap_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerClickPlayer", EventPriorityType_Default, (void*)OnPlayerClickPlayer_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onClientCheckResponse", EventPriorityType_Default, (void*)OnClientCheckResponse_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerUpdate", EventPriorityType_Default, (void*)OnPlayerUpdate_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerCancelTextDrawSelection", EventPriorityType_Default, (void*)OnPlayerCancelTextDrawSelection_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerCancelPlayerTextDrawSelection", EventPriorityType_Default, (void*)OnPlayerCancelPlayerTextDrawSelection_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerClickTextDraw", EventPriorityType_Default, (void*)OnPlayerClickTextDraw_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerClickPlayerTextDraw", EventPriorityType_Default, (void*)OnPlayerClickPlayerTextDraw_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onVehicleStreamIn", EventPriorityType_Default, (void*)OnVehicleStreamIn_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onVehicleStreamOut", EventPriorityType_Default, (void*)OnVehicleStreamOut_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onVehicleDeath", EventPriorityType_Default, (void*)OnVehicleDeath_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerEnterVehicle", EventPriorityType_Default, (void*)OnPlayerEnterVehicle_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onPlayerExitVehicle", EventPriorityType_Default, (void*)OnPlayerExitVehicle_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onVehicleDamageStatusUpdate", EventPriorityType_Default, (void*)OnVehicleDamageStatusUpdate_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onVehiclePaintJob", EventPriorityType_Default, (void*)OnVehiclePaintJob_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onVehicleMod", EventPriorityType_Default, (void*)OnVehicleMod_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onVehicleRespray", EventPriorityType_Default, (void*)OnVehicleRespray_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onEnterExitModShop", EventPriorityType_Default, (void*)OnEnterExitModShop_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onVehicleSpawn", EventPriorityType_Default, (void*)OnVehicleSpawn_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onUnoccupiedVehicleUpdate", EventPriorityType_Default, (void*)OnUnoccupiedVehicleUpdate_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onTrailerUpdate", EventPriorityType_Default, (void*)OnTrailerUpdate_handler) && ok;
	ok = g_ompapi.Event.AddHandler("onVehicleSirenStateChange", EventPriorityType_Default, (void*)OnVehicleSirenStateChange_handler) && ok;

	return ok;
}
*/
import "C"
