// Code generated by tools/codegen - DO NOT EDIT
package runtime

/*
#cgo CFLAGS: -I${SRCDIR}/include

#include "ompcapi.h"
*/
import "C"

import (
	"log"
	"unsafe"
)

//export OMPGO_OnPlayerGiveDamageActor
func OMPGO_OnPlayerGiveDamageActor(player unsafe.Pointer, actor unsafe.Pointer, amount C.float, weapon C.int, part C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerGiveDamageActor: %v", r)
		}
	}()
	Instance().OnPlayerGiveDamageActor(player, actor, float32(amount), int32(weapon), int32(part))
}

//export OMPGO_OnActorStreamIn
func OMPGO_OnActorStreamIn(actor unsafe.Pointer, forPlayer unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnActorStreamIn: %v", r)
		}
	}()
	Instance().OnActorStreamIn(actor, forPlayer)
}

//export OMPGO_OnActorStreamOut
func OMPGO_OnActorStreamOut(actor unsafe.Pointer, forPlayer unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnActorStreamOut: %v", r)
		}
	}()
	Instance().OnActorStreamOut(actor, forPlayer)
}

//export OMPGO_OnPlayerEnterCheckpoint
func OMPGO_OnPlayerEnterCheckpoint(player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerEnterCheckpoint: %v", r)
		}
	}()
	Instance().OnPlayerEnterCheckpoint(player)
}

//export OMPGO_OnPlayerLeaveCheckpoint
func OMPGO_OnPlayerLeaveCheckpoint(player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerLeaveCheckpoint: %v", r)
		}
	}()
	Instance().OnPlayerLeaveCheckpoint(player)
}

//export OMPGO_OnPlayerEnterRaceCheckpoint
func OMPGO_OnPlayerEnterRaceCheckpoint(player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerEnterRaceCheckpoint: %v", r)
		}
	}()
	Instance().OnPlayerEnterRaceCheckpoint(player)
}

//export OMPGO_OnPlayerLeaveRaceCheckpoint
func OMPGO_OnPlayerLeaveRaceCheckpoint(player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerLeaveRaceCheckpoint: %v", r)
		}
	}()
	Instance().OnPlayerLeaveRaceCheckpoint(player)
}

//export OMPGO_OnPlayerRequestClass
func OMPGO_OnPlayerRequestClass(player unsafe.Pointer, classID C.int) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerRequestClass: %v", r)
		}
	}()
	result := Instance().OnPlayerRequestClass(player, int32(classID))
	return C.bool(result)
}

//export OMPGO_OnConsoleText
func OMPGO_OnConsoleText(command C.struct_CAPIStringView, parameters C.struct_CAPIStringView) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnConsoleText: %v", r)
		}
	}()
	result := Instance().OnConsoleText(borrowedStringViewFromCAPIStringView(command), borrowedStringViewFromCAPIStringView(parameters))
	return C.bool(result)
}

//export OMPGO_OnRconLoginAttempt
func OMPGO_OnRconLoginAttempt(address C.struct_CAPIStringView, password C.struct_CAPIStringView, success C.bool) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnRconLoginAttempt: %v", r)
		}
	}()
	result := Instance().OnRconLoginAttempt(borrowedStringViewFromCAPIStringView(address), borrowedStringViewFromCAPIStringView(password), bool(success))
	return C.bool(result)
}

//export OMPGO_OnTick
func OMPGO_OnTick(elapsed C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnTick: %v", r)
		}
	}()
	Instance().OnTick(int32(elapsed))
}

//export OMPGO_OnPlayerFinishedDownloading
func OMPGO_OnPlayerFinishedDownloading(player unsafe.Pointer, vw C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerFinishedDownloading: %v", r)
		}
	}()
	Instance().OnPlayerFinishedDownloading(player, int32(vw))
}

//export OMPGO_OnPlayerRequestDownload
func OMPGO_OnPlayerRequestDownload(player unsafe.Pointer, typ C.int, checksum C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerRequestDownload: %v", r)
		}
	}()
	Instance().OnPlayerRequestDownload(player, int32(typ), int32(checksum))
}

//export OMPGO_OnDialogResponse
func OMPGO_OnDialogResponse(player unsafe.Pointer, dialogID C.int, response C.int, listItem C.int, inputText C.struct_CAPIStringView) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnDialogResponse: %v", r)
		}
	}()
	Instance().OnDialogResponse(player, int32(dialogID), int32(response), int32(listItem), borrowedStringViewFromCAPIStringView(inputText))
}

//export OMPGO_OnPlayerEnterGangZone
func OMPGO_OnPlayerEnterGangZone(player unsafe.Pointer, zone unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerEnterGangZone: %v", r)
		}
	}()
	Instance().OnPlayerEnterGangZone(player, zone)
}

//export OMPGO_OnPlayerLeaveGangZone
func OMPGO_OnPlayerLeaveGangZone(player unsafe.Pointer, zone unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerLeaveGangZone: %v", r)
		}
	}()
	Instance().OnPlayerLeaveGangZone(player, zone)
}

//export OMPGO_OnPlayerClickGangZone
func OMPGO_OnPlayerClickGangZone(player unsafe.Pointer, zone unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerClickGangZone: %v", r)
		}
	}()
	Instance().OnPlayerClickGangZone(player, zone)
}

//export OMPGO_OnPlayerSelectedMenuRow
func OMPGO_OnPlayerSelectedMenuRow(player unsafe.Pointer, row C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerSelectedMenuRow: %v", r)
		}
	}()
	Instance().OnPlayerSelectedMenuRow(player, int32(row))
}

//export OMPGO_OnPlayerExitedMenu
func OMPGO_OnPlayerExitedMenu(player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerExitedMenu: %v", r)
		}
	}()
	Instance().OnPlayerExitedMenu(player)
}

//export OMPGO_OnNPCFinishMove
func OMPGO_OnNPCFinishMove(npc unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCFinishMove: %v", r)
		}
	}()
	Instance().OnNPCFinishMove(npc)
}

//export OMPGO_OnNPCCreate
func OMPGO_OnNPCCreate(npc unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCCreate: %v", r)
		}
	}()
	Instance().OnNPCCreate(npc)
}

//export OMPGO_OnNPCDestroy
func OMPGO_OnNPCDestroy(npc unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCDestroy: %v", r)
		}
	}()
	Instance().OnNPCDestroy(npc)
}

//export OMPGO_OnNPCWeaponStateChange
func OMPGO_OnNPCWeaponStateChange(npc unsafe.Pointer, newState C.int, oldState C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCWeaponStateChange: %v", r)
		}
	}()
	Instance().OnNPCWeaponStateChange(npc, int32(newState), int32(oldState))
}

//export OMPGO_OnNPCTakeDamage
func OMPGO_OnNPCTakeDamage(npc unsafe.Pointer, damager unsafe.Pointer, damage C.float, weapon C.int, bodyPart C.int) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCTakeDamage: %v", r)
		}
	}()
	result := Instance().OnNPCTakeDamage(npc, damager, float32(damage), int32(weapon), int32(bodyPart))
	return C.bool(result)
}

//export OMPGO_OnNPCGiveDamage
func OMPGO_OnNPCGiveDamage(npc unsafe.Pointer, damaged unsafe.Pointer, damage C.float, weapon C.int, bodyPart C.int) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCGiveDamage: %v", r)
		}
	}()
	result := Instance().OnNPCGiveDamage(npc, damaged, float32(damage), int32(weapon), int32(bodyPart))
	return C.bool(result)
}

//export OMPGO_OnNPCDeath
func OMPGO_OnNPCDeath(npc unsafe.Pointer, killer unsafe.Pointer, reason C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCDeath: %v", r)
		}
	}()
	Instance().OnNPCDeath(npc, killer, int32(reason))
}

//export OMPGO_OnNPCSpawn
func OMPGO_OnNPCSpawn(npc unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCSpawn: %v", r)
		}
	}()
	Instance().OnNPCSpawn(npc)
}

//export OMPGO_OnNPCRespawn
func OMPGO_OnNPCRespawn(npc unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCRespawn: %v", r)
		}
	}()
	Instance().OnNPCRespawn(npc)
}

//export OMPGO_OnNPCPlaybackStart
func OMPGO_OnNPCPlaybackStart(npc unsafe.Pointer, recordID C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCPlaybackStart: %v", r)
		}
	}()
	Instance().OnNPCPlaybackStart(npc, int32(recordID))
}

//export OMPGO_OnNPCPlaybackEnd
func OMPGO_OnNPCPlaybackEnd(npc unsafe.Pointer, recordID C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCPlaybackEnd: %v", r)
		}
	}()
	Instance().OnNPCPlaybackEnd(npc, int32(recordID))
}

//export OMPGO_OnNPCShotMissed
func OMPGO_OnNPCShotMissed(npc unsafe.Pointer, weapon C.int, offsetX C.float, offsetY C.float, offsetZ C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCShotMissed: %v", r)
		}
	}()
	result := Instance().OnNPCShotMissed(npc, int32(weapon), float32(offsetX), float32(offsetY), float32(offsetZ))
	return C.bool(result)
}

//export OMPGO_OnNPCShotPlayer
func OMPGO_OnNPCShotPlayer(npc unsafe.Pointer, player unsafe.Pointer, weapon C.int, offsetX C.float, offsetY C.float, offsetZ C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCShotPlayer: %v", r)
		}
	}()
	result := Instance().OnNPCShotPlayer(npc, player, int32(weapon), float32(offsetX), float32(offsetY), float32(offsetZ))
	return C.bool(result)
}

//export OMPGO_OnNPCShotNPC
func OMPGO_OnNPCShotNPC(npc unsafe.Pointer, npcTarget unsafe.Pointer, weapon C.int, offsetX C.float, offsetY C.float, offsetZ C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCShotNPC: %v", r)
		}
	}()
	result := Instance().OnNPCShotNPC(npc, npcTarget, int32(weapon), float32(offsetX), float32(offsetY), float32(offsetZ))
	return C.bool(result)
}

//export OMPGO_OnNPCShotVehicle
func OMPGO_OnNPCShotVehicle(npc unsafe.Pointer, vehicle unsafe.Pointer, weapon C.int, offsetX C.float, offsetY C.float, offsetZ C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCShotVehicle: %v", r)
		}
	}()
	result := Instance().OnNPCShotVehicle(npc, vehicle, int32(weapon), float32(offsetX), float32(offsetY), float32(offsetZ))
	return C.bool(result)
}

//export OMPGO_OnNPCShotObject
func OMPGO_OnNPCShotObject(npc unsafe.Pointer, object unsafe.Pointer, weapon C.int, offsetX C.float, offsetY C.float, offsetZ C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCShotObject: %v", r)
		}
	}()
	result := Instance().OnNPCShotObject(npc, object, int32(weapon), float32(offsetX), float32(offsetY), float32(offsetZ))
	return C.bool(result)
}

//export OMPGO_OnNPCShotPlayerObject
func OMPGO_OnNPCShotPlayerObject(npc unsafe.Pointer, playerObject unsafe.Pointer, weapon C.int, offsetX C.float, offsetY C.float, offsetZ C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCShotPlayerObject: %v", r)
		}
	}()
	result := Instance().OnNPCShotPlayerObject(npc, playerObject, int32(weapon), float32(offsetX), float32(offsetY), float32(offsetZ))
	return C.bool(result)
}

//export OMPGO_OnNPCFinishNodePoint
func OMPGO_OnNPCFinishNodePoint(npc unsafe.Pointer, nodeID C.int, pointID C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCFinishNodePoint: %v", r)
		}
	}()
	Instance().OnNPCFinishNodePoint(npc, int32(nodeID), int32(pointID))
}

//export OMPGO_OnNPCFinishNode
func OMPGO_OnNPCFinishNode(npc unsafe.Pointer, nodeID C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCFinishNode: %v", r)
		}
	}()
	Instance().OnNPCFinishNode(npc, int32(nodeID))
}

//export OMPGO_OnNPCChangeNode
func OMPGO_OnNPCChangeNode(npc unsafe.Pointer, newNodeID C.int, oldNodeID C.int) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCChangeNode: %v", r)
		}
	}()
	result := Instance().OnNPCChangeNode(npc, int32(newNodeID), int32(oldNodeID))
	return C.bool(result)
}

//export OMPGO_OnNPCFinishMovePath
func OMPGO_OnNPCFinishMovePath(npc unsafe.Pointer, pathID C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCFinishMovePath: %v", r)
		}
	}()
	Instance().OnNPCFinishMovePath(npc, int32(pathID))
}

//export OMPGO_OnNPCFinishMovePathPoint
func OMPGO_OnNPCFinishMovePathPoint(npc unsafe.Pointer, pathID C.int, pointID C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnNPCFinishMovePathPoint: %v", r)
		}
	}()
	Instance().OnNPCFinishMovePathPoint(npc, int32(pathID), int32(pointID))
}

//export OMPGO_OnObjectMove
func OMPGO_OnObjectMove(object unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnObjectMove: %v", r)
		}
	}()
	Instance().OnObjectMove(object)
}

//export OMPGO_OnPlayerObjectMove
func OMPGO_OnPlayerObjectMove(player unsafe.Pointer, object unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerObjectMove: %v", r)
		}
	}()
	Instance().OnPlayerObjectMove(player, object)
}

//export OMPGO_OnPlayerEditObject
func OMPGO_OnPlayerEditObject(player unsafe.Pointer, object unsafe.Pointer, response C.int, offsetX C.float, offsetY C.float, offsetZ C.float, rotationX C.float, rotationY C.float, rotationZ C.float) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerEditObject: %v", r)
		}
	}()
	Instance().OnPlayerEditObject(player, object, int32(response), float32(offsetX), float32(offsetY), float32(offsetZ), float32(rotationX), float32(rotationY), float32(rotationZ))
}

//export OMPGO_OnPlayerEditPlayerObject
func OMPGO_OnPlayerEditPlayerObject(player unsafe.Pointer, object unsafe.Pointer, response C.int, offsetX C.float, offsetY C.float, offsetZ C.float, rotationX C.float, rotationY C.float, rotationZ C.float) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerEditPlayerObject: %v", r)
		}
	}()
	Instance().OnPlayerEditPlayerObject(player, object, int32(response), float32(offsetX), float32(offsetY), float32(offsetZ), float32(rotationX), float32(rotationY), float32(rotationZ))
}

//export OMPGO_OnPlayerEditAttachedObject
func OMPGO_OnPlayerEditAttachedObject(player unsafe.Pointer, saved C.bool, index C.int, model C.int, bone C.int, offsetX C.float, offsetY C.float, offsetZ C.float, rotationX C.float, rotationY C.float, rotationZ C.float, scaleX C.float, scaleY C.float, scaleZ C.float) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerEditAttachedObject: %v", r)
		}
	}()
	Instance().OnPlayerEditAttachedObject(player, bool(saved), int32(index), int32(model), int32(bone), float32(offsetX), float32(offsetY), float32(offsetZ), float32(rotationX), float32(rotationY), float32(rotationZ), float32(scaleX), float32(scaleY), float32(scaleZ))
}

//export OMPGO_OnPlayerSelectObject
func OMPGO_OnPlayerSelectObject(player unsafe.Pointer, object unsafe.Pointer, model C.int, x C.float, y C.float, z C.float) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerSelectObject: %v", r)
		}
	}()
	Instance().OnPlayerSelectObject(player, object, int32(model), float32(x), float32(y), float32(z))
}

//export OMPGO_OnPlayerSelectPlayerObject
func OMPGO_OnPlayerSelectPlayerObject(player unsafe.Pointer, object unsafe.Pointer, model C.int, x C.float, y C.float, z C.float) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerSelectPlayerObject: %v", r)
		}
	}()
	Instance().OnPlayerSelectPlayerObject(player, object, int32(model), float32(x), float32(y), float32(z))
}

//export OMPGO_OnPlayerPickUpPickup
func OMPGO_OnPlayerPickUpPickup(player unsafe.Pointer, pickup unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerPickUpPickup: %v", r)
		}
	}()
	Instance().OnPlayerPickUpPickup(player, pickup)
}

//export OMPGO_OnPlayerConnect
func OMPGO_OnPlayerConnect(player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerConnect: %v", r)
		}
	}()
	Instance().OnPlayerConnect(player)
}

//export OMPGO_OnPlayerSpawn
func OMPGO_OnPlayerSpawn(player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerSpawn: %v", r)
		}
	}()
	Instance().OnPlayerSpawn(player)
}

//export OMPGO_OnPlayerCommandText
func OMPGO_OnPlayerCommandText(player unsafe.Pointer, command C.struct_CAPIStringView) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerCommandText: %v", r)
		}
	}()
	result := Instance().OnPlayerCommandText(player, borrowedStringViewFromCAPIStringView(command))
	return C.bool(result)
}

//export OMPGO_OnPlayerKeyStateChange
func OMPGO_OnPlayerKeyStateChange(player unsafe.Pointer, newKeys C.int, oldKeys C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerKeyStateChange: %v", r)
		}
	}()
	Instance().OnPlayerKeyStateChange(player, int32(newKeys), int32(oldKeys))
}

//export OMPGO_OnIncomingConnection
func OMPGO_OnIncomingConnection(player unsafe.Pointer, ipAddress C.struct_CAPIStringView, port C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnIncomingConnection: %v", r)
		}
	}()
	Instance().OnIncomingConnection(player, borrowedStringViewFromCAPIStringView(ipAddress), int32(port))
}

//export OMPGO_OnPlayerDisconnect
func OMPGO_OnPlayerDisconnect(player unsafe.Pointer, reason C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerDisconnect: %v", r)
		}
	}()
	Instance().OnPlayerDisconnect(player, int32(reason))
}

//export OMPGO_OnPlayerRequestSpawn
func OMPGO_OnPlayerRequestSpawn(player unsafe.Pointer) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerRequestSpawn: %v", r)
		}
	}()
	result := Instance().OnPlayerRequestSpawn(player)
	return C.bool(result)
}

//export OMPGO_OnPlayerStreamIn
func OMPGO_OnPlayerStreamIn(player unsafe.Pointer, forPlayer unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerStreamIn: %v", r)
		}
	}()
	Instance().OnPlayerStreamIn(player, forPlayer)
}

//export OMPGO_OnPlayerStreamOut
func OMPGO_OnPlayerStreamOut(player unsafe.Pointer, forPlayer unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerStreamOut: %v", r)
		}
	}()
	Instance().OnPlayerStreamOut(player, forPlayer)
}

//export OMPGO_OnPlayerText
func OMPGO_OnPlayerText(player unsafe.Pointer, text C.struct_CAPIStringView) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerText: %v", r)
		}
	}()
	result := Instance().OnPlayerText(player, borrowedStringViewFromCAPIStringView(text))
	return C.bool(result)
}

//export OMPGO_OnPlayerShotMissed
func OMPGO_OnPlayerShotMissed(player unsafe.Pointer, weapon C.int, x C.float, y C.float, z C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerShotMissed: %v", r)
		}
	}()
	result := Instance().OnPlayerShotMissed(player, int32(weapon), float32(x), float32(y), float32(z))
	return C.bool(result)
}

//export OMPGO_OnPlayerShotPlayer
func OMPGO_OnPlayerShotPlayer(player unsafe.Pointer, target unsafe.Pointer, weapon C.int, x C.float, y C.float, z C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerShotPlayer: %v", r)
		}
	}()
	result := Instance().OnPlayerShotPlayer(player, target, int32(weapon), float32(x), float32(y), float32(z))
	return C.bool(result)
}

//export OMPGO_OnPlayerShotVehicle
func OMPGO_OnPlayerShotVehicle(player unsafe.Pointer, target unsafe.Pointer, weapon C.int, x C.float, y C.float, z C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerShotVehicle: %v", r)
		}
	}()
	result := Instance().OnPlayerShotVehicle(player, target, int32(weapon), float32(x), float32(y), float32(z))
	return C.bool(result)
}

//export OMPGO_OnPlayerShotObject
func OMPGO_OnPlayerShotObject(player unsafe.Pointer, target unsafe.Pointer, weapon C.int, x C.float, y C.float, z C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerShotObject: %v", r)
		}
	}()
	result := Instance().OnPlayerShotObject(player, target, int32(weapon), float32(x), float32(y), float32(z))
	return C.bool(result)
}

//export OMPGO_OnPlayerShotPlayerObject
func OMPGO_OnPlayerShotPlayerObject(player unsafe.Pointer, target unsafe.Pointer, weapon C.int, x C.float, y C.float, z C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerShotPlayerObject: %v", r)
		}
	}()
	result := Instance().OnPlayerShotPlayerObject(player, target, int32(weapon), float32(x), float32(y), float32(z))
	return C.bool(result)
}

//export OMPGO_OnPlayerDeath
func OMPGO_OnPlayerDeath(player unsafe.Pointer, killer unsafe.Pointer, reason C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerDeath: %v", r)
		}
	}()
	Instance().OnPlayerDeath(player, killer, int32(reason))
}

//export OMPGO_OnPlayerTakeDamage
func OMPGO_OnPlayerTakeDamage(player unsafe.Pointer, from unsafe.Pointer, amount C.float, weapon C.int, bodypart C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerTakeDamage: %v", r)
		}
	}()
	Instance().OnPlayerTakeDamage(player, from, float32(amount), int32(weapon), int32(bodypart))
}

//export OMPGO_OnPlayerGiveDamage
func OMPGO_OnPlayerGiveDamage(player unsafe.Pointer, to unsafe.Pointer, amount C.float, weapon C.int, bodypart C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerGiveDamage: %v", r)
		}
	}()
	Instance().OnPlayerGiveDamage(player, to, float32(amount), int32(weapon), int32(bodypart))
}

//export OMPGO_OnPlayerInteriorChange
func OMPGO_OnPlayerInteriorChange(player unsafe.Pointer, newInterior C.int, oldInterior C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerInteriorChange: %v", r)
		}
	}()
	Instance().OnPlayerInteriorChange(player, int32(newInterior), int32(oldInterior))
}

//export OMPGO_OnPlayerStateChange
func OMPGO_OnPlayerStateChange(player unsafe.Pointer, newState C.int, oldState C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerStateChange: %v", r)
		}
	}()
	Instance().OnPlayerStateChange(player, int32(newState), int32(oldState))
}

//export OMPGO_OnPlayerClickMap
func OMPGO_OnPlayerClickMap(player unsafe.Pointer, x C.float, y C.float, z C.float) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerClickMap: %v", r)
		}
	}()
	Instance().OnPlayerClickMap(player, float32(x), float32(y), float32(z))
}

//export OMPGO_OnPlayerClickPlayer
func OMPGO_OnPlayerClickPlayer(player unsafe.Pointer, clicked unsafe.Pointer, source C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerClickPlayer: %v", r)
		}
	}()
	Instance().OnPlayerClickPlayer(player, clicked, int32(source))
}

//export OMPGO_OnClientCheckResponse
func OMPGO_OnClientCheckResponse(player unsafe.Pointer, actionType C.int, address C.int, result C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnClientCheckResponse: %v", r)
		}
	}()
	Instance().OnClientCheckResponse(player, int32(actionType), int32(address), int32(result))
}

//export OMPGO_OnPlayerUpdate
func OMPGO_OnPlayerUpdate(player unsafe.Pointer) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerUpdate: %v", r)
		}
	}()
	result := Instance().OnPlayerUpdate(player)
	return C.bool(result)
}

//export OMPGO_OnPlayerCancelTextDrawSelection
func OMPGO_OnPlayerCancelTextDrawSelection(player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerCancelTextDrawSelection: %v", r)
		}
	}()
	Instance().OnPlayerCancelTextDrawSelection(player)
}

//export OMPGO_OnPlayerCancelPlayerTextDrawSelection
func OMPGO_OnPlayerCancelPlayerTextDrawSelection(player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerCancelPlayerTextDrawSelection: %v", r)
		}
	}()
	Instance().OnPlayerCancelPlayerTextDrawSelection(player)
}

//export OMPGO_OnPlayerClickTextDraw
func OMPGO_OnPlayerClickTextDraw(player unsafe.Pointer, textdraw unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerClickTextDraw: %v", r)
		}
	}()
	Instance().OnPlayerClickTextDraw(player, textdraw)
}

//export OMPGO_OnPlayerClickPlayerTextDraw
func OMPGO_OnPlayerClickPlayerTextDraw(player unsafe.Pointer, textdraw unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerClickPlayerTextDraw: %v", r)
		}
	}()
	Instance().OnPlayerClickPlayerTextDraw(player, textdraw)
}

//export OMPGO_OnVehicleStreamIn
func OMPGO_OnVehicleStreamIn(vehicle unsafe.Pointer, player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnVehicleStreamIn: %v", r)
		}
	}()
	Instance().OnVehicleStreamIn(vehicle, player)
}

//export OMPGO_OnVehicleStreamOut
func OMPGO_OnVehicleStreamOut(vehicle unsafe.Pointer, player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnVehicleStreamOut: %v", r)
		}
	}()
	Instance().OnVehicleStreamOut(vehicle, player)
}

//export OMPGO_OnVehicleDeath
func OMPGO_OnVehicleDeath(vehicle unsafe.Pointer, player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnVehicleDeath: %v", r)
		}
	}()
	Instance().OnVehicleDeath(vehicle, player)
}

//export OMPGO_OnPlayerEnterVehicle
func OMPGO_OnPlayerEnterVehicle(player unsafe.Pointer, vehicle unsafe.Pointer, passenger C.bool) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerEnterVehicle: %v", r)
		}
	}()
	Instance().OnPlayerEnterVehicle(player, vehicle, bool(passenger))
}

//export OMPGO_OnPlayerExitVehicle
func OMPGO_OnPlayerExitVehicle(player unsafe.Pointer, vehicle unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnPlayerExitVehicle: %v", r)
		}
	}()
	Instance().OnPlayerExitVehicle(player, vehicle)
}

//export OMPGO_OnVehicleDamageStatusUpdate
func OMPGO_OnVehicleDamageStatusUpdate(vehicle unsafe.Pointer, player unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnVehicleDamageStatusUpdate: %v", r)
		}
	}()
	Instance().OnVehicleDamageStatusUpdate(vehicle, player)
}

//export OMPGO_OnVehiclePaintJob
func OMPGO_OnVehiclePaintJob(player unsafe.Pointer, vehicle unsafe.Pointer, paintJob C.int) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnVehiclePaintJob: %v", r)
		}
	}()
	result := Instance().OnVehiclePaintJob(player, vehicle, int32(paintJob))
	return C.bool(result)
}

//export OMPGO_OnVehicleMod
func OMPGO_OnVehicleMod(player unsafe.Pointer, vehicle unsafe.Pointer, component C.int) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnVehicleMod: %v", r)
		}
	}()
	result := Instance().OnVehicleMod(player, vehicle, int32(component))
	return C.bool(result)
}

//export OMPGO_OnVehicleRespray
func OMPGO_OnVehicleRespray(player unsafe.Pointer, vehicle unsafe.Pointer, color1 C.int, color2 C.int) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnVehicleRespray: %v", r)
		}
	}()
	result := Instance().OnVehicleRespray(player, vehicle, int32(color1), int32(color2))
	return C.bool(result)
}

//export OMPGO_OnEnterExitModShop
func OMPGO_OnEnterExitModShop(player unsafe.Pointer, enterexit C.int, interiorID C.int) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnEnterExitModShop: %v", r)
		}
	}()
	Instance().OnEnterExitModShop(player, int32(enterexit), int32(interiorID))
}

//export OMPGO_OnVehicleSpawn
func OMPGO_OnVehicleSpawn(vehicle unsafe.Pointer) {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnVehicleSpawn: %v", r)
		}
	}()
	Instance().OnVehicleSpawn(vehicle)
}

//export OMPGO_OnUnoccupiedVehicleUpdate
func OMPGO_OnUnoccupiedVehicleUpdate(vehicle unsafe.Pointer, player unsafe.Pointer, seat C.int, posX C.float, posY C.float, posZ C.float, velocityX C.float, velocityY C.float, velocityZ C.float) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnUnoccupiedVehicleUpdate: %v", r)
		}
	}()
	result := Instance().OnUnoccupiedVehicleUpdate(vehicle, player, int32(seat), float32(posX), float32(posY), float32(posZ), float32(velocityX), float32(velocityY), float32(velocityZ))
	return C.bool(result)
}

//export OMPGO_OnTrailerUpdate
func OMPGO_OnTrailerUpdate(player unsafe.Pointer, trailer unsafe.Pointer) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnTrailerUpdate: %v", r)
		}
	}()
	result := Instance().OnTrailerUpdate(player, trailer)
	return C.bool(result)
}

//export OMPGO_OnVehicleSirenStateChange
func OMPGO_OnVehicleSirenStateChange(player unsafe.Pointer, vehicle unsafe.Pointer, sirenState C.int) C.bool {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in OnVehicleSirenStateChange: %v", r)
		}
	}()
	result := Instance().OnVehicleSirenStateChange(player, vehicle, int32(sirenState))
	return C.bool(result)
}
