// Code generated by tools/codegen - DO NOT EDIT
package actor

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI Actor_Create
func Create(model int32, x float32, y float32, z float32, rot float32, id *int32) *omp.Actor {
	c := runtime.Instance().CAPI()
	res := c.Actor_Create(model, x, y, z, rot, id)
	return omp.NewActor(res)
}

// Destroy wraps CAPI Actor_Destroy
func Destroy(actor *omp.Actor) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_Destroy(actor.Handle())
}

// FromID wraps CAPI Actor_FromID
func FromID(actorid int32) *omp.Actor {
	c := runtime.Instance().CAPI()
	res := c.Actor_FromID(actorid)
	return omp.NewActor(res)
}

// GetID wraps CAPI Actor_GetID
func GetID(actor *omp.Actor) int32 {
	c := runtime.Instance().CAPI()
	return c.Actor_GetID(actor.Handle())
}

// IsStreamedInFor wraps CAPI Actor_IsStreamedInFor
func IsStreamedInFor(actor *omp.Actor, player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_IsStreamedInFor(actor.Handle(), player.Handle())
}

// SetVirtualWorld wraps CAPI Actor_SetVirtualWorld
func SetVirtualWorld(actor *omp.Actor, vw int32) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_SetVirtualWorld(actor.Handle(), vw)
}

// GetVirtualWorld wraps CAPI Actor_GetVirtualWorld
func GetVirtualWorld(actor *omp.Actor) int32 {
	c := runtime.Instance().CAPI()
	return c.Actor_GetVirtualWorld(actor.Handle())
}

// ApplyAnimation wraps CAPI Actor_ApplyAnimation
func ApplyAnimation(actor *omp.Actor, name string, library string, delta float32, loop bool, lockX bool, lockY bool, freeze bool, time int32) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_ApplyAnimation(actor.Handle(), name, library, delta, loop, lockX, lockY, freeze, time)
}

// ClearAnimations wraps CAPI Actor_ClearAnimations
func ClearAnimations(actor *omp.Actor) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_ClearAnimations(actor.Handle())
}

// SetPos wraps CAPI Actor_SetPos
func SetPos(actor *omp.Actor, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_SetPos(actor.Handle(), x, y, z)
}

// GetPos wraps CAPI Actor_GetPos
func GetPos(actor *omp.Actor, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_GetPos(actor.Handle(), x, y, z)
}

// SetFacingAngle wraps CAPI Actor_SetFacingAngle
func SetFacingAngle(actor *omp.Actor, angle float32) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_SetFacingAngle(actor.Handle(), angle)
}

// GetFacingAngle wraps CAPI Actor_GetFacingAngle
func GetFacingAngle(actor *omp.Actor) float32 {
	c := runtime.Instance().CAPI()
	return c.Actor_GetFacingAngle(actor.Handle())
}

// SetHealth wraps CAPI Actor_SetHealth
func SetHealth(actor *omp.Actor, hp float32) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_SetHealth(actor.Handle(), hp)
}

// GetHealth wraps CAPI Actor_GetHealth
func GetHealth(actor *omp.Actor) float32 {
	c := runtime.Instance().CAPI()
	return c.Actor_GetHealth(actor.Handle())
}

// SetInvulnerable wraps CAPI Actor_SetInvulnerable
func SetInvulnerable(actor *omp.Actor, toggle bool) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_SetInvulnerable(actor.Handle(), toggle)
}

// IsInvulnerable wraps CAPI Actor_IsInvulnerable
func IsInvulnerable(actor *omp.Actor) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_IsInvulnerable(actor.Handle())
}

// IsValid wraps CAPI Actor_IsValid
func IsValid(actor *omp.Actor) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_IsValid(actor.Handle())
}

// SetSkin wraps CAPI Actor_SetSkin
func SetSkin(actor *omp.Actor, skin int32) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_SetSkin(actor.Handle(), skin)
}

// GetSkin wraps CAPI Actor_GetSkin
func GetSkin(actor *omp.Actor) int32 {
	c := runtime.Instance().CAPI()
	return c.Actor_GetSkin(actor.Handle())
}

// GetAnimation wraps CAPI Actor_GetAnimation
func GetAnimation(actor *omp.Actor, library *string, name *string, delta *float32, loop *bool, lockX *bool, lockY *bool, freeze *bool, time *int32) bool {
	c := runtime.Instance().CAPI()
	var libraryView runtime.CAPIStringView
	var nameView runtime.CAPIStringView
	res := c.Actor_GetAnimation(actor.Handle(), &libraryView, &nameView, delta, loop, lockX, lockY, freeze, time)
	if library != nil {
		*library = runtime.CAPIStringViewToString(&libraryView)
	}
	if name != nil {
		*name = runtime.CAPIStringViewToString(&nameView)
	}
	return res
}

// GetSpawnInfo wraps CAPI Actor_GetSpawnInfo
func GetSpawnInfo(actor *omp.Actor, x *float32, y *float32, z *float32, angle *float32, skin *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Actor_GetSpawnInfo(actor.Handle(), x, y, z, angle, skin)
}
