// Code generated by tools/codegen - DO NOT EDIT
package menu

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI Menu_Create
func Create(title string, columns uint32, x float32, y float32, column1Width float32, column2Width float32, id *int32) *omp.Menu {
	c := runtime.Instance().CAPI()
	res := c.Menu_Create(title, columns, x, y, column1Width, column2Width, id)
	return omp.NewMenu(res)
}

// Destroy wraps CAPI Menu_Destroy
func Destroy(menu *omp.Menu) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_Destroy(menu.Handle())
}

// FromID wraps CAPI Menu_FromID
func FromID(menuid int32) *omp.Menu {
	c := runtime.Instance().CAPI()
	res := c.Menu_FromID(menuid)
	return omp.NewMenu(res)
}

// GetID wraps CAPI Menu_GetID
func GetID(menu *omp.Menu) int32 {
	c := runtime.Instance().CAPI()
	return c.Menu_GetID(menu.Handle())
}

// AddItem wraps CAPI Menu_AddItem
func AddItem(menu *omp.Menu, column uint8, text string) int32 {
	c := runtime.Instance().CAPI()
	return c.Menu_AddItem(menu.Handle(), column, text)
}

// SetColumnHeader wraps CAPI Menu_SetColumnHeader
func SetColumnHeader(menu *omp.Menu, column uint8, headerTitle string) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_SetColumnHeader(menu.Handle(), column, headerTitle)
}

// ShowForPlayer wraps CAPI Menu_ShowForPlayer
func ShowForPlayer(menu *omp.Menu, player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_ShowForPlayer(menu.Handle(), player.Handle())
}

// HideForPlayer wraps CAPI Menu_HideForPlayer
func HideForPlayer(menu *omp.Menu, player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_HideForPlayer(menu.Handle(), player.Handle())
}

// Disable wraps CAPI Menu_Disable
func Disable(menu *omp.Menu) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_Disable(menu.Handle())
}

// DisableRow wraps CAPI Menu_DisableRow
func DisableRow(menu *omp.Menu, row uint8) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_DisableRow(menu.Handle(), row)
}

// IsValid wraps CAPI Menu_IsValid
func IsValid(menu *omp.Menu) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_IsValid(menu.Handle())
}

// IsDisabled wraps CAPI Menu_IsDisabled
func IsDisabled(menu *omp.Menu) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_IsDisabled(menu.Handle())
}

// IsRowDisabled wraps CAPI Menu_IsRowDisabled
func IsRowDisabled(menu *omp.Menu, row int32) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_IsRowDisabled(menu.Handle(), row)
}

// GetColumns wraps CAPI Menu_GetColumns
func GetColumns(menu *omp.Menu) int32 {
	c := runtime.Instance().CAPI()
	return c.Menu_GetColumns(menu.Handle())
}

// GetItems wraps CAPI Menu_GetItems
func GetItems(menu *omp.Menu, column int32) int32 {
	c := runtime.Instance().CAPI()
	return c.Menu_GetItems(menu.Handle(), column)
}

// GetPos wraps CAPI Menu_GetPos
func GetPos(menu *omp.Menu, x *float32, y *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_GetPos(menu.Handle(), x, y)
}

// GetColumnWidth wraps CAPI Menu_GetColumnWidth
func GetColumnWidth(menu *omp.Menu, column1Width *float32, column2Width *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Menu_GetColumnWidth(menu.Handle(), column1Width, column2Width)
}

// GetColumnHeaderString wraps CAPI Menu_GetColumnHeader and returns a string.
func GetColumnHeaderString(menu *omp.Menu, column int32) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Menu_GetColumnHeaderString(menu.Handle(), column)
}

// GetItemString wraps CAPI Menu_GetItem and returns a string.
func GetItemString(menu *omp.Menu, column int32, row int32) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Menu_GetItemString(menu.Handle(), column, row)
}
