// Code generated by tools/codegen - DO NOT EDIT
package all

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// SendClientMessage wraps CAPI All_SendClientMessage
func SendClientMessage(color uint32, text string) bool {
	c := runtime.Instance().CAPI()
	return c.All_SendClientMessage(color, text)
}

// CreateExplosion wraps CAPI All_CreateExplosion
func CreateExplosion(x float32, y float32, z float32, typ int32, radius float32) bool {
	c := runtime.Instance().CAPI()
	return c.All_CreateExplosion(x, y, z, typ, radius)
}

// SendDeathMessage wraps CAPI All_SendDeathMessage
func SendDeathMessage(killer *omp.Player, killee *omp.Player, weapon int32) bool {
	c := runtime.Instance().CAPI()
	return c.All_SendDeathMessage(killer.Handle(), killee.Handle(), weapon)
}

// EnableStuntBonus wraps CAPI All_EnableStuntBonus
func EnableStuntBonus(enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.All_EnableStuntBonus(enable)
}
