package generator

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/ompgo-dev/ompgo/tools/codegen/mapping"
	"github.com/ompgo-dev/ompgo/tools/codegen/model"
)

// generateCAPIAPIWrappers generates pkg/runtime/capi_api_gen.go
func generateCAPIAPIWrappers(apiGroups map[string][]model.APIFunction, outDir, modulePath string) error {
	fmt.Println("Generating CAPI API wrappers...")

	// Remove superseded generated files if present.
	_ = os.Remove(outDir + "/capi_api_gen.h")
	_ = os.Remove(outDir + "/capi_wrappers_gen.go")

	apiGoTemplate := template.Must(template.New("capi_api_go").Funcs(template.FuncMap{
		"goType":       mapping.GoTypeForCType,
		"cArg":         mapping.GoArgForCType,
		"hasReturn":    hasReturnValueFromCType,
		"safeGoName":   mapping.SafeGoName,
		"apiFuncName":  apiFuncName,
		"safeCName":    safeCName,
		"defaultGoRet": mapping.DefaultGoReturn,
		"cType":        mapping.CTypeToC,
		"defaultRet":   mapping.DefaultReturnValue,
		"groupName":    groupName,
		"methodName":   methodName,
		"isStrOut":     mapping.IsStringOutputCandidate,
		"strOutType":   mapping.StringOutputParamType,
		"isStrParam":   mapping.IsStringParam,
		"strHelper":    stringHelperName,
		"strParams":    stringHelperParams,
		"strCallArgs":  stringHelperCallArgs,
		"strRetOk":     stringHelperOkExpr,
		"strRetConv":   stringHelperReturnExpr,
	}).Parse(capiAPIGoTemplate))

	groups := make([]string, 0, len(apiGroups))
	for group := range apiGroups {
		groups = append(groups, group)
	}
	sort.Strings(groups)

	allFunctions := []model.APIFunction{}
	for _, group := range groups {
		for _, fn := range apiGroups[group] {
			if strings.Contains(fn.Name, "_Internal") {
				continue
			}
			allFunctions = append(allFunctions, fn)
		}
	}

	data := struct {
		Functions  []model.APIFunction
		ModulePath string
	}{
		Functions:  allFunctions,
		ModulePath: modulePath,
	}

	var buf bytes.Buffer
	if err := apiGoTemplate.Execute(&buf, data); err != nil {
		return err
	}
	return writeFormattedGoFile(outDir+"/capi_api_gen.go", buf.Bytes())
}

func stringHelperName(fn model.APIFunction) string {
	return fn.Name + "String"
}

func stringHelperParams(fn model.APIFunction) string {
	var parts []string
	for _, p := range fn.Params {
		if p.Type == "CAPIStringView*" || p.Type == "CAPIStringBuffer*" {
			continue
		}
		name := mapping.SafeGoName(p.Name)
		parts = append(parts, fmt.Sprintf("%s %s", name, mapping.GoTypeForCType(p.Type)))
	}
	return strings.Join(parts, ", ")
}

func stringHelperCallArgs(fn model.APIFunction) string {
	var parts []string
	for _, p := range fn.Params {
		switch p.Type {
		case "CAPIStringView*":
			parts = append(parts, "&view")
		case "CAPIStringBuffer*":
			parts = append(parts, "&buf")
		default:
			name := mapping.SafeGoName(p.Name)
			parts = append(parts, name)
		}
	}
	return strings.Join(parts, ", ")
}

func stringHelperOkExpr(fn model.APIFunction) string {
	switch fn.Ret {
	case "bool":
		return "ok = ret"
	case "void":
		return "ok = true"
	default:
		if strings.Contains(fn.Ret, "int") {
			return "ok = ret != 0"
		}
		return "ok = true"
	}
}

func stringHelperReturnExpr(fn model.APIFunction) string {
	switch mapping.StringOutputParamType(fn) {
	case "CAPIStringBuffer*":
		return "stringFromBuffer(buf)"
	default:
		return "stringFromView(view)"
	}
}

func safeCName(name string) string {
	// Avoid C/C++ keywords in parameter names
	switch name {
	case "class", "template", "typename", "namespace", "operator", "new", "delete", "this":
		return name + "_"
	case "type":
		return "type_"
	default:
		return name
	}
}

func apiFuncName(name string) string {
	return "capi_" + name
}

func groupName(fullName string) string {
	parts := strings.SplitN(fullName, "_", 2)
	if len(parts) == 0 {
		return fullName
	}
	return parts[0]
}

func methodName(fullName string) string {
	parts := strings.SplitN(fullName, "_", 2)
	if len(parts) < 2 {
		return fullName
	}
	return parts[1]
}

func hasReturnValueFromCType(ret string) bool {
	return ret != "void"
}

const capiAPIGoTemplate = `// Code generated by tools/codegen - DO NOT EDIT
package runtime

/*
#cgo CFLAGS: -I${SRCDIR}/include

#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include "ompcapi.h"

extern struct OMPAPI_t g_ompapi;
extern bool g_capi_initialised;

{{range .Functions}}
static inline {{cType .Ret}} {{apiFuncName .Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{cType $p.Type}} {{safeCName $p.Name}}{{end}}) {
	if (!g_capi_initialised || !g_ompapi.{{groupName .Name}}.{{methodName .Name}}) {
		{{if ne .Ret "void"}}return {{defaultRet .Ret}};{{else}}return;{{end}}
	}
	{{if ne .Ret "void"}}return {{end}}g_ompapi.{{groupName .Name}}.{{methodName .Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{safeCName $p.Name}}{{end}});
}
{{end}}
*/
import "C"

import (
	"unsafe"

	"{{.ModulePath}}/pkg/handle"
)

const defaultStringBufferSize = 1024

// StringBufferSize controls the buffer size used for CAPIStringBuffer outputs.
var StringBufferSize = defaultStringBufferSize

// stringFromView converts CAPIStringView to Go string.
func stringFromView(view C.struct_CAPIStringView) string {
	if view.data == nil || view.len == 0 {
		return ""
	}
	return C.GoStringN(view.data, C.int(view.len))
}

// stringFromBuffer converts CAPIStringBuffer to Go string.
func stringFromBuffer(buf C.struct_CAPIStringBuffer) string {
	if buf.data == nil || buf.len == 0 {
		return ""
	}
	return C.GoStringN(buf.data, C.int(buf.len))
}

func allocStringBuffer() (C.struct_CAPIStringBuffer, func()) {
	size := StringBufferSize
	if size <= 0 {
		size = defaultStringBufferSize
	}
	data := (*C.char)(C.malloc(C.size_t(size)))
	var buf C.struct_CAPIStringBuffer
	buf.capacity = C.uint(size)
	buf.len = 0
	buf.data = data
	return buf, func() {
		if data != nil {
			C.free(unsafe.Pointer(data))
		}
	}
}

{{- range .Functions}}
// {{.Name}} wraps CAPI call {{apiFuncName .Name}}
func (c *CAPI) {{.Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{safeGoName $p.Name}} {{goType $p.Type}}{{end}}){{if hasReturn .Ret}} {{goType .Ret}}{{end}} {
	if c == nil || !c.IsInitialised() {
		{{- if eq .Ret "void*" -}}return handle.Handle(0){{- else if hasReturn .Ret -}}return {{defaultGoRet .Ret}}{{- end }}
	}
	{{- range $p := .Params }}
	{{- if isStrParam $p.Type }}
	c_{{safeGoName $p.Name}} := C.CString({{safeGoName $p.Name}})
	defer C.free(unsafe.Pointer(c_{{safeGoName $p.Name}}))
	{{- end }}
	{{- end }}
	{{- if hasReturn .Ret }}
	{{- if eq .Ret "void*" }}
	return handleFromPtr(C.{{apiFuncName .Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{cArg $p.Name $p.Type}}{{end}}))
	{{- else }}
	return {{goType .Ret}}(C.{{apiFuncName .Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{cArg $p.Name $p.Type}}{{end}}))
	{{- end }}
	{{- else }}
	C.{{apiFuncName .Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{cArg $p.Name $p.Type}}{{end}})
	{{- end }}
}

{{- if isStrOut .}}
// {{strHelper .}} wraps {{.Name}} and returns a Go string.
func (c *CAPI) {{strHelper .}}({{strParams .}}) (string, bool) {
	if c == nil || !c.IsInitialised() {
		return "", false
	}
	{{- if eq (strOutType .) "CAPIStringView*" }}
	var view C.struct_CAPIStringView
	{{- end }}
	{{- if eq (strOutType .) "CAPIStringBuffer*" }}
	var buf C.struct_CAPIStringBuffer
	var freeBuf func()
	buf, freeBuf = allocStringBuffer()
	defer freeBuf()
	{{- end }}
	{{- if hasReturn .Ret }}
	ret := c.{{.Name}}({{strCallArgs .}})
	ok := false
	{{strRetOk .}}
	return {{strRetConv .}}, ok
	{{- else }}
	c.{{.Name}}({{strCallArgs .}})
	return {{strRetConv .}}, true
	{{- end }}
}

{{- end}}

{{- end}}
`
