package generator

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/ompgo-dev/ompgo/tools/codegen/mapping"
	"github.com/ompgo-dev/ompgo/tools/codegen/model"
)

// generateCAPIEventBindings generates pkg/runtime/capi_events_cgo_gen.go.
func generateCAPIEventBindings(eventGroups map[string][]model.Event, outDir string) error {
	fmt.Println("Generating CAPI event registration CGo bindings...")

	tmpl := template.Must(template.New("capi_events").Funcs(template.FuncMap{
		"handlerName":     mapping.HandlerName,
		"exportName":      mapping.ExportName,
		"eventArgsType":   eventArgsTypeName,
		"hasReturn":       hasReturnValue,
		"externSignature": buildExternSignature,
		"cHandlerParams":  buildCHandlerCallParams,
	}).Parse(capiEventsGoTemplate))

	allEvents := orderedEvents(eventGroups)

	data := struct {
		Events []model.Event
	}{
		Events: allEvents,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	return writeFormattedGoFile(outDir+"/capi_events_cgo_gen.go", buf.Bytes())
}

func eventArgsTypeName(eventName string) string {
	return "EventArgs_" + eventName
}

func buildCHandlerCallParams(args []model.EventArg) string {
	if len(args) == 0 {
		return ""
	}

	params := make([]string, 0, len(args))
	for _, arg := range args {
		paramName := arg.Name
		switch {
		case arg.Type == "void*":
			params = append(params, fmt.Sprintf("(args->list[0].%s ? *args->list[0].%s : NULL)", paramName, paramName))
		case arg.Type == "const char*":
			params = append(params, fmt.Sprintf("(args->list[0].%s ? *args->list[0].%s : NULL)", paramName, paramName))
		case arg.Type == "CAPIStringView":
			params = append(params, fmt.Sprintf("(args->list[0].%s ? *args->list[0].%s : (struct CAPIStringView){0, NULL})", paramName, paramName))
		case arg.Type == "bool":
			params = append(params, fmt.Sprintf("(args->list[0].%s ? *args->list[0].%s : false)", paramName, paramName))
		case strings.Contains(arg.Type, "int"):
			params = append(params, fmt.Sprintf("(args->list[0].%s ? *args->list[0].%s : 0)", paramName, paramName))
		case strings.Contains(arg.Type, "float"):
			params = append(params, fmt.Sprintf("(args->list[0].%s ? *args->list[0].%s : 0.0f)", paramName, paramName))
		default:
			params = append(params, fmt.Sprintf("(args->list[0].%s ? *args->list[0].%s : 0)", paramName, paramName))
		}
	}
	return strings.Join(params, ", ")
}

func buildExternSignature(eventName string, args []model.EventArg, badret string) string {
	retType := "void"
	if hasReturnValue(badret) {
		retType = "bool"
	}

	params := make([]string, 0, len(args))
	for _, arg := range args {
		paramName := arg.Name
		params = append(params, fmt.Sprintf("%s %s", mapping.CTypeToC(arg.Type), paramName))
	}

	if len(params) == 0 {
		params = append(params, "void")
	}

	return fmt.Sprintf("extern %s %s(%s);", retType, mapping.ExportName(eventName), strings.Join(params, ", "))
}

const capiEventsGoTemplate = `// Code generated by tools/codegen - DO NOT EDIT
package runtime

/*
#cgo CFLAGS: -I${SRCDIR}/include

#include <stdbool.h>
#include "ompcapi.h"

extern struct OMPAPI_t g_ompapi;
extern bool g_capi_initialised;

{{range .Events}}{{externSignature .Name .Args .BadRet}}
{{end}}

{{range .Events}}
static bool {{handlerName .Name}}_handler(struct {{eventArgsType .Name}}* args) {
	if (!args || args->size < 1 || args->list == NULL) {
		return {{if hasReturn .BadRet}}false{{else}}true{{end}};
	}
	{{if hasReturn .BadRet}}return {{exportName .Name}}({{cHandlerParams .Args}});{{else}}{{exportName .Name}}({{cHandlerParams .Args}}); return true;{{end}}
}

{{end}}
bool capi_register_all_handlers() {
	if (!g_capi_initialised || !g_ompapi.Event.AddHandler) {
		return false;
	}
	bool ok = true;
	{{range .Events}}ok = g_ompapi.Event.AddHandler("{{.Name}}", EventPriorityType_Default, (void*){{handlerName .Name}}_handler) && ok;
	{{end}}
	return ok;
}
*/
import "C"
`
