package generator

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/ompgo-dev/ompgo/tools/codegen/mapping"
	"github.com/ompgo-dev/ompgo/tools/codegen/model"
)

// generateRuntimeEventExports generates pkg/runtime/events_exports_gen.go with C exports.
func generateRuntimeEventExports(eventGroups map[string][]model.Event, outDir string) error {
	fmt.Println("Generating runtime C exports...")

	tmpl := template.Must(template.New("cmd_exports").Funcs(template.FuncMap{
		"cType":       mapping.MapGoTypeToCType,
		"cEventParam": buildCEventParam,
		"goCallParam": buildGoCallParam,
		"hasReturn":   hasReturnValue,
		"title":       mapping.Capitalize,
		"handlerName": mapping.HandlerName,
		"exportName":  mapping.ExportName,
	}).Parse(cmdExportsTemplate))

	allEvents := orderedEvents(eventGroups)

	data := struct {
		Events []model.Event
	}{
		Events: allEvents,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	return writeFormattedGoFile(outDir+"/events_exports_gen.go", buf.Bytes())
}

// buildCEventParam builds C function parameters
func buildCEventParam(args []model.EventArg) string {
	if len(args) == 0 {
		return ""
	}

	var params []string
	for _, arg := range args {
		paramName := mapping.SafeGoName(arg.Name)
		params = append(params, fmt.Sprintf("%s %s", paramName, mapping.CEventParamType(arg.Type)))
	}
	return strings.Join(params, ", ")
}

// buildGoCallParam builds the parameters for calling Go runtime method
func buildGoCallParam(args []model.EventArg) string {
	if len(args) == 0 {
		return ""
	}

	var params []string
	for _, arg := range args {
		paramName := mapping.SafeGoName(arg.Name)
		if arg.Type == "CAPIStringView" {
			params = append(params, fmt.Sprintf("borrowedStringViewFromCAPIStringView(%s)", paramName))
			continue
		}
		params = append(params, mapping.GoEventParamCast(paramName, arg.Type))
	}
	return strings.Join(params, ", ")
}

const cmdExportsTemplate = `// Code generated by tools/codegen - DO NOT EDIT
package runtime

/*
#cgo CFLAGS: -I${SRCDIR}/include

#include "ompcapi.h"
*/
import "C"

import (
	"log"
	"unsafe"
)

{{- range .Events}}
//export {{exportName .Name}}
func {{exportName .Name}}({{cEventParam .Args}}){{if hasReturn .BadRet}} C.bool{{end}} {
	defer func() {
		if r := recover(); r != nil {
			log.Printf("[ompgo] PANIC in {{handlerName .Name}}: %v", r)
		}
	}()

	{{- if hasReturn .BadRet }}
	result := Instance().{{handlerName .Name}}({{goCallParam .Args}})
	return C.bool(result)
	{{- else }}
	Instance().{{handlerName .Name}}({{goCallParam .Args}})
	{{- end }}
}
{{- end}}
`
