package generator

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/ompgo-dev/ompgo/tools/codegen/mapping"
	"github.com/ompgo-dev/ompgo/tools/codegen/model"
)

func generateEvents(eventGroups map[string][]model.Event, outDir string) error {
	f := jen.NewFile("omp")
	f.PackageComment("Code generated by tools/codegen - DO NOT EDIT")

	ordered := orderedEventMetas(eventGroups)
	count := 0
	for _, event := range ordered {
		count++
		structName := event.StructName

		fields := []jen.Code{}
		for _, arg := range event.Args {
			fieldName := arg.FieldName
			goType := mapping.CTypeToGoSafeWithEvent(arg.Type, arg.Name, event.Name)

			tag := map[string]string{"json": strings.ToLower(arg.Name)}
			fields = append(fields, jen.Id(fieldName).Add(goType).Tag(tag))
		}

		f.Commentf("%s is emitted when %s", structName, event.Name)
		f.Type().Id(structName).Struct(fields...)
	}

	filename := filepath.Join(outDir, "events_gen.go")
	fmt.Printf("Total: %d events\n", count)
	return f.Save(filename)
}

func generateEventHandlers(eventGroups map[string][]model.Event, outDir string) error {
	fmt.Println("Generating event handler interface...")

	f := jen.NewFile("omp")
	f.PackageComment("Code generated by tools/codegen - DO NOT EDIT")

	// Generate EventHandler interface with all events
	methods := []jen.Code{}
	ordered := orderedEventMetas(eventGroups)

	for _, event := range ordered {
		structName := event.StructName
		methodName := event.MethodName

		params := []jen.Code{
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("event").Op("*").Id(structName),
		}

		method := jen.Id(methodName).Params(params...)
		if event.BadRet != "none" {
			method = method.Params(jen.Bool(), jen.Error())
		} else {
			method = method.Error()
		}
		methods = append(methods, method)
	}

	f.Comment("EventHandler is the interface for handling all game events")
	f.Comment("Implement only the events you want to handle")
	f.Type().Id("EventHandler").Interface(methods...)

	// Generate BaseEventHandler with default implementations
	f.Comment("BaseEventHandler provides default no-op implementations for all events")
	f.Comment("Embed this to only implement events you care about")
	f.Type().Id("BaseEventHandler").Struct()

	// Generate default implementations
	for _, event := range ordered {
		structName := event.StructName
		methodName := event.MethodName

		params := []jen.Code{
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("event").Op("*").Id(structName),
		}
		fn := f.Func().Params(jen.Id("b").Op("*").Id("BaseEventHandler")).Id(methodName).Params(params...)
		if event.BadRet != "none" {
			fn.Params(jen.Bool(), jen.Error()).Block(jen.Return(jen.True(), jen.Nil()))
		} else {
			fn.Error().Block(jen.Return(jen.Nil()))
		}
	}

	filename := filepath.Join(outDir, "event_handlers_gen.go")
	return f.Save(filename)
}
