package generator

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
)

const constantsManifestPath = "tools/codegen/data/gamemode_constants.json"

type constantsConfig struct {
	Version  int               `json:"version"`
	Comments map[string]string `json:"comments"`
	Groups   []constantsGroup  `json:"groups"`
}

type constantsGroup struct {
	Name    string          `json:"name"`
	Type    string          `json:"type"`
	Comment string          `json:"comment,omitempty"`
	Items   []constantsItem `json:"items"`
}

type constantsItem struct {
	Name    string `json:"name"`
	Value   int    `json:"value"`
	Comment string `json:"comment,omitempty"`
}

func generateConstants(outDir string) error {
	cfg, err := loadConstantsConfig(constantsManifestPath)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("constants: create output dir %s: %w", outDir, err)
	}

	f := jen.NewFile("omp")
	f.PackageComment("Code generated by tools/codegen - DO NOT EDIT")

	if len(cfg.Comments) > 0 {
		keys := make([]string, 0, len(cfg.Comments))
		for k := range cfg.Comments {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := cfg.Comments[k]
			f.Comment(fmt.Sprintf("%s: %s", strings.TrimSpace(k), strings.TrimSpace(v)))
		}
	}

	for _, group := range cfg.Groups {
		if strings.TrimSpace(group.Name) == "" {
			continue
		}
		switch strings.ToLower(strings.TrimSpace(group.Type)) {
		case "enum":
			emitEnumGroup(f, group)
		case "bitflags":
			emitBitflagsGroup(f, group)
		default:
			return fmt.Errorf("constants: unsupported group type %q for %q", group.Type, group.Name)
		}
	}

	filename := filepath.Join(outDir, "constants_gen.go")
	return f.Save(filename)
}

func loadConstantsConfig(path string) (*constantsConfig, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("constants: read %s: %w", path, err)
	}

	var cfg constantsConfig
	if err := json.Unmarshal(b, &cfg); err != nil {
		return nil, fmt.Errorf("constants: parse %s: %w", path, err)
	}
	return &cfg, nil
}

func formatGroupComment(group constantsGroup, fallback string) string {
	if strings.TrimSpace(group.Comment) != "" {
		return strings.TrimSpace(group.Comment)
	}
	return fallback
}

func emitEnumGroup(f *jen.File, group constantsGroup) {
	f.Line()
	comment := formatGroupComment(group, fmt.Sprintf("%s represents %s values.", group.Name, group.Name))
	f.Comment(comment)
	f.Type().Id(group.Name).Int()

	if len(group.Items) == 0 {
		return
	}

	consts := make([]jen.Code, 0, len(group.Items))
	for _, item := range group.Items {
		if strings.TrimSpace(item.Name) == "" {
			continue
		}
		if item.Comment != "" {
			consts = append(consts, jen.Comment(item.Comment))
		}
		consts = append(consts, jen.Id(item.Name).Id(group.Name).Op("=").Lit(item.Value))
	}
	f.Const().Defs(consts...)
}

func emitBitflagsGroup(f *jen.File, group constantsGroup) {
	f.Line()
	comment := formatGroupComment(group, fmt.Sprintf("%s defines bitflags for %s.", group.Name, group.Name))
	f.Comment(comment)

	if len(group.Items) == 0 {
		return
	}

	consts := make([]jen.Code, 0, len(group.Items))
	for _, item := range group.Items {
		if strings.TrimSpace(item.Name) == "" {
			continue
		}
		if item.Comment != "" {
			consts = append(consts, jen.Comment(item.Comment))
		}
		consts = append(consts, jen.Id(item.Name).Op("=").Lit(item.Value))
	}
	f.Const().Defs(consts...)
}
