package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/ompgo-dev/ompgo/tools/codegen/mapping"
	"github.com/ompgo-dev/ompgo/tools/codegen/model"
)

type fnMeta struct {
	Group            string
	Function         model.APIFunction
	BaseName         string
	StringOutput     bool
	MethodName       string
	ParamTypes       []string
	ReturnType       string
	NeedsOMP         bool
	NeedsUnsafe      bool
	NeedsErrors      bool
	NeedsRuntime     bool
	HasStringParams  bool
	HasRuntimeParam  bool
	HasRuntimeReturn bool
}

// generateGamemodeBindings generates pkg/gamemode API wrappers.
func generateGamemodeBindings(apiGroups map[string][]model.APIFunction, outDir, modulePath string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if err := removeGeneratedGamemodeDomainDirs(outDir); err != nil {
		return err
	}
	if err := removeGeneratedGamemodeCompatibilityFiles(outDir); err != nil {
		return err
	}
	if err := generateGamemodeAPI(apiGroups, outDir, modulePath); err != nil {
		return err
	}
	return nil
}

func removeGeneratedGamemodeCompatibilityFiles(outDir string) error {
	for _, name := range []string{"constants_gen.go", "events_gen.go", "reexports_gen.go"} {
		if err := os.Remove(filepath.Join(outDir, name)); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

// generateGamemodeAPI generates high-level API wrappers in pkg/gamemode.
func generateGamemodeAPI(apiGroups map[string][]model.APIFunction, outDir, modulePath string) error {
	fmt.Println("Generating gamemode API wrappers...")

	funcs := make([]fnMeta, 0, 512)
	nameCounts := map[string]int{}

	for group, fns := range apiGroups {
		if group == "Component" {
			continue
		}
		for _, fn := range fns {
			if strings.Contains(fn.Name, "_Internal") {
				continue
			}
			baseName := mapping.SanitizeName(strings.TrimPrefix(fn.Name, group+"_"))
			stringOutput := mapping.HasStringOutput(fn)
			nameCounts[baseName]++
			funcs = append(funcs, fnMeta{
				Group:        group,
				Function:     fn,
				BaseName:     baseName,
				StringOutput: stringOutput,
			})
		}
	}

	filtered := make([]fnMeta, 0, len(funcs))
	for i := range funcs {
		meta := &funcs[i]
		meta.MethodName = meta.BaseName
		if nameCounts[meta.BaseName] > 1 {
			meta.MethodName = disambiguateGamemodeMethod(meta.BaseName, meta.Group)
		}

		meta.ParamTypes = make([]string, 0, len(meta.Function.Params))
		for _, p := range meta.Function.Params {
			if meta.StringOutput && (p.Type == "CAPIStringView*" || p.Type == "CAPIStringBuffer*") {
				continue
			}
			goType := gamemodeParamType(p.Type, p.Name, meta.Function.Name)
			meta.ParamTypes = append(meta.ParamTypes, goType)
			if isGamemodeHandleType(goType) {
				meta.NeedsOMP = true
			}
			if goType == "unsafe.Pointer" {
				meta.NeedsUnsafe = true
			}
			if mapping.IsStringParam(p.Type) {
				meta.HasStringParams = true
			}
			if strings.HasPrefix(goType, "runtime.") || strings.HasPrefix(goType, "*runtime.") {
				meta.HasRuntimeParam = true
			}
		}

		if meta.StringOutput {
			meta.ReturnType = "string"
			meta.NeedsErrors = true
		} else {
			meta.ReturnType = gamemodeReturnType(meta.Function.Ret, meta.Function.Name, meta.Group)
			if isGamemodeHandleType(meta.ReturnType) {
				meta.NeedsOMP = true
			}
			if meta.ReturnType == "unsafe.Pointer" {
				meta.NeedsUnsafe = true
			}
			if strings.HasPrefix(meta.ReturnType, "runtime.") || strings.HasPrefix(meta.ReturnType, "*runtime.") {
				meta.HasRuntimeReturn = true
			}
			meta.NeedsRuntime = meta.HasRuntimeParam || meta.HasRuntimeReturn || (meta.HasStringParams && !meta.StringOutput)
		}

		filtered = append(filtered, *meta)
	}
	funcs = filtered

	sort.SliceStable(funcs, func(i, j int) bool {
		if funcs[i].MethodName == funcs[j].MethodName {
			if funcs[i].Group == funcs[j].Group {
				return funcs[i].Function.Name < funcs[j].Function.Name
			}
			return funcs[i].Group < funcs[j].Group
		}
		return funcs[i].MethodName < funcs[j].MethodName
	})

	reservedNames := map[string]struct{}{
		"API":           {},
		"InitAPI":       {},
		"GetAPI":        {},
		"Initialize":    {},
		"IsInitialised": {},
		"Log":           {},
	}
	usedNames := map[string]int{}
	for i := range funcs {
		name := funcs[i].MethodName
		if _, reserved := reservedNames[name]; reserved {
			name = funcs[i].Group + name
		}
		if usedNames[name] > 0 {
			name = funcs[i].Group + name
		}
		if count := usedNames[name]; count > 0 {
			name = fmt.Sprintf("%s%d", name, count+1)
		}
		usedNames[name]++
		funcs[i].MethodName = name
	}

	ompPkg := modulePath + "/pkg/omp"
	runtimePkg := modulePath + "/pkg/runtime"

	f := jen.NewFile("gamemode")
	f.PackageComment("Code generated by tools/codegen - DO NOT EDIT")

	generateGamemodeAPIPrelude(f, runtimePkg)

	for _, meta := range funcs {
		fn := meta.Function

		params := []jen.Code{}
		callArgs := []jen.Code{}
		handleChecks := []jen.Code{}
		type stringOutArg struct {
			paramName string
			tempName  string
			tempType  string
			convFunc  string
		}
		stringOutArgs := []stringOutArg{}

		paramIndex := 0
		for _, p := range fn.Params {
			if meta.StringOutput && (p.Type == "CAPIStringView*" || p.Type == "CAPIStringBuffer*") {
				continue
			}
			paramName := mapping.SafeGoName(p.Name)
			goType := meta.ParamTypes[paramIndex]
			paramIndex++

			params = append(params, jen.Id(paramName).Add(typeExprFromString(goType, modulePath)))

			callArg := jen.Id(paramName)
			if p.Type == "CAPIStringView*" {
				tmpName := paramName + "View"
				callArg = jen.Op("&").Id(tmpName)
				stringOutArgs = append(stringOutArgs, stringOutArg{
					paramName: paramName,
					tempName:  tmpName,
					tempType:  "CAPIStringView",
					convFunc:  "CAPIStringViewToString",
				})
			} else if p.Type == "CAPIStringBuffer*" {
				tmpName := paramName + "Buffer"
				callArg = jen.Op("&").Id(tmpName)
				stringOutArgs = append(stringOutArgs, stringOutArg{
					paramName: paramName,
					tempName:  tmpName,
					tempType:  "CAPIStringBuffer",
					convFunc:  "CAPIStringBufferToString",
				})
			}
			if isGamemodeHandleType(goType) {
				callArg = jen.Id(paramName).Dot("Handle").Call()
				errName := invalidErrForType(goType)
				if errName != "" {
					handleChecks = append(handleChecks,
						jen.If(
							jen.Id(paramName).Op("==").Nil().Op("||").Op("!").Id(paramName).Dot("Valid").Call(),
						).Block(
							errReturnStatement(meta.ReturnType, errName),
						),
					)
				}
			}

			if mapping.IsStringParam(p.Type) && !meta.StringOutput {
				// runtime CAPI wrappers accept Go strings directly.
			}

			callArgs = append(callArgs, callArg)
		}

		returnParams := []jen.Code{}
		if meta.ReturnType == "" {
			returnParams = append(returnParams, jen.Error())
		} else {
			returnParams = append(returnParams, typeExprFromString(meta.ReturnType, modulePath), jen.Error())
		}

		method := jen.Func().
			Params(jen.Id("a").Op("*").Id("API")).
			Id(meta.MethodName).
			Params(params...).
			Params(returnParams...)

		body := []jen.Code{
			jen.If(jen.Op("!").Id("a").Dot("IsInitialised").Call()).Block(
				initReturnStatement(meta.ReturnType),
			),
		}
		body = append(body, handleChecks...)
		for _, out := range stringOutArgs {
			body = append(body, jen.Var().Id(out.tempName).Qual(runtimePkg, out.tempType))
		}
		assignStringOuts := func() []jen.Code {
			out := make([]jen.Code, 0, len(stringOutArgs))
			for _, arg := range stringOutArgs {
				out = append(out, jen.If(jen.Id(arg.paramName).Op("!=").Nil()).Block(
					jen.Op("*").Id(arg.paramName).Op("=").Qual(runtimePkg, arg.convFunc).Call(jen.Op("&").Id(arg.tempName)),
				))
			}
			return out
		}

		if meta.StringOutput {
			call := jen.Id("a").Dot("capi").Dot(fn.Name + "String").Call(callArgs...)
			body = append(body,
				jen.List(jen.Id("res"), jen.Id("ok")).Op(":=").Add(call),
				jen.If(jen.Op("!").Id("ok")).Block(
					jen.Return(
						jen.Lit(""),
						jen.Qual("errors", "New").Call(jen.Lit("gamemode: "+meta.MethodName+" failed")),
					),
				),
				jen.Return(jen.Id("res"), jen.Nil()),
			)
		} else if meta.ReturnType == "" {
			body = append(body,
				jen.Id("a").Dot("capi").Dot(fn.Name).Call(callArgs...),
			)
			body = append(body, assignStringOuts()...)
			body = append(body,
				jen.Return(jen.Nil()),
			)
		} else {
			call := jen.Id("a").Dot("capi").Dot(fn.Name).Call(callArgs...)
			wrapExpr, ok := wrapNewFuncExpr(meta.ReturnType, ompPkg)
			if ok {
				body = append(body, jen.Id("res").Op(":=").Add(call))
				body = append(body, assignStringOuts()...)
				body = append(body, jen.Return(wrapExpr.Call(jen.Id("res")), jen.Nil()))
			} else {
				body = append(body, jen.Id("res").Op(":=").Add(call))
				body = append(body, assignStringOuts()...)
				body = append(body, jen.Return(jen.Id("res"), jen.Nil()))
			}
		}

		f.Commentf("%s wraps CAPI %s", meta.MethodName, fn.Name)
		f.Add(method.Block(body...))
		f.Line()
	}

	filename := filepath.Join(outDir, "api_gen.go")
	return f.Save(filename)
}

func generateGamemodeAPIPrelude(f *jen.File, runtimePkg string) {
	f.Comment("Common API errors")
	f.Var().Defs(
		jen.Id("ErrNotImplemented").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: feature not yet implemented")),
		jen.Id("ErrInvalidPlayer").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid player handle")),
		jen.Id("ErrInvalidVehicle").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid vehicle handle")),
		jen.Id("ErrInvalidActor").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid actor handle")),
		jen.Id("ErrInvalidObject").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid object handle")),
		jen.Id("ErrInvalidPlayerObject").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid playerobject handle")),
		jen.Id("ErrInvalidPickup").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid pickup handle")),
		jen.Id("ErrInvalidTextDraw").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid textdraw handle")),
		jen.Id("ErrInvalidPlayerTextDraw").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid playertextdraw handle")),
		jen.Id("ErrInvalidTextLabel").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid textlabel handle")),
		jen.Id("ErrInvalidPlayerTextLabel").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid playertextlabel handle")),
		jen.Id("ErrInvalidGangZone").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid gangzone handle")),
		jen.Id("ErrInvalidMenu").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid menu handle")),
		jen.Id("ErrInvalidCheckpoint").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid checkpoint handle")),
		jen.Id("ErrInvalidClass").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid class handle")),
		jen.Id("ErrInvalidNPC").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: invalid npc handle")),
		jen.Id("ErrNotInitialised").Op("=").Qual("errors", "New").Call(jen.Lit("gamemode: API not Initialised")),
	)
	f.Line()

	f.Comment("API provides access to server functions for use in gamemodes.")
	f.Type().Id("API").Struct(
		jen.Id("capi").Op("*").Qual(runtimePkg, "CAPI"),
	)
	f.Line()

	f.Comment("apiInstance is the global API instance")
	f.Var().Id("apiInstance").Op("*").Id("API")
	f.Line()

	f.Comment("InitAPI initializes the API with a CAPI instance")
	f.Func().Id("InitAPI").Params(jen.Id("capi").Op("*").Qual(runtimePkg, "CAPI")).Block(
		jen.If(
			jen.Id("capi").Op("==").Nil().Op("||").Op("!").Id("capi").Dot("IsInitialised").Call(),
		).Block(
			jen.Panic(jen.Lit("gamemode: CAPI not Initialised")),
		),
		jen.Id("apiInstance").Op("=").Op("&").Id("API").Values(jen.Id("capi").Op(":").Id("capi")),
	)
	f.Line()

	f.Comment("GetAPI returns the gamemode API instance.")
	f.Func().Id("GetAPI").Params().Op("*").Id("API").Block(
		jen.Return(jen.Id("apiInstance")),
	)
	f.Line()

	f.Comment("Initialize returns the API instance or panics if it is not ready.")
	f.Func().Id("Initialize").Params().Op("*").Id("API").Block(
		jen.If(jen.Id("apiInstance").Op("==").Nil()).Block(
			jen.Panic(jen.Lit("gamemode: API not Initialised")),
		),
		jen.Return(jen.Id("apiInstance")),
	)
	f.Line()

	f.Func().Id("init").Params().Block(
		jen.Qual(runtimePkg, "RegisterAPIInit").Call(
			jen.Func().Params(
				jen.Id("ctx").Qual("context", "Context"),
				jen.Id("capi").Op("*").Qual(runtimePkg, "CAPI"),
			).Error().Block(
				jen.Id("_").Op("=").Id("ctx"),
				jen.Id("InitAPI").Call(jen.Id("capi")),
				jen.Return(jen.Nil()),
			),
		),
	)
	f.Line()

	f.Comment("IsInitialised returns whether the API has been properly Initialised")
	f.Func().Params(jen.Id("a").Op("*").Id("API")).Id("IsInitialised").Params().Bool().Block(
		jen.Return(
			jen.Id("a").Op("!=").Nil().
				Op("&&").Id("a").Dot("capi").Op("!=").Nil().
				Op("&&").Id("a").Dot("capi").Dot("IsInitialised").Call(),
		),
	)
	f.Line()

	f.Comment("Log writes a message to the open.mp server console.")
	f.Func().Params(jen.Id("a").Op("*").Id("API")).Id("Log").Params(jen.Id("message").String()).Error().Block(
		jen.If(jen.Op("!").Id("a").Dot("IsInitialised").Call()).Block(
			jen.Return(jen.Id("ErrNotInitialised")),
		),
		jen.If(jen.Op("!").Id("a").Dot("capi").Dot("Core_Log").Call(jen.Id("message"))).Block(
			jen.Return(jen.Qual("errors", "New").Call(jen.Lit("gamemode: failed to log message"))),
		),
		jen.Return(jen.Nil()),
	)
	f.Line()
}

func gamemodeParamType(cType, paramName, fnName string) string {
	if mapping.IsStringParam(cType) {
		return "string"
	}
	if cType == "void*" {
		return gamemodeVoidParamType(fnName, paramName)
	}
	if strings.HasSuffix(cType, "*") {
		base := strings.TrimSuffix(cType, "*")
		if base == "CAPIStringView" || base == "CAPIStringBuffer" {
			return "*string"
		}
		if base == "ComponentVersion" {
			return "*runtime.ComponentVersion"
		}
		return "*" + mapping.MapCTypeToGo(base)
	}
	return mapping.MapCTypeToGo(cType)
}

func gamemodeReturnType(cType, fnName, group string) string {
	if cType == "void" {
		return ""
	}
	if cType == "void*" {
		return gamemodeVoidReturnType(fnName, group)
	}
	if strings.HasSuffix(cType, "*") {
		base := strings.TrimSuffix(cType, "*")
		if base == "CAPIStringView" {
			return "*runtime.CAPIStringView"
		}
		if base == "CAPIStringBuffer" {
			return "*runtime.CAPIStringBuffer"
		}
		if base == "ComponentVersion" {
			return "*runtime.ComponentVersion"
		}
		return "*" + mapping.MapCTypeToGo(base)
	}
	return mapping.MapCTypeToGo(cType)
}

func gamemodeVoidParamType(fnName, paramName string) string {
	return helperVoidParamType(fnName, paramName)
}

func gamemodeVoidReturnType(fnName, group string) string {
	return helperVoidReturnType(fnName, group)
}

func disambiguateGamemodeMethod(baseName, group string) string {
	if strings.HasPrefix(baseName, group) || strings.Contains(baseName, group) {
		return baseName
	}

	for _, verb := range []string{
		"Get", "Set", "Is", "Has", "Show", "Hide", "Create", "Destroy", "Add",
		"Remove", "Send", "Give", "Put", "Toggle", "Enable", "Disable", "Update",
		"Edit", "Apply", "Reset", "Kick", "Ban", "Unban", "Play", "Stop", "Start",
		"Spawn", "Attach", "Detach", "Select", "Clear", "Force", "Allow", "Disallow",
	} {
		if strings.HasPrefix(baseName, verb) {
			return verb + group + strings.TrimPrefix(baseName, verb)
		}
	}

	return group + baseName
}

func isGamemodeHandleType(goType string) bool {
	switch goType {
	case "*omp.Player", "*omp.Vehicle", "*omp.Actor", "*omp.Object", "*omp.PlayerObject", "*omp.Pickup", "*omp.TextDraw", "*omp.PlayerTextDraw", "*omp.TextLabel", "*omp.PlayerTextLabel", "*omp.GangZone", "*omp.Menu", "*omp.Checkpoint", "*omp.NPC", "*omp.Class":
		return true
	default:
		return false
	}
}

func invalidErrForType(goType string) string {
	switch goType {
	case "*omp.Player":
		return "ErrInvalidPlayer"
	case "*omp.Vehicle":
		return "ErrInvalidVehicle"
	case "*omp.Actor":
		return "ErrInvalidActor"
	case "*omp.Object":
		return "ErrInvalidObject"
	case "*omp.PlayerObject":
		return "ErrInvalidPlayerObject"
	case "*omp.Pickup":
		return "ErrInvalidPickup"
	case "*omp.TextDraw":
		return "ErrInvalidTextDraw"
	case "*omp.PlayerTextDraw":
		return "ErrInvalidPlayerTextDraw"
	case "*omp.TextLabel":
		return "ErrInvalidTextLabel"
	case "*omp.PlayerTextLabel":
		return "ErrInvalidPlayerTextLabel"
	case "*omp.GangZone":
		return "ErrInvalidGangZone"
	case "*omp.Menu":
		return "ErrInvalidMenu"
	case "*omp.Checkpoint":
		return "ErrInvalidCheckpoint"
	case "*omp.Class":
		return "ErrInvalidClass"
	case "*omp.NPC":
		return "ErrInvalidNPC"
	default:
		return ""
	}
}

func typeExprFromString(goType, modulePath string) jen.Code {
	if goType == "" {
		return jen.Empty()
	}
	if strings.HasPrefix(goType, "*") {
		return jen.Op("*").Add(typeExprFromString(strings.TrimPrefix(goType, "*"), modulePath))
	}
	switch goType {
	case "handle.Handle":
		return jen.Qual(modulePath+"/pkg/handle", "Handle")
	case "string":
		return jen.String()
	case "bool":
		return jen.Bool()
	case "int":
		return jen.Int()
	case "int8":
		return jen.Int8()
	case "int16":
		return jen.Int16()
	case "int32":
		return jen.Int32()
	case "int64":
		return jen.Int64()
	case "uint":
		return jen.Uint()
	case "uint8":
		return jen.Uint8()
	case "uint16":
		return jen.Uint16()
	case "uint32":
		return jen.Uint32()
	case "uint64":
		return jen.Uint64()
	case "float32":
		return jen.Float32()
	case "float64":
		return jen.Float64()
	case "byte":
		return jen.Byte()
	case "unsafe.Pointer":
		return jen.Qual("unsafe", "Pointer")
	}

	if strings.HasPrefix(goType, "runtime.") {
		return jen.Qual(modulePath+"/pkg/runtime", strings.TrimPrefix(goType, "runtime."))
	}
	if strings.HasPrefix(goType, "omp.") {
		return jen.Qual(modulePath+"/pkg/omp", strings.TrimPrefix(goType, "omp."))
	}

	return jen.Id(goType)
}

func zeroValueExprFromString(goType string) jen.Code {
	if goType == "" {
		return jen.Empty()
	}
	if strings.HasPrefix(goType, "*") || goType == "unsafe.Pointer" {
		return jen.Nil()
	}
	switch goType {
	case "string":
		return jen.Lit("")
	case "bool":
		return jen.False()
	case "handle.Handle":
		return jen.Lit(0)
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "byte":
		return jen.Lit(0)
	default:
		return jen.Lit(0)
	}
}

func initReturnStatement(retType string) jen.Code {
	if retType == "" {
		return jen.Return(jen.Id("ErrNotInitialised"))
	}
	return jen.Return(zeroValueExprFromString(retType), jen.Id("ErrNotInitialised"))
}

func errReturnStatement(retType, errName string) jen.Code {
	if retType == "" {
		return jen.Return(jen.Id(errName))
	}
	return jen.Return(zeroValueExprFromString(retType), jen.Id(errName))
}

func wrapNewFuncExpr(retType, ompPkg string) (*jen.Statement, bool) {
	switch retType {
	case "*omp.Player":
		return jen.Qual(ompPkg, "NewPlayer"), true
	case "*omp.Vehicle":
		return jen.Qual(ompPkg, "NewVehicle"), true
	case "*omp.Actor":
		return jen.Qual(ompPkg, "NewActor"), true
	case "*omp.Object":
		return jen.Qual(ompPkg, "NewObject"), true
	case "*omp.PlayerObject":
		return jen.Qual(ompPkg, "NewPlayerObject"), true
	case "*omp.Pickup":
		return jen.Qual(ompPkg, "NewPickup"), true
	case "*omp.TextDraw":
		return jen.Qual(ompPkg, "NewTextDraw"), true
	case "*omp.PlayerTextDraw":
		return jen.Qual(ompPkg, "NewPlayerTextDraw"), true
	case "*omp.TextLabel":
		return jen.Qual(ompPkg, "NewTextLabel"), true
	case "*omp.PlayerTextLabel":
		return jen.Qual(ompPkg, "NewPlayerTextLabel"), true
	case "*omp.GangZone":
		return jen.Qual(ompPkg, "NewGangZone"), true
	case "*omp.Menu":
		return jen.Qual(ompPkg, "NewMenu"), true
	case "*omp.Checkpoint":
		return jen.Qual(ompPkg, "NewCheckpoint"), true
	case "*omp.NPC":
		return jen.Qual(ompPkg, "NewNPC"), true
	case "*omp.Class":
		return jen.Qual(ompPkg, "NewClass"), true
	default:
		return nil, false
	}
}
