package generator

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/ompgo-dev/ompgo/tools/codegen/mapping"
	"github.com/ompgo-dev/ompgo/tools/codegen/model"
)

func generateHelpers(outDir string, apiGroups map[string][]model.APIFunction, modulePath string) error {
	return generateDomainHelpers(outDir, apiGroups, modulePath)
}

var gamemodeAliasDomainDirs = []string{
	"actor",
	"all",
	"checkpoint",
	"class",
	"config",
	"core",
	"dialog",
	"gangzone",
	"menu",
	"object",
	"pickup",
	"playerobject",
	"players",
	"playertextdraw",
	"playertextlabel",
	"racecheckpoint",
	"textdraw",
	"textlabel",
	"vehicle",
}

func removeGeneratedGamemodeDomainDirs(outDir string) error {
	for _, dirName := range gamemodeAliasDomainDirs {
		if err := os.RemoveAll(filepath.Join(outDir, dirName)); err != nil {
			return err
		}
	}
	return nil
}

func generateDomainHelpers(outDir string, apiGroups map[string][]model.APIFunction, modulePath string) error {
	for group, functions := range apiGroups {
		if group == "Component" {
			continue
		}
		pkgName := domainPackageName(group)
		pkgDir := filepath.Join(outDir, pkgName)
		if err := os.MkdirAll(pkgDir, 0o755); err != nil {
			return err
		}

		var sb strings.Builder
		sb.WriteString("// Code generated by tools/codegen - DO NOT EDIT\n")
		sb.WriteString("package " + pkgName + "\n\n")
		hasOMP := false
		hasHandle := false
		for _, fn := range functions {
			if strings.Contains(fn.Name, "_Internal") {
				continue
			}
			isString := mapping.HasStringOutput(fn)
			retType := helperReturnType(fn.Ret, fn.Name, group)
			if retType != "" && strings.HasPrefix(retType, "*omp.") {
				hasOMP = true
			}
			if !isString && retType == "handle.Handle" {
				hasHandle = true
			}
			for _, p := range fn.Params {
				paramType := helperParamType(p.Type, p.Name, fn.Name)
				if strings.HasPrefix(paramType, "*omp.") {
					hasOMP = true
				}
				if !isString && paramType == "handle.Handle" {
					hasHandle = true
				}
			}
		}

		sb.WriteString("import (\n")
		if hasHandle {
			sb.WriteString(fmt.Sprintf("\t\"%s/pkg/handle\"\n\n", modulePath))
		}
		if hasOMP {
			sb.WriteString(fmt.Sprintf("\t\"%s/pkg/omp\"\n", modulePath))
		}
		sb.WriteString(fmt.Sprintf("\t\"%s/pkg/runtime\"\n", modulePath))
		sb.WriteString(")\n\n")

		for _, fn := range functions {
			if strings.Contains(fn.Name, "_Internal") {
				continue
			}

			if mapping.HasStringOutput(fn) {
				writeStringHelper(&sb, fn, group)
				continue
			}

			funcName := mapping.SanitizeName(strings.TrimPrefix(fn.Name, group+"_"))
			retType := helperReturnType(fn.Ret, fn.Name, group)
			params := []string{}
			callArgs := []string{}
			type stringOutParam struct {
				paramName string
				tempVar   string
				varType   string
				convFunc  string
			}
			stringOutParams := []stringOutParam{}
			wrapNew := helperNewFuncForType(retType)

			for _, p := range fn.Params {
				paramName := mapping.SafeGoName(p.Name)
				goType := helperParamType(p.Type, p.Name, fn.Name)
				params = append(params, fmt.Sprintf("%s %s", paramName, goType))
				callArg := paramName
				if p.Type == "CAPIStringView*" {
					viewVar := paramName + "View"
					callArg = "&" + viewVar
					stringOutParams = append(stringOutParams, stringOutParam{
						paramName: paramName,
						tempVar:   viewVar,
						varType:   "runtime.CAPIStringView",
						convFunc:  "runtime.CAPIStringViewToString",
					})
				} else if p.Type == "CAPIStringBuffer*" {
					bufVar := paramName + "Buffer"
					callArg = "&" + bufVar
					stringOutParams = append(stringOutParams, stringOutParam{
						paramName: paramName,
						tempVar:   bufVar,
						varType:   "runtime.CAPIStringBuffer",
						convFunc:  "runtime.CAPIStringBufferToString",
					})
				}
				if strings.HasPrefix(goType, "*omp.") {
					callArg = paramName + ".Handle()"
				}
				callArgs = append(callArgs, callArg)
			}

			sb.WriteString(fmt.Sprintf("// %s wraps CAPI %s\n", funcName, fn.Name))
			if retType == "" {
				sb.WriteString(fmt.Sprintf("func %s(%s) {\n", funcName, strings.Join(params, ", ")))
			} else {
				sb.WriteString(fmt.Sprintf("func %s(%s) %s {\n", funcName, strings.Join(params, ", "), retType))
			}

			sb.WriteString("\tc := runtime.Instance().CAPI()\n")
			for _, out := range stringOutParams {
				sb.WriteString("\tvar " + out.tempVar + " " + out.varType + "\n")
			}

			call := fmt.Sprintf("c.%s(%s)", fn.Name, strings.Join(callArgs, ", "))
			if retType == "" {
				sb.WriteString("\t" + call + "\n")
				for _, out := range stringOutParams {
					sb.WriteString("\tif " + out.paramName + " != nil { *" + out.paramName + " = " + out.convFunc + "(&" + out.tempVar + ") }\n")
				}
				sb.WriteString("}\n\n")
			} else {
				if wrapNew != "" {
					sb.WriteString("\tres := " + call + "\n")
					for _, out := range stringOutParams {
						sb.WriteString("\tif " + out.paramName + " != nil { *" + out.paramName + " = " + out.convFunc + "(&" + out.tempVar + ") }\n")
					}
					sb.WriteString("\treturn " + wrapNew + "(res)\n")
				} else {
					if len(stringOutParams) > 0 {
						sb.WriteString("\tres := " + call + "\n")
						for _, out := range stringOutParams {
							sb.WriteString("\tif " + out.paramName + " != nil { *" + out.paramName + " = " + out.convFunc + "(&" + out.tempVar + ") }\n")
						}
						sb.WriteString("\treturn res\n")
						sb.WriteString("}\n\n")
						continue
					}
					sb.WriteString("\treturn " + call + "\n")
				}
				sb.WriteString("}\n\n")
			}
		}

		src, err := format.Source([]byte(sb.String()))
		if err != nil {
			// Keep the raw output to aid debugging.
			_ = os.WriteFile(filepath.Join(pkgDir, "functions_gen.go"), []byte(sb.String()), 0o644)
			return err
		}
		if err := os.WriteFile(filepath.Join(pkgDir, "functions_gen.go"), src, 0o644); err != nil {
			return err
		}
	}

	return nil
}

func domainPackageName(group string) string {
	switch group {
	case "Player":
		return "players"
	default:
		return strings.ToLower(group)
	}
}

func helperParamType(cType, paramName, fnName string) string {
	if mapping.IsStringParam(cType) {
		return "string"
	}
	if cType == "void*" {
		return helperVoidParamType(fnName, paramName)
	}
	if strings.HasSuffix(cType, "*") {
		base := strings.TrimSuffix(cType, "*")
		if base == "CAPIStringView" || base == "CAPIStringBuffer" {
			return "*string"
		}
		if base == "ComponentVersion" {
			return "*runtime.ComponentVersion"
		}
		return "*" + mapping.MapCTypeToGo(base)
	}
	return mapping.MapCTypeToGo(cType)
}

func helperReturnType(cType, fnName, group string) string {
	if cType == "void" {
		return ""
	}
	if cType == "void*" {
		return helperVoidReturnType(fnName, group)
	}
	if strings.HasSuffix(cType, "*") {
		base := strings.TrimSuffix(cType, "*")
		if base == "CAPIStringView" {
			return "*runtime.CAPIStringView"
		}
		if base == "CAPIStringBuffer" {
			return "*runtime.CAPIStringBuffer"
		}
		if base == "ComponentVersion" {
			return "*runtime.ComponentVersion"
		}
		return "*" + mapping.MapCTypeToGo(base)
	}
	return mapping.MapCTypeToGo(cType)
}

func helperVoidParamType(fnName, paramName string) string {
	paramLower := strings.ToLower(paramName)
	if kind, ok := mapping.ResolveVoidPtrKindForAPI(fnName, paramLower); ok {
		return mapping.KindToHelperType(kind)
	}
	return "handle.Handle"
}

func helperVoidReturnType(fnName, group string) string {
	name := strings.ToLower(fnName)
	if kind, ok := mapping.ResolveVoidPtrKind("", name); ok {
		return mapping.KindToHelperType(kind)
	}

	switch group {
	case "Actor":
		return "*omp.Actor"
	case "Vehicle":
		return "*omp.Vehicle"
	case "Object":
		return "*omp.Object"
	case "Pickup":
		return "*omp.Pickup"
	case "TextDraw":
		return "*omp.TextDraw"
	case "TextLabel":
		return "*omp.TextLabel"
	case "GangZone":
		return "*omp.GangZone"
	case "Menu":
		return "*omp.Menu"
	case "Checkpoint":
		return "*omp.Checkpoint"
	case "Class":
		return "*omp.Class"
	case "NPC":
		return "*omp.NPC"
	default:
		return "handle.Handle"
	}
}

func writeStringHelper(sb *strings.Builder, fn model.APIFunction, group string) {
	baseName := mapping.SanitizeName(strings.TrimPrefix(fn.Name, group+"_"))
	funcName := baseName + "String"
	if group == "Player" && baseName == "GetName" {
		funcName = "GetName"
	}
	params := []string{}
	callArgs := []string{}

	for _, p := range fn.Params {
		if p.Type == "CAPIStringView*" || p.Type == "CAPIStringBuffer*" {
			continue
		}
		paramName := mapping.SafeGoName(p.Name)
		goType := helperParamType(p.Type, p.Name, fn.Name)
		params = append(params, fmt.Sprintf("%s %s", paramName, goType))
		callArg := paramName
		if strings.HasPrefix(goType, "*omp.") {
			callArg = paramName + ".Handle()"
		}
		callArgs = append(callArgs, callArg)
	}

	sb.WriteString(fmt.Sprintf("// %s wraps CAPI %s and returns a string.\n", funcName, fn.Name))
	sb.WriteString(fmt.Sprintf("func %s(%s) (string, bool) {\n", funcName, strings.Join(params, ", ")))
	sb.WriteString("\tc := runtime.Instance().CAPI()\n")
	call := fmt.Sprintf("c.%sString(%s)", fn.Name, strings.Join(callArgs, ", "))
	sb.WriteString("\treturn " + call + "\n")
	sb.WriteString("}\n\n")
}

func helperNewFuncForType(retType string) string {
	switch retType {
	case "*omp.Player":
		return "omp.NewPlayer"
	case "*omp.Vehicle":
		return "omp.NewVehicle"
	case "*omp.Actor":
		return "omp.NewActor"
	case "*omp.Object":
		return "omp.NewObject"
	case "*omp.PlayerObject":
		return "omp.NewPlayerObject"
	case "*omp.Pickup":
		return "omp.NewPickup"
	case "*omp.TextDraw":
		return "omp.NewTextDraw"
	case "*omp.PlayerTextDraw":
		return "omp.NewPlayerTextDraw"
	case "*omp.TextLabel":
		return "omp.NewTextLabel"
	case "*omp.PlayerTextLabel":
		return "omp.NewPlayerTextLabel"
	case "*omp.GangZone":
		return "omp.NewGangZone"
	case "*omp.Menu":
		return "omp.NewMenu"
	case "*omp.Checkpoint":
		return "omp.NewCheckpoint"
	case "*omp.NPC":
		return "omp.NewNPC"
	case "*omp.Class":
		return "omp.NewClass"
	default:
		return ""
	}
}
