package generator

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/ompgo-dev/ompgo/tools/codegen/mapping"
	"github.com/ompgo-dev/ompgo/tools/codegen/model"
)

// generateRuntimeEvents generates pkg/runtime/events.go with all event handlers.
func generateRuntimeEvents(eventGroups map[string][]model.Event, outDir, modulePath string) error {
	fmt.Println("Generating runtime events...")

	tmpl := template.Must(template.New("runtime_events").Funcs(template.FuncMap{
		"goType":        mapping.MapCTypeToGo,
		"goEventParam":  buildGoEventParam,
		"goEventStruct": buildGoEventStruct,
		"eventStruct":   mapping.EventStructName,
		"hasReturn":     hasReturnValue,
		"title":         mapping.Capitalize,
		"handlerName":   mapping.HandlerName,
		"handlerVar":    mapping.HandlerVarName,
		"registerName":  mapping.RegisterName,
		"returnDefault": getDefaultReturn,
	}).Parse(runtimeEventsTemplate(modulePath)))

	allEvents := orderedEventMetas(eventGroups)

	data := struct {
		Events []EventMeta
	}{
		Events: allEvents,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	return writeFormattedGoFile(outDir+"/events_gen.go", buf.Bytes())
}

// buildGoEventParam builds the Go function parameters from event args.
func buildGoEventParam(args []EventArgMeta) string {
	if len(args) == 0 {
		return ""
	}

	var params []string
	for _, arg := range args {
		if arg.Type == "CAPIStringView" {
			params = append(params, fmt.Sprintf("%s omp.BorrowedStringView", arg.ParamName))
			continue
		}
		goType := mapping.MapCTypeToGo(arg.Type)
		if strings.HasSuffix(arg.Type, "*") {
			params = append(params, fmt.Sprintf("%s unsafe.Pointer", arg.ParamName))
			continue
		}
		params = append(params, fmt.Sprintf("%s %s", arg.ParamName, goType))
	}
	return strings.Join(params, ", ")
}

// buildGoEventStruct builds the event struct initialization.
func buildGoEventStruct(eventName string, args []EventArgMeta) string {
	structName := mapping.EventStructName(eventName)

	if len(args) == 0 {
		return fmt.Sprintf("&omp.%s{}", structName)
	}

	var fields []string
	for _, arg := range args {
		fieldName := arg.FieldName
		paramName := arg.ParamName

		switch arg.Type {
		case "void*":
			if ctor, ok := mapping.ConstructorForVoidPtr(eventName, arg.Name); ok {
				fields = append(fields, fmt.Sprintf("\t\t%s: %s(handleFromPtr(%s)),", fieldName, ctor, paramName))
				continue
			}
			fields = append(fields, fmt.Sprintf("\t\t%s: handleFromPtr(%s),", fieldName, paramName))
		case "const char*", "CAPIStringView":
			fields = append(fields, fmt.Sprintf("\t\t%s: %s,", fieldName, paramName))
		default:
			fields = append(fields, fmt.Sprintf("\t\t%s: %s,", fieldName, paramName))
		}
	}

	return fmt.Sprintf("&omp.%s{\n%s\n\t}", structName, strings.Join(fields, "\n"))
}

// hasReturnValue checks if an event has a return value.
func hasReturnValue(badret string) bool {
	return badret != "none"
}

// getDefaultReturn gets the default return value for an event.
func getDefaultReturn(badret string) string {
	switch badret {
	case "true", "1":
		return "true"
	case "false", "0":
		return "false"
	default:
		return "true"
	}
}

func runtimeEventsTemplate(modulePath string) string {
	return fmt.Sprintf(`// Code generated by tools/codegen - DO NOT EDIT
// Package runtime provides event forwarding from C++ to Go gamemodes
package runtime

import (
	"context"
	"sync"
	"sync/atomic"
	"unsafe"

	"%s/pkg/omp"
)

{{range .Events}}
type {{handlerVar .Name}}Func func(context.Context, *omp.{{eventStruct .Name}}){{if hasReturn .BadRet}} (bool, error){{else}} error{{end}}

{{end}}

var (
	eventHandlerMu  sync.Mutex
	eventHandlerSeq atomic.Int64
{{range .Events}}
	{{handlerVar .Name}} atomic.Pointer[handlerSnapshot[{{handlerVar .Name}}Func]]
{{end}}
)

{{range .Events}}
// {{handlerName .Name}}Handler is implemented by types that handle {{handlerName .Name}}.
type {{handlerName .Name}}Handler interface {
	{{handlerName .Name}}(ctx context.Context, event *omp.{{eventStruct .Name}}){{if hasReturn .BadRet}} (bool, error){{else}} error{{end}}
}

{{end}}

{{range .Events}}
// {{registerName .Name}} registers a handler for {{handlerName .Name}}.
// The returned function unregisters the handler.
func {{registerName .Name}}(handler {{handlerVar .Name}}Func) func() {
	if handler == nil {
		return func() {}
	}
	return registerHandler(&eventHandlerMu, &eventHandlerSeq, &{{handlerVar .Name}}, handler)
}

{{end}}

// AttachHandlers registers all supported event handlers implemented by handler.
// It returns a function that unregisters all registered handlers.
func AttachHandlers(handler interface{}) func() {
	if handler == nil {
		return func() {}
	}
	unregisters := []func(){}
	{{range .Events}}
	if h, ok := handler.({{handlerName .Name}}Handler); ok {
		unregisters = append(unregisters, {{registerName .Name}}(h.{{handlerName .Name}}))
	}
	{{end}}

	return func() {
		for i := len(unregisters) - 1; i >= 0; i-- {
			unregisters[i]()
		}
	}
}

{{range .Events}}
// {{handlerName .Name}} forwards {{.Name}} events
func (r *Runtime) {{handlerName .Name}}({{goEventParam .Args}}){{if hasReturn .BadRet}} bool{{end}} {
	gm := r.currentGamemode()
	cfg := currentEventDispatchConfig()

	event := {{goEventStruct .Name .Args}}
	ctx := newEventContext(cfg, "{{handlerName .Name}}")
	if cfg.decorator != nil {
		ctx = decorateEventContext(cfg, ctx, "{{handlerName .Name}}", event)
	}
	{{if hasReturn .BadRet}}
	blocked := false
	for _, registered := range loadHandlerSnapshot(&{{handlerVar .Name}}) {
		allowed, err := invokeBlockingHandler(ctx, "{{handlerName .Name}}", event, true, registered.fn)
		if err != nil {
			reportEventErrorWithConfig(ctx, cfg, "{{handlerName .Name}}", event, err)
			if eventErrorPolicyBlocks(cfg) {
				blocked = true
				break
			}
		}
		if !allowed {
			blocked = true
			break
		}
	}
	if blocked {
		return false
	}
	if gm == nil {
		return {{returnDefault .BadRet}}
	}
	allowed, err := invokeBlockingHandler(ctx, "{{handlerName .Name}}", event, {{returnDefault .BadRet}}, gm.{{handlerName .Name}})
	if err != nil {
		reportEventErrorWithConfig(ctx, cfg, "{{handlerName .Name}}", event, err)
		if eventErrorPolicyBlocks(cfg) {
			return false
		}
	}
	return allowed
	{{else}}
	for _, registered := range loadHandlerSnapshot(&{{handlerVar .Name}}) {
		if err := invokeHandler(ctx, "{{handlerName .Name}}", event, registered.fn); err != nil {
			reportEventErrorWithConfig(ctx, cfg, "{{handlerName .Name}}", event, err)
			if eventErrorPolicyBlocks(cfg) {
				return
			}
		}
	}
	if gm == nil {
		return
	}
	if err := invokeHandler(ctx, "{{handlerName .Name}}", event, gm.{{handlerName .Name}}); err != nil {
		reportEventErrorWithConfig(ctx, cfg, "{{handlerName .Name}}", event, err)
	}
	{{end}}
}
{{end}}
`, modulePath)
}
