package generator

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/dave/jennifer/jen"
)

func generateTypes(outDir, modulePath string) error {
	fmt.Println("Generating safe wrapper types...")

	f := jen.NewFile("omp")
	f.PackageComment("Code generated by tools/codegen - DO NOT EDIT")
	handlePkg := modulePath + "/pkg/handle"
	f.ImportName(handlePkg, "handle")

	entities := []string{"Player", "Vehicle", "Actor", "Object", "PlayerObject", "Pickup", "TextDraw", "PlayerTextDraw", "TextLabel", "PlayerTextLabel", "GangZone", "Menu", "Checkpoint", "NPC", "Class"}

	for _, entity := range entities {
		f.Commentf("%s is a safe wrapper around an open.mp %s handle", entity, strings.ToLower(entity))
		f.Type().Id(entity).Struct(
			jen.Id("handle").Qual(handlePkg, "Handle"),
		)

		f.Commentf("New%s creates a %s from an opaque handle", entity, entity)
		f.Func().Id("New"+entity).Params(
			jen.Id("handle").Qual(handlePkg, "Handle"),
		).Op("*").Id(entity).Block(
			jen.If(jen.Id("handle").Op("==").Lit(0)).Block(
				jen.Return(jen.Nil()),
			),
			jen.Return(jen.Op("&").Id(entity).Values(jen.Id("handle").Op(":").Id("handle"))),
		)

		f.Commentf("Handle returns the underlying handle")
		f.Func().Params(jen.Id("e").Op("*").Id(entity)).Id("Handle").Params().Qual(handlePkg, "Handle").Block(
			jen.If(jen.Id("e").Op("==").Nil()).Block(
				jen.Return(jen.Lit(0)),
			),
			jen.Return(jen.Id("e").Dot("handle")),
		)

		f.Commentf("Valid returns true if the handle is not nil")
		f.Func().Params(jen.Id("e").Op("*").Id(entity)).Id("Valid").Params().Bool().Block(
			jen.Return(jen.Id("e").Op("!=").Nil().Op("&&").Id("e").Dot("handle").Op("!=").Lit(0)),
		)
	}

	// Common types
	f.Comment("Vector3 represents a 3D position")
	f.Type().Id("Vector3").Struct(
		jen.Id("X").Float32().Tag(map[string]string{"json": "x"}),
		jen.Id("Y").Float32().Tag(map[string]string{"json": "y"}),
		jen.Id("Z").Float32().Tag(map[string]string{"json": "z"}),
	)

	f.Comment("Vector4 represents a 4D vector (often rotation)")
	f.Type().Id("Vector4").Struct(
		jen.Id("X").Float32().Tag(map[string]string{"json": "x"}),
		jen.Id("Y").Float32().Tag(map[string]string{"json": "y"}),
		jen.Id("Z").Float32().Tag(map[string]string{"json": "z"}),
		jen.Id("W").Float32().Tag(map[string]string{"json": "w"}),
	)

	f.Comment("Color represents an RGBA color")
	f.Type().Id("Color").Uint32()

	f.Comment("RGBA creates a Color from RGBA components")
	f.Func().Id("RGBA").Params(
		jen.Id("r").Uint8(),
		jen.Id("g").Uint8(),
		jen.Id("b").Uint8(),
		jen.Id("a").Uint8(),
	).Id("Color").Block(
		jen.Return(jen.Id("Color").Call(
			jen.Uint32().Call(jen.Id("r")).Op("<<").Lit(24).Op("|").
				Uint32().Call(jen.Id("g")).Op("<<").Lit(16).Op("|").
				Uint32().Call(jen.Id("b")).Op("<<").Lit(8).Op("|").
				Uint32().Call(jen.Id("a")),
		)),
	)

	f.Comment("RGB creates a Color from RGB components with full alpha")
	f.Func().Id("RGB").Params(
		jen.Id("r").Uint8(),
		jen.Id("g").Uint8(),
		jen.Id("b").Uint8(),
	).Id("Color").Block(
		jen.Return(jen.Id("RGBA").Call(jen.Id("r"), jen.Id("g"), jen.Id("b"), jen.Lit(255))),
	)

	// Common color constants
	f.Comment("Common color constants")
	f.Const().DefsFunc(func(g *jen.Group) {
		colors := []struct {
			name  string
			value uint32
		}{
			{name: "ColorWhite", value: 0xFFFFFFFF},
			{name: "ColorBlack", value: 0x000000FF},
			{name: "ColorRed", value: 0xFF0000FF},
			{name: "ColorGreen", value: 0x00FF00FF},
			{name: "ColorBlue", value: 0x0000FFFF},
			{name: "ColorYellow", value: 0xFFFF00FF},
			{name: "ColorOrange", value: 0xFF8000FF},
			{name: "ColorPurple", value: 0x8000FFFF},
			{name: "ColorGrey", value: 0xAAAAAFFF},
		}
		for _, color := range colors {
			g.Id(color.name).Op("=").Id("Color").Call(jen.Lit(color.value))
		}
	})

	filename := filepath.Join(outDir, "types_gen.go")
	return f.Save(filename)
}
