// Code generated by tools/codegen - DO NOT EDIT
package playertextlabel

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI PlayerTextLabel_Create
func Create(player *omp.Player, text string, color uint32, x float32, y float32, z float32, drawDistance float32, attachedPlayer *omp.Player, attachedVehicle *omp.Vehicle, los bool, id *int32) *omp.PlayerTextLabel {
	c := runtime.Instance().CAPI()
	res := c.PlayerTextLabel_Create(player.Handle(), text, color, x, y, z, drawDistance, attachedPlayer.Handle(), attachedVehicle.Handle(), los, id)
	return omp.NewPlayerTextLabel(res)
}

// Destroy wraps CAPI PlayerTextLabel_Destroy
func Destroy(player *omp.Player, textlabel *omp.PlayerTextLabel) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_Destroy(player.Handle(), textlabel.Handle())
}

// FromID wraps CAPI PlayerTextLabel_FromID
func FromID(player *omp.Player, textlabelid int32) *omp.PlayerTextLabel {
	c := runtime.Instance().CAPI()
	res := c.PlayerTextLabel_FromID(player.Handle(), textlabelid)
	return omp.NewPlayerTextLabel(res)
}

// GetID wraps CAPI PlayerTextLabel_GetID
func GetID(player *omp.Player, textlabel *omp.PlayerTextLabel) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_GetID(player.Handle(), textlabel.Handle())
}

// UpdateText wraps CAPI PlayerTextLabel_UpdateText
func UpdateText(player *omp.Player, textlabel *omp.PlayerTextLabel, color uint32, text string) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_UpdateText(player.Handle(), textlabel.Handle(), color, text)
}

// IsValid wraps CAPI PlayerTextLabel_IsValid
func IsValid(player *omp.Player, textlabel *omp.PlayerTextLabel, valid *bool) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_IsValid(player.Handle(), textlabel.Handle(), valid)
}

// GetTextString wraps CAPI PlayerTextLabel_GetText and returns a string.
func GetTextString(player *omp.Player, textlabel *omp.PlayerTextLabel) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_GetTextString(player.Handle(), textlabel.Handle())
}

// GetColor wraps CAPI PlayerTextLabel_GetColor
func GetColor(player *omp.Player, textlabel *omp.PlayerTextLabel, color *uint32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_GetColor(player.Handle(), textlabel.Handle(), color)
}

// GetPos wraps CAPI PlayerTextLabel_GetPos
func GetPos(player *omp.Player, textlabel *omp.PlayerTextLabel, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_GetPos(player.Handle(), textlabel.Handle(), x, y, z)
}

// SetDrawDistance wraps CAPI PlayerTextLabel_SetDrawDistance
func SetDrawDistance(player *omp.Player, textlabel *omp.PlayerTextLabel, distance float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_SetDrawDistance(player.Handle(), textlabel.Handle(), distance)
}

// GetDrawDistance wraps CAPI PlayerTextLabel_GetDrawDistance
func GetDrawDistance(player *omp.Player, textlabel *omp.PlayerTextLabel) float32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_GetDrawDistance(player.Handle(), textlabel.Handle())
}

// GetLOS wraps CAPI PlayerTextLabel_GetLOS
func GetLOS(player *omp.Player, textlabel *omp.PlayerTextLabel) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_GetLOS(player.Handle(), textlabel.Handle())
}

// SetLOS wraps CAPI PlayerTextLabel_SetLOS
func SetLOS(player *omp.Player, textlabel *omp.PlayerTextLabel, status bool) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_SetLOS(player.Handle(), textlabel.Handle(), status)
}

// GetVirtualWorld wraps CAPI PlayerTextLabel_GetVirtualWorld
func GetVirtualWorld(player *omp.Player) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_GetVirtualWorld(player.Handle())
}

// GetAttachedData wraps CAPI PlayerTextLabel_GetAttachedData
func GetAttachedData(player *omp.Player, textlabel *omp.PlayerTextLabel, attachedPlayer *int32, attachedVehicle *int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextLabel_GetAttachedData(player.Handle(), textlabel.Handle(), attachedPlayer, attachedVehicle)
}
