// Code generated by tools/codegen - DO NOT EDIT
package racecheckpoint

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Set wraps CAPI RaceCheckpoint_Set
func Set(player *omp.Player, typ int32, x float32, y float32, z float32, nextX float32, nextY float32, nextZ float32, radius float32) bool {
	c := runtime.Instance().CAPI()
	return c.RaceCheckpoint_Set(player.Handle(), typ, x, y, z, nextX, nextY, nextZ, radius)
}

// Disable wraps CAPI RaceCheckpoint_Disable
func Disable(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.RaceCheckpoint_Disable(player.Handle())
}

// IsPlayerIn wraps CAPI RaceCheckpoint_IsPlayerIn
func IsPlayerIn(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.RaceCheckpoint_IsPlayerIn(player.Handle())
}

// IsActive wraps CAPI RaceCheckpoint_IsActive
func IsActive(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.RaceCheckpoint_IsActive(player.Handle())
}

// Get wraps CAPI RaceCheckpoint_Get
func Get(player *omp.Player, x *float32, y *float32, z *float32, nextX *float32, nextY *float32, nextZ *float32, radius *float32) bool {
	c := runtime.Instance().CAPI()
	return c.RaceCheckpoint_Get(player.Handle(), x, y, z, nextX, nextY, nextZ, radius)
}
