// Code generated by tools/codegen - DO NOT EDIT
package object

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI Object_Create
func Create(modelid int32, x float32, y float32, z float32, rotationX float32, rotationY float32, rotationZ float32, drawDistance float32, id *int32) *omp.Object {
	c := runtime.Instance().CAPI()
	res := c.Object_Create(modelid, x, y, z, rotationX, rotationY, rotationZ, drawDistance, id)
	return omp.NewObject(res)
}

// Destroy wraps CAPI Object_Destroy
func Destroy(object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Object_Destroy(object.Handle())
}

// FromID wraps CAPI Object_FromID
func FromID(objectid int32) *omp.Object {
	c := runtime.Instance().CAPI()
	res := c.Object_FromID(objectid)
	return omp.NewObject(res)
}

// GetID wraps CAPI Object_GetID
func GetID(object *omp.Object) int32 {
	c := runtime.Instance().CAPI()
	return c.Object_GetID(object.Handle())
}

// AttachToVehicle wraps CAPI Object_AttachToVehicle
func AttachToVehicle(object *omp.Object, vehicle *omp.Vehicle, offsetX float32, offsetY float32, offsetZ float32, rotationX float32, rotationY float32, rotationZ float32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_AttachToVehicle(object.Handle(), vehicle.Handle(), offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ)
}

// AttachToObject wraps CAPI Object_AttachToObject
func AttachToObject(object *omp.Object, objAttachedTo *omp.Object, offsetX float32, offsetY float32, offsetZ float32, rotationX float32, rotationY float32, rotationZ float32, syncRotation bool) bool {
	c := runtime.Instance().CAPI()
	return c.Object_AttachToObject(object.Handle(), objAttachedTo.Handle(), offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ, syncRotation)
}

// AttachToPlayer wraps CAPI Object_AttachToPlayer
func AttachToPlayer(object *omp.Object, player *omp.Player, offsetX float32, offsetY float32, offsetZ float32, rotationX float32, rotationY float32, rotationZ float32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_AttachToPlayer(object.Handle(), player.Handle(), offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ)
}

// SetPos wraps CAPI Object_SetPos
func SetPos(object *omp.Object, x float32, y float32, z float32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_SetPos(object.Handle(), x, y, z)
}

// GetPos wraps CAPI Object_GetPos
func GetPos(object *omp.Object, x *float32, y *float32, z *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_GetPos(object.Handle(), x, y, z)
}

// SetRot wraps CAPI Object_SetRot
func SetRot(object *omp.Object, rotationX float32, rotationY float32, rotationZ float32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_SetRot(object.Handle(), rotationX, rotationY, rotationZ)
}

// GetRot wraps CAPI Object_GetRot
func GetRot(object *omp.Object, rotationX *float32, rotationY *float32, rotationZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_GetRot(object.Handle(), rotationX, rotationY, rotationZ)
}

// GetModel wraps CAPI Object_GetModel
func GetModel(object *omp.Object) int32 {
	c := runtime.Instance().CAPI()
	return c.Object_GetModel(object.Handle())
}

// SetNoCameraCollision wraps CAPI Object_SetNoCameraCollision
func SetNoCameraCollision(object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Object_SetNoCameraCollision(object.Handle())
}

// IsValid wraps CAPI Object_IsValid
func IsValid(object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Object_IsValid(object.Handle())
}

// Move wraps CAPI Object_Move
func Move(object *omp.Object, x float32, y float32, z float32, speed float32, rotationX float32, rotationY float32, rotationZ float32) int32 {
	c := runtime.Instance().CAPI()
	return c.Object_Move(object.Handle(), x, y, z, speed, rotationX, rotationY, rotationZ)
}

// Stop wraps CAPI Object_Stop
func Stop(object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Object_Stop(object.Handle())
}

// IsMoving wraps CAPI Object_IsMoving
func IsMoving(object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Object_IsMoving(object.Handle())
}

// BeginEditing wraps CAPI Object_BeginEditing
func BeginEditing(player *omp.Player, object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Object_BeginEditing(player.Handle(), object.Handle())
}

// BeginSelecting wraps CAPI Object_BeginSelecting
func BeginSelecting(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Object_BeginSelecting(player.Handle())
}

// EndEditing wraps CAPI Object_EndEditing
func EndEditing(player *omp.Player) bool {
	c := runtime.Instance().CAPI()
	return c.Object_EndEditing(player.Handle())
}

// SetMaterial wraps CAPI Object_SetMaterial
func SetMaterial(object *omp.Object, materialIndex int32, modelID int32, textureLibrary string, textureName string, materialColor uint32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_SetMaterial(object.Handle(), materialIndex, modelID, textureLibrary, textureName, materialColor)
}

// SetMaterialText wraps CAPI Object_SetMaterialText
func SetMaterialText(object *omp.Object, text string, materialIndex int32, materialSize int32, fontface string, fontsize int32, bold bool, fontColor uint32, backgroundColor uint32, textalignment int32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_SetMaterialText(object.Handle(), text, materialIndex, materialSize, fontface, fontsize, bold, fontColor, backgroundColor, textalignment)
}

// SetDefaultCameraCollision wraps CAPI Object_SetDefaultCameraCollision
func SetDefaultCameraCollision(disable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Object_SetDefaultCameraCollision(disable)
}

// GetDrawDistance wraps CAPI Object_GetDrawDistance
func GetDrawDistance(object *omp.Object) float32 {
	c := runtime.Instance().CAPI()
	return c.Object_GetDrawDistance(object.Handle())
}

// GetMoveSpeed wraps CAPI Object_GetMoveSpeed
func GetMoveSpeed(object *omp.Object) float32 {
	c := runtime.Instance().CAPI()
	return c.Object_GetMoveSpeed(object.Handle())
}

// GetMovingTargetPos wraps CAPI Object_GetMovingTargetPos
func GetMovingTargetPos(object *omp.Object, targetX *float32, targetY *float32, targetZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_GetMovingTargetPos(object.Handle(), targetX, targetY, targetZ)
}

// GetMovingTargetRot wraps CAPI Object_GetMovingTargetRot
func GetMovingTargetRot(object *omp.Object, rotationX *float32, rotationY *float32, rotationZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_GetMovingTargetRot(object.Handle(), rotationX, rotationY, rotationZ)
}

// GetAttachedData wraps CAPI Object_GetAttachedData
func GetAttachedData(object *omp.Object, parentVehicle *int32, parentObject *int32, parentPlayer *int32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_GetAttachedData(object.Handle(), parentVehicle, parentObject, parentPlayer)
}

// GetAttachedOffset wraps CAPI Object_GetAttachedOffset
func GetAttachedOffset(object *omp.Object, offsetX *float32, offsetY *float32, offsetZ *float32, rotationX *float32, rotationY *float32, rotationZ *float32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_GetAttachedOffset(object.Handle(), offsetX, offsetY, offsetZ, rotationX, rotationY, rotationZ)
}

// GetSyncRotation wraps CAPI Object_GetSyncRotation
func GetSyncRotation(object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Object_GetSyncRotation(object.Handle())
}

// IsMaterialSlotUsed wraps CAPI Object_IsMaterialSlotUsed
func IsMaterialSlotUsed(object *omp.Object, materialIndex int32) bool {
	c := runtime.Instance().CAPI()
	return c.Object_IsMaterialSlotUsed(object.Handle(), materialIndex)
}

// GetMaterial wraps CAPI Object_GetMaterial
func GetMaterial(object *omp.Object, materialIndex int32, modelid *int32, textureLibrary *string, textureName *string, materialColor *int32) bool {
	c := runtime.Instance().CAPI()
	var textureLibraryView runtime.CAPIStringView
	var textureNameView runtime.CAPIStringView
	res := c.Object_GetMaterial(object.Handle(), materialIndex, modelid, &textureLibraryView, &textureNameView, materialColor)
	if textureLibrary != nil {
		*textureLibrary = runtime.CAPIStringViewToString(&textureLibraryView)
	}
	if textureName != nil {
		*textureName = runtime.CAPIStringViewToString(&textureNameView)
	}
	return res
}

// GetMaterialText wraps CAPI Object_GetMaterialText
func GetMaterialText(object *omp.Object, materialIndex int32, text *string, materialSize *int32, fontFace *string, fontSize *int32, bold *bool, fontColor *int32, backgroundColor *int32, textAlignment *int32) bool {
	c := runtime.Instance().CAPI()
	var textView runtime.CAPIStringView
	var fontFaceView runtime.CAPIStringView
	res := c.Object_GetMaterialText(object.Handle(), materialIndex, &textView, materialSize, &fontFaceView, fontSize, bold, fontColor, backgroundColor, textAlignment)
	if text != nil {
		*text = runtime.CAPIStringViewToString(&textView)
	}
	if fontFace != nil {
		*fontFace = runtime.CAPIStringViewToString(&fontFaceView)
	}
	return res
}

// IsObjectNoCameraCollision wraps CAPI Object_IsObjectNoCameraCollision
func IsObjectNoCameraCollision(object *omp.Object) bool {
	c := runtime.Instance().CAPI()
	return c.Object_IsObjectNoCameraCollision(object.Handle())
}

// GetType wraps CAPI Object_GetType
func GetType(player *omp.Player, objectid int32) uint8 {
	c := runtime.Instance().CAPI()
	return c.Object_GetType(player.Handle(), objectid)
}
