// Code generated by tools/codegen - DO NOT EDIT
package config

import (
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// GetAsBool wraps CAPI Config_GetAsBool
func GetAsBool(cvar string) bool {
	c := runtime.Instance().CAPI()
	return c.Config_GetAsBool(cvar)
}

// GetAsInt wraps CAPI Config_GetAsInt
func GetAsInt(cvar string) int32 {
	c := runtime.Instance().CAPI()
	return c.Config_GetAsInt(cvar)
}

// GetAsFloat wraps CAPI Config_GetAsFloat
func GetAsFloat(cvar string) float32 {
	c := runtime.Instance().CAPI()
	return c.Config_GetAsFloat(cvar)
}

// GetAsStringString wraps CAPI Config_GetAsString and returns a string.
func GetAsStringString(cvar string) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Config_GetAsStringString(cvar)
}
