// Code generated by tools/codegen - DO NOT EDIT
package core

import (
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// TickCount wraps CAPI Core_TickCount
func TickCount() uint32 {
	c := runtime.Instance().CAPI()
	return c.Core_TickCount()
}

// MaxPlayers wraps CAPI Core_MaxPlayers
func MaxPlayers() int32 {
	c := runtime.Instance().CAPI()
	return c.Core_MaxPlayers()
}

// Log wraps CAPI Core_Log
func Log(text string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_Log(text)
}

// IsAdminTeleportAllowed wraps CAPI Core_IsAdminTeleportAllowed
func IsAdminTeleportAllowed() bool {
	c := runtime.Instance().CAPI()
	return c.Core_IsAdminTeleportAllowed()
}

// AllowAdminTeleport wraps CAPI Core_AllowAdminTeleport
func AllowAdminTeleport(allow bool) bool {
	c := runtime.Instance().CAPI()
	return c.Core_AllowAdminTeleport(allow)
}

// AreAllAnimationsEnabled wraps CAPI Core_AreAllAnimationsEnabled
func AreAllAnimationsEnabled() bool {
	c := runtime.Instance().CAPI()
	return c.Core_AreAllAnimationsEnabled()
}

// EnableAllAnimations wraps CAPI Core_EnableAllAnimations
func EnableAllAnimations(allow bool) bool {
	c := runtime.Instance().CAPI()
	return c.Core_EnableAllAnimations(allow)
}

// IsAnimationLibraryValid wraps CAPI Core_IsAnimationLibraryValid
func IsAnimationLibraryValid(name string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_IsAnimationLibraryValid(name)
}

// AreInteriorWeaponsAllowed wraps CAPI Core_AreInteriorWeaponsAllowed
func AreInteriorWeaponsAllowed() bool {
	c := runtime.Instance().CAPI()
	return c.Core_AreInteriorWeaponsAllowed()
}

// AllowInteriorWeapons wraps CAPI Core_AllowInteriorWeapons
func AllowInteriorWeapons(allow bool) bool {
	c := runtime.Instance().CAPI()
	return c.Core_AllowInteriorWeapons(allow)
}

// BlockIPAddress wraps CAPI Core_BlockIpAddress
func BlockIPAddress(ipAddress string, timeMS int32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_BlockIpAddress(ipAddress, timeMS)
}

// UnBlockIPAddress wraps CAPI Core_UnBlockIpAddress
func UnBlockIPAddress(ipAddress string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_UnBlockIpAddress(ipAddress)
}

// DisableEntryExitMarkers wraps CAPI Core_DisableEntryExitMarkers
func DisableEntryExitMarkers() bool {
	c := runtime.Instance().CAPI()
	return c.Core_DisableEntryExitMarkers()
}

// DisableNameTagsLOS wraps CAPI Core_DisableNameTagsLOS
func DisableNameTagsLOS() bool {
	c := runtime.Instance().CAPI()
	return c.Core_DisableNameTagsLOS()
}

// EnableZoneNames wraps CAPI Core_EnableZoneNames
func EnableZoneNames(enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Core_EnableZoneNames(enable)
}

// ShowGameTextForAll wraps CAPI Core_ShowGameTextForAll
func ShowGameTextForAll(msg string, time int32, style int32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_ShowGameTextForAll(msg, time, style)
}

// HideGameTextForAll wraps CAPI Core_HideGameTextForAll
func HideGameTextForAll(style int32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_HideGameTextForAll(style)
}

// NetworkStatsString wraps CAPI Core_NetworkStats and returns a string.
func NetworkStatsString() (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Core_NetworkStatsString()
}

// ServerTickRate wraps CAPI Core_ServerTickRate
func ServerTickRate() int32 {
	c := runtime.Instance().CAPI()
	return c.Core_ServerTickRate()
}

// GetWeaponNameString wraps CAPI Core_GetWeaponName and returns a string.
func GetWeaponNameString(weaponid int32) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.Core_GetWeaponNameString(weaponid)
}

// SetChatRadius wraps CAPI Core_SetChatRadius
func SetChatRadius(globalChatRadius float32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_SetChatRadius(globalChatRadius)
}

// SetMarkerRadius wraps CAPI Core_SetMarkerRadius
func SetMarkerRadius(playerMarkerRadius float32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_SetMarkerRadius(playerMarkerRadius)
}

// SendRconCommand wraps CAPI Core_SendRconCommand
func SendRconCommand(command string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_SendRconCommand(command)
}

// SetDeathDropAmount wraps CAPI Core_SetDeathDropAmount
func SetDeathDropAmount(amount int32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_SetDeathDropAmount(amount)
}

// GameModeSetText wraps CAPI Core_GameMode_SetText
func GameModeSetText(string string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_GameMode_SetText(string)
}

// SetGravity wraps CAPI Core_SetGravity
func SetGravity(gravity float32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_SetGravity(gravity)
}

// GetGravity wraps CAPI Core_GetGravity
func GetGravity() float32 {
	c := runtime.Instance().CAPI()
	return c.Core_GetGravity()
}

// SetNameTagsDrawDistance wraps CAPI Core_SetNameTagsDrawDistance
func SetNameTagsDrawDistance(distance float32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_SetNameTagsDrawDistance(distance)
}

// SetWeather wraps CAPI Core_SetWeather
func SetWeather(weatherid int32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_SetWeather(weatherid)
}

// SetWorldTime wraps CAPI Core_SetWorldTime
func SetWorldTime(hour int32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_SetWorldTime(hour)
}

// ShowNameTags wraps CAPI Core_ShowNameTags
func ShowNameTags(show bool) bool {
	c := runtime.Instance().CAPI()
	return c.Core_ShowNameTags(show)
}

// ShowPlayerMarkers wraps CAPI Core_ShowPlayerMarkers
func ShowPlayerMarkers(mode int32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_ShowPlayerMarkers(mode)
}

// UsePedAnims wraps CAPI Core_UsePedAnims
func UsePedAnims() bool {
	c := runtime.Instance().CAPI()
	return c.Core_UsePedAnims()
}

// GetWeather wraps CAPI Core_GetWeather
func GetWeather() int32 {
	c := runtime.Instance().CAPI()
	return c.Core_GetWeather()
}

// GetWorldTime wraps CAPI Core_GetWorldTime
func GetWorldTime() int32 {
	c := runtime.Instance().CAPI()
	return c.Core_GetWorldTime()
}

// ToggleChatTextReplacement wraps CAPI Core_ToggleChatTextReplacement
func ToggleChatTextReplacement(enable bool) bool {
	c := runtime.Instance().CAPI()
	return c.Core_ToggleChatTextReplacement(enable)
}

// IsChatTextReplacementToggled wraps CAPI Core_IsChatTextReplacementToggled
func IsChatTextReplacementToggled() bool {
	c := runtime.Instance().CAPI()
	return c.Core_IsChatTextReplacementToggled()
}

// IsNickNameValid wraps CAPI Core_IsNickNameValid
func IsNickNameValid(name string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_IsNickNameValid(name)
}

// AllowNickNameCharacter wraps CAPI Core_AllowNickNameCharacter
func AllowNickNameCharacter(character int32, allow bool) bool {
	c := runtime.Instance().CAPI()
	return c.Core_AllowNickNameCharacter(character, allow)
}

// IsNickNameCharacterAllowed wraps CAPI Core_IsNickNameCharacterAllowed
func IsNickNameCharacterAllowed(character int32) bool {
	c := runtime.Instance().CAPI()
	return c.Core_IsNickNameCharacterAllowed(character)
}

// ClearBanList wraps CAPI Core_ClearBanList
func ClearBanList() bool {
	c := runtime.Instance().CAPI()
	return c.Core_ClearBanList()
}

// IsIPAddressBanned wraps CAPI Core_IsIpAddressBanned
func IsIPAddressBanned(ip string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_IsIpAddressBanned(ip)
}

// GetWeaponSlot wraps CAPI Core_GetWeaponSlot
func GetWeaponSlot(weapon uint8) int32 {
	c := runtime.Instance().CAPI()
	return c.Core_GetWeaponSlot(weapon)
}

// AddRule wraps CAPI Core_AddRule
func AddRule(name string, value string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_AddRule(name, value)
}

// IsValidRule wraps CAPI Core_IsValidRule
func IsValidRule(name string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_IsValidRule(name)
}

// RemoveRule wraps CAPI Core_RemoveRule
func RemoveRule(name string) bool {
	c := runtime.Instance().CAPI()
	return c.Core_RemoveRule(name)
}
