// Code generated by tools/codegen - DO NOT EDIT
package textdraw

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI TextDraw_Create
func Create(x float32, y float32, text string, id *int32) *omp.TextDraw {
	c := runtime.Instance().CAPI()
	res := c.TextDraw_Create(x, y, text, id)
	return omp.NewTextDraw(res)
}

// Destroy wraps CAPI TextDraw_Destroy
func Destroy(textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_Destroy(textdraw.Handle())
}

// FromID wraps CAPI TextDraw_FromID
func FromID(textdrawid int32) *omp.TextDraw {
	c := runtime.Instance().CAPI()
	res := c.TextDraw_FromID(textdrawid)
	return omp.NewTextDraw(res)
}

// GetID wraps CAPI TextDraw_GetID
func GetID(textdraw *omp.TextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetID(textdraw.Handle())
}

// IsValid wraps CAPI TextDraw_IsValid
func IsValid(textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_IsValid(textdraw.Handle())
}

// IsVisibleForPlayer wraps CAPI TextDraw_IsVisibleForPlayer
func IsVisibleForPlayer(player *omp.Player, textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_IsVisibleForPlayer(player.Handle(), textdraw.Handle())
}

// SetLetterSize wraps CAPI TextDraw_SetLetterSize
func SetLetterSize(textdraw *omp.TextDraw, sizeX float32, sizeY float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetLetterSize(textdraw.Handle(), sizeX, sizeY)
}

// SetTextSize wraps CAPI TextDraw_SetTextSize
func SetTextSize(textdraw *omp.TextDraw, sizeX float32, sizeY float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetTextSize(textdraw.Handle(), sizeX, sizeY)
}

// SetAlignment wraps CAPI TextDraw_SetAlignment
func SetAlignment(textdraw *omp.TextDraw, alignment int32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetAlignment(textdraw.Handle(), alignment)
}

// SetColor wraps CAPI TextDraw_SetColor
func SetColor(textdraw *omp.TextDraw, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetColor(textdraw.Handle(), color)
}

// SetUseBox wraps CAPI TextDraw_SetUseBox
func SetUseBox(textdraw *omp.TextDraw, use bool) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetUseBox(textdraw.Handle(), use)
}

// SetBoxColor wraps CAPI TextDraw_SetBoxColor
func SetBoxColor(textdraw *omp.TextDraw, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetBoxColor(textdraw.Handle(), color)
}

// SetShadow wraps CAPI TextDraw_SetShadow
func SetShadow(textdraw *omp.TextDraw, size int32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetShadow(textdraw.Handle(), size)
}

// SetOutline wraps CAPI TextDraw_SetOutline
func SetOutline(textdraw *omp.TextDraw, size int32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetOutline(textdraw.Handle(), size)
}

// SetBackgroundColor wraps CAPI TextDraw_SetBackgroundColor
func SetBackgroundColor(textdraw *omp.TextDraw, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetBackgroundColor(textdraw.Handle(), color)
}

// SetFont wraps CAPI TextDraw_SetFont
func SetFont(textdraw *omp.TextDraw, font int32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetFont(textdraw.Handle(), font)
}

// SetProportional wraps CAPI TextDraw_SetProportional
func SetProportional(textdraw *omp.TextDraw, set bool) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetProportional(textdraw.Handle(), set)
}

// SetSelectable wraps CAPI TextDraw_SetSelectable
func SetSelectable(textdraw *omp.TextDraw, set bool) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetSelectable(textdraw.Handle(), set)
}

// ShowForPlayer wraps CAPI TextDraw_ShowForPlayer
func ShowForPlayer(player *omp.Player, textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_ShowForPlayer(player.Handle(), textdraw.Handle())
}

// HideForPlayer wraps CAPI TextDraw_HideForPlayer
func HideForPlayer(player *omp.Player, textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_HideForPlayer(player.Handle(), textdraw.Handle())
}

// ShowForAll wraps CAPI TextDraw_ShowForAll
func ShowForAll(textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_ShowForAll(textdraw.Handle())
}

// HideForAll wraps CAPI TextDraw_HideForAll
func HideForAll(textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_HideForAll(textdraw.Handle())
}

// SetString wraps CAPI TextDraw_SetString
func SetString(textdraw *omp.TextDraw, text string) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetString(textdraw.Handle(), text)
}

// SetPreviewModel wraps CAPI TextDraw_SetPreviewModel
func SetPreviewModel(textdraw *omp.TextDraw, model int32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetPreviewModel(textdraw.Handle(), model)
}

// SetPreviewRot wraps CAPI TextDraw_SetPreviewRot
func SetPreviewRot(textdraw *omp.TextDraw, rotationX float32, rotationY float32, rotationZ float32, zoom float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetPreviewRot(textdraw.Handle(), rotationX, rotationY, rotationZ, zoom)
}

// SetPreviewVehCol wraps CAPI TextDraw_SetPreviewVehCol
func SetPreviewVehCol(textdraw *omp.TextDraw, color1 int32, color2 int32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetPreviewVehCol(textdraw.Handle(), color1, color2)
}

// SetPos wraps CAPI TextDraw_SetPos
func SetPos(textdraw *omp.TextDraw, x float32, y float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetPos(textdraw.Handle(), x, y)
}

// GetStringString wraps CAPI TextDraw_GetString and returns a string.
func GetStringString(textdraw *omp.TextDraw) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetStringString(textdraw.Handle())
}

// GetLetterSize wraps CAPI TextDraw_GetLetterSize
func GetLetterSize(textdraw *omp.TextDraw, sizeX *float32, sizeY *float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetLetterSize(textdraw.Handle(), sizeX, sizeY)
}

// GetTextSize wraps CAPI TextDraw_GetTextSize
func GetTextSize(textdraw *omp.TextDraw, sizeX *float32, sizeY *float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetTextSize(textdraw.Handle(), sizeX, sizeY)
}

// GetPos wraps CAPI TextDraw_GetPos
func GetPos(textdraw *omp.TextDraw, x *float32, y *float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetPos(textdraw.Handle(), x, y)
}

// GetColor wraps CAPI TextDraw_GetColor
func GetColor(textdraw *omp.TextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetColor(textdraw.Handle())
}

// GetBoxColor wraps CAPI TextDraw_GetBoxColor
func GetBoxColor(textdraw *omp.TextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetBoxColor(textdraw.Handle())
}

// GetBackgroundColor wraps CAPI TextDraw_GetBackgroundColor
func GetBackgroundColor(textdraw *omp.TextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetBackgroundColor(textdraw.Handle())
}

// GetShadow wraps CAPI TextDraw_GetShadow
func GetShadow(textdraw *omp.TextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetShadow(textdraw.Handle())
}

// GetOutline wraps CAPI TextDraw_GetOutline
func GetOutline(textdraw *omp.TextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetOutline(textdraw.Handle())
}

// GetFont wraps CAPI TextDraw_GetFont
func GetFont(textdraw *omp.TextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetFont(textdraw.Handle())
}

// IsBox wraps CAPI TextDraw_IsBox
func IsBox(textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_IsBox(textdraw.Handle())
}

// IsProportional wraps CAPI TextDraw_IsProportional
func IsProportional(textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_IsProportional(textdraw.Handle())
}

// IsSelectable wraps CAPI TextDraw_IsSelectable
func IsSelectable(textdraw *omp.TextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_IsSelectable(textdraw.Handle())
}

// GetAlignment wraps CAPI TextDraw_GetAlignment
func GetAlignment(textdraw *omp.TextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetAlignment(textdraw.Handle())
}

// GetPreviewModel wraps CAPI TextDraw_GetPreviewModel
func GetPreviewModel(textdraw *omp.TextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetPreviewModel(textdraw.Handle())
}

// GetPreviewRot wraps CAPI TextDraw_GetPreviewRot
func GetPreviewRot(textdraw *omp.TextDraw, x *float32, y *float32, z *float32, zoom *float32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetPreviewRot(textdraw.Handle(), x, y, z, zoom)
}

// GetPreviewVehColor wraps CAPI TextDraw_GetPreviewVehColor
func GetPreviewVehColor(textdraw *omp.TextDraw, color1 *int32, color2 *int32) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_GetPreviewVehColor(textdraw.Handle(), color1, color2)
}

// SetStringForPlayer wraps CAPI TextDraw_SetStringForPlayer
func SetStringForPlayer(textdraw *omp.TextDraw, player *omp.Player, text string) bool {
	c := runtime.Instance().CAPI()
	return c.TextDraw_SetStringForPlayer(textdraw.Handle(), player.Handle(), text)
}
