// Code generated by tools/codegen - DO NOT EDIT
package playertextdraw

import (
	"github.com/ompgo-dev/ompgo/pkg/omp"
	"github.com/ompgo-dev/ompgo/pkg/runtime"
)

// Create wraps CAPI PlayerTextDraw_Create
func Create(player *omp.Player, x float32, y float32, text string, id *int32) *omp.PlayerTextDraw {
	c := runtime.Instance().CAPI()
	res := c.PlayerTextDraw_Create(player.Handle(), x, y, text, id)
	return omp.NewPlayerTextDraw(res)
}

// Destroy wraps CAPI PlayerTextDraw_Destroy
func Destroy(player *omp.Player, textdraw *omp.PlayerTextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_Destroy(player.Handle(), textdraw.Handle())
}

// FromID wraps CAPI PlayerTextDraw_FromID
func FromID(player *omp.Player, textdrawid int32) *omp.PlayerTextDraw {
	c := runtime.Instance().CAPI()
	res := c.PlayerTextDraw_FromID(player.Handle(), textdrawid)
	return omp.NewPlayerTextDraw(res)
}

// GetID wraps CAPI PlayerTextDraw_GetID
func GetID(player *omp.Player, textdraw *omp.PlayerTextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetID(player.Handle(), textdraw.Handle())
}

// IsValid wraps CAPI PlayerTextDraw_IsValid
func IsValid(player *omp.Player, textdraw *omp.PlayerTextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_IsValid(player.Handle(), textdraw.Handle())
}

// IsVisible wraps CAPI PlayerTextDraw_IsVisible
func IsVisible(player *omp.Player, textdraw *omp.PlayerTextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_IsVisible(player.Handle(), textdraw.Handle())
}

// SetLetterSize wraps CAPI PlayerTextDraw_SetLetterSize
func SetLetterSize(player *omp.Player, textdraw *omp.PlayerTextDraw, x float32, y float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetLetterSize(player.Handle(), textdraw.Handle(), x, y)
}

// SetTextSize wraps CAPI PlayerTextDraw_SetTextSize
func SetTextSize(player *omp.Player, textdraw *omp.PlayerTextDraw, x float32, y float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetTextSize(player.Handle(), textdraw.Handle(), x, y)
}

// SetAlignment wraps CAPI PlayerTextDraw_SetAlignment
func SetAlignment(player *omp.Player, textdraw *omp.PlayerTextDraw, alignment int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetAlignment(player.Handle(), textdraw.Handle(), alignment)
}

// SetColor wraps CAPI PlayerTextDraw_SetColor
func SetColor(player *omp.Player, textdraw *omp.PlayerTextDraw, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetColor(player.Handle(), textdraw.Handle(), color)
}

// UseBox wraps CAPI PlayerTextDraw_UseBox
func UseBox(player *omp.Player, textdraw *omp.PlayerTextDraw, use bool) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_UseBox(player.Handle(), textdraw.Handle(), use)
}

// SetBoxColor wraps CAPI PlayerTextDraw_SetBoxColor
func SetBoxColor(player *omp.Player, textdraw *omp.PlayerTextDraw, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetBoxColor(player.Handle(), textdraw.Handle(), color)
}

// SetShadow wraps CAPI PlayerTextDraw_SetShadow
func SetShadow(player *omp.Player, textdraw *omp.PlayerTextDraw, size int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetShadow(player.Handle(), textdraw.Handle(), size)
}

// SetOutline wraps CAPI PlayerTextDraw_SetOutline
func SetOutline(player *omp.Player, textdraw *omp.PlayerTextDraw, size int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetOutline(player.Handle(), textdraw.Handle(), size)
}

// SetBackgroundColor wraps CAPI PlayerTextDraw_SetBackgroundColor
func SetBackgroundColor(player *omp.Player, textdraw *omp.PlayerTextDraw, color uint32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetBackgroundColor(player.Handle(), textdraw.Handle(), color)
}

// SetFont wraps CAPI PlayerTextDraw_SetFont
func SetFont(player *omp.Player, textdraw *omp.PlayerTextDraw, font int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetFont(player.Handle(), textdraw.Handle(), font)
}

// SetProportional wraps CAPI PlayerTextDraw_SetProportional
func SetProportional(player *omp.Player, textdraw *omp.PlayerTextDraw, set bool) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetProportional(player.Handle(), textdraw.Handle(), set)
}

// SetSelectable wraps CAPI PlayerTextDraw_SetSelectable
func SetSelectable(player *omp.Player, textdraw *omp.PlayerTextDraw, set bool) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetSelectable(player.Handle(), textdraw.Handle(), set)
}

// Show wraps CAPI PlayerTextDraw_Show
func Show(player *omp.Player, textdraw *omp.PlayerTextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_Show(player.Handle(), textdraw.Handle())
}

// Hide wraps CAPI PlayerTextDraw_Hide
func Hide(player *omp.Player, textdraw *omp.PlayerTextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_Hide(player.Handle(), textdraw.Handle())
}

// SetString wraps CAPI PlayerTextDraw_SetString
func SetString(player *omp.Player, textdraw *omp.PlayerTextDraw, text string) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetString(player.Handle(), textdraw.Handle(), text)
}

// SetPreviewModel wraps CAPI PlayerTextDraw_SetPreviewModel
func SetPreviewModel(player *omp.Player, textdraw *omp.PlayerTextDraw, model int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetPreviewModel(player.Handle(), textdraw.Handle(), model)
}

// SetPreviewRot wraps CAPI PlayerTextDraw_SetPreviewRot
func SetPreviewRot(player *omp.Player, textdraw *omp.PlayerTextDraw, rx float32, ry float32, rz float32, zoom float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetPreviewRot(player.Handle(), textdraw.Handle(), rx, ry, rz, zoom)
}

// SetPreviewVehCol wraps CAPI PlayerTextDraw_SetPreviewVehCol
func SetPreviewVehCol(player *omp.Player, textdraw *omp.PlayerTextDraw, color1 int32, color2 int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetPreviewVehCol(player.Handle(), textdraw.Handle(), color1, color2)
}

// SetPos wraps CAPI PlayerTextDraw_SetPos
func SetPos(player *omp.Player, textdraw *omp.PlayerTextDraw, x float32, y float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_SetPos(player.Handle(), textdraw.Handle(), x, y)
}

// GetStringString wraps CAPI PlayerTextDraw_GetString and returns a string.
func GetStringString(player *omp.Player, textdraw *omp.PlayerTextDraw) (string, bool) {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetStringString(player.Handle(), textdraw.Handle())
}

// GetLetterSize wraps CAPI PlayerTextDraw_GetLetterSize
func GetLetterSize(player *omp.Player, textdraw *omp.PlayerTextDraw, x *float32, y *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetLetterSize(player.Handle(), textdraw.Handle(), x, y)
}

// GetTextSize wraps CAPI PlayerTextDraw_GetTextSize
func GetTextSize(player *omp.Player, textdraw *omp.PlayerTextDraw, x *float32, y *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetTextSize(player.Handle(), textdraw.Handle(), x, y)
}

// GetPos wraps CAPI PlayerTextDraw_GetPos
func GetPos(player *omp.Player, textdraw *omp.PlayerTextDraw, x *float32, y *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetPos(player.Handle(), textdraw.Handle(), x, y)
}

// GetColor wraps CAPI PlayerTextDraw_GetColor
func GetColor(player *omp.Player, textdraw *omp.PlayerTextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetColor(player.Handle(), textdraw.Handle())
}

// GetBoxColor wraps CAPI PlayerTextDraw_GetBoxColor
func GetBoxColor(player *omp.Player, textdraw *omp.PlayerTextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetBoxColor(player.Handle(), textdraw.Handle())
}

// GetBackgroundColor wraps CAPI PlayerTextDraw_GetBackgroundColor
func GetBackgroundColor(player *omp.Player, textdraw *omp.PlayerTextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetBackgroundColor(player.Handle(), textdraw.Handle())
}

// GetShadow wraps CAPI PlayerTextDraw_GetShadow
func GetShadow(player *omp.Player, textdraw *omp.PlayerTextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetShadow(player.Handle(), textdraw.Handle())
}

// GetOutline wraps CAPI PlayerTextDraw_GetOutline
func GetOutline(player *omp.Player, textdraw *omp.PlayerTextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetOutline(player.Handle(), textdraw.Handle())
}

// GetFont wraps CAPI PlayerTextDraw_GetFont
func GetFont(player *omp.Player, textdraw *omp.PlayerTextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetFont(player.Handle(), textdraw.Handle())
}

// IsBox wraps CAPI PlayerTextDraw_IsBox
func IsBox(player *omp.Player, textdraw *omp.PlayerTextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_IsBox(player.Handle(), textdraw.Handle())
}

// IsProportional wraps CAPI PlayerTextDraw_IsProportional
func IsProportional(player *omp.Player, textdraw *omp.PlayerTextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_IsProportional(player.Handle(), textdraw.Handle())
}

// IsSelectable wraps CAPI PlayerTextDraw_IsSelectable
func IsSelectable(player *omp.Player, textdraw *omp.PlayerTextDraw) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_IsSelectable(player.Handle(), textdraw.Handle())
}

// GetAlignment wraps CAPI PlayerTextDraw_GetAlignment
func GetAlignment(player *omp.Player, textdraw *omp.PlayerTextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetAlignment(player.Handle(), textdraw.Handle())
}

// GetPreviewModel wraps CAPI PlayerTextDraw_GetPreviewModel
func GetPreviewModel(player *omp.Player, textdraw *omp.PlayerTextDraw) int32 {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetPreviewModel(player.Handle(), textdraw.Handle())
}

// GetPreviewRot wraps CAPI PlayerTextDraw_GetPreviewRot
func GetPreviewRot(player *omp.Player, textdraw *omp.PlayerTextDraw, rx *float32, ry *float32, rz *float32, zoom *float32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetPreviewRot(player.Handle(), textdraw.Handle(), rx, ry, rz, zoom)
}

// GetPreviewVehColor wraps CAPI PlayerTextDraw_GetPreviewVehColor
func GetPreviewVehColor(player *omp.Player, textdraw *omp.PlayerTextDraw, color1 *int32, color2 *int32) bool {
	c := runtime.Instance().CAPI()
	return c.PlayerTextDraw_GetPreviewVehColor(player.Handle(), textdraw.Handle(), color1, color2)
}
